// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom MemoryRouter Route NavigateProps
// Source: react-router-dom
// (extracted from /run/media/kingwill101/disk2/code/code/dart_packages/react_workspace/.dart_tool/react/js/node_modules/react-router-dom/./dist/index.d.ts)
// ignore_for_file: type=lint

import 'package:react_core/react.dart';

/// Typed helper for the `reactRouterDom.MemoryRouter` foreign component.
///
/// Props from `MemoryRouter`:
///
/// basename?: string
/// future?: { v7_startTransition?: boolean; v7_relativeSplatPath?: boolean }
/// children?: React.ReactNode; initialEntries?: any[]; initialIndex?: number
ReactNode memoryRouter({
  String? key,
  List<ReactNode> children = const [],
  String? basename,
  FutureConfig? future,
  List<Object?>? initialEntries,
  num? initialIndex,
}) => foreignComponent(
  'reactRouterDom.MemoryRouter',
  key: key,
  props: {
    if (basename != null) 'basename': basename,
    if (future != null) 'future': future.toJson(),
    if (initialEntries != null) 'initialEntries': initialEntries,
    if (initialIndex != null) 'initialIndex': initialIndex,
  },
  children: children,
);

/// Typed helper for the `reactRouterDom.Route` foreign component.
///
/// Props from `Route`:
///
/// shouldRevalidate?: any; element?: React.ReactNode; HydrateFallback?: any
/// id?: any; lazy?: Record<string, unknown>
/// hydrateFallbackElement?: React.ReactNode; errorElement?: React.ReactNode
/// Component?: any; action?: any; path?: any; index?: false
/// hasErrorBoundary?: any; handle?: any; caseSensitive?: any; loader?: any
/// children?: React.ReactNode; ErrorBoundary?: any
ReactNode route({
  String? key,
  List<ReactNode> children = const [],
  Object? shouldRevalidate,
  ReactNode? element,
  Object? HydrateFallback,
  Object? id,
  Object? lazy,
  ReactNode? hydrateFallbackElement,
  ReactNode? errorElement,
  Object? Component,
  Object? action,
  Object? path,
  bool? index,
  Object? hasErrorBoundary,
  Object? handle,
  Object? caseSensitive,
  Object? loader,
  Object? ErrorBoundary,
}) => foreignComponent(
  'reactRouterDom.Route',
  key: key,
  props: {
    if (shouldRevalidate != null) 'shouldRevalidate': shouldRevalidate,
    if (element != null) 'element': element,
    if (HydrateFallback != null) 'HydrateFallback': HydrateFallback,
    if (id != null) 'id': id,
    if (lazy != null) 'lazy': lazy,
    if (hydrateFallbackElement != null)
      'hydrateFallbackElement': hydrateFallbackElement,
    if (errorElement != null) 'errorElement': errorElement,
    if (Component != null) 'Component': Component,
    if (action != null) 'action': action,
    if (path != null) 'path': path,
    if (index != null) 'index': index,
    if (hasErrorBoundary != null) 'hasErrorBoundary': hasErrorBoundary,
    if (handle != null) 'handle': handle,
    if (caseSensitive != null) 'caseSensitive': caseSensitive,
    if (loader != null) 'loader': loader,
    if (ErrorBoundary != null) 'ErrorBoundary': ErrorBoundary,
  },
  children: children,
);

/// Literal union: "route" | "path"
enum NavigatePropsRelative {
  route('route'),
  path('path');

  const NavigatePropsRelative(this.value);
  final String value;
}

/// Typed props for `FutureConfig`.
///
/// v7_startTransition?: boolean; v7_relativeSplatPath?: boolean
class FutureConfig {
  const FutureConfig({
    bool? this.v7_startTransition,
    bool? this.v7_relativeSplatPath,
  });

  /// TS: boolean
  final bool? v7_startTransition;

  /// TS: boolean
  final bool? v7_relativeSplatPath;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (v7_startTransition != null) 'v7_startTransition': v7_startTransition,
    if (v7_relativeSplatPath != null)
      'v7_relativeSplatPath': v7_relativeSplatPath,
  };
}

/// Typed props for `NavigateProps`.
///
/// relative?: "route" | "path"; to: any; replace?: boolean; state?: any
class NavigateProps {
  const NavigateProps({
    NavigatePropsRelative? this.relative,
    required Object this.to,
    bool? this.replace,
    Object? this.state,
  });

  /// TS: "route" | "path"
  final NavigatePropsRelative? relative;

  /// TS: any
  final Object to;

  /// TS: boolean
  final bool? replace;

  /// TS: any
  final Object? state;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (relative != null) 'relative': relative!.value,
    'to': to,
    if (replace != null) 'replace': replace,
    if (state != null) 'state': state,
  };
}
