include: package:lints/recommended.yaml

plugins:
  react_analyzer:
    path: packages/react_analyzer

analyzer:
  exclude:
    - tool/vendor/**
    - third_party/**
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
