name: react_workspace
environment:
  sdk: ">=3.12.0 <4.0.0"
workspace:
  - packages/react
  - packages/react_js
  - packages/react_dom
  - packages/react_codegen
  - packages/react_server
  - example
dependencies:
  shelf: ^1.4.0
  shelf_static: ^1.1.3
  watcher: ^1.1.0
dev_dependencies:
  test: ^1.31.2
