import 'package:react_core/react.dart';

/// Semantic usage demo — scanned by `react_analysis` instead of JS regex.
///
/// `dart_tool/lib/src/bundler/dart_usage.dart` walks Dart sources from
/// `client.dart`/`ssr.dart` and calls `ReactRuntimeUsageCollector`:
///
/// - `foreignComponent('reactRouter.Route')` → components
/// - `@ReactRuntimeSymbol(kind: hook, runtimeKey: 'reactRouter.useLocation')`
///   calls → hooks (generated hooks carry this metadata)

ReactNode App(({String? placeholder}) props) {
  // Component usage — collected as `reactRouter.Route`
  final a = foreignComponent('reactRouter.Route', props: {'path': '/'});
  final b = foreignComponent('reactRouter.Link', props: {'to': '/about'});
  return Fragment([a, b]);
}

/// Simulated generated hook with runtime metadata.
/// Real hooks in `react_router_dom`/`react_zustand` are generated by `react ts bind`.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useLocation',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
String useLocation() => '/';

@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useNavigate',
  targets: {ReactRenderTarget.browser},
)
void Function(String) useNavigate() => (String to) {};

ReactNode HookUsageDemo(({String? placeholder}) props) {
  final loc = useLocation(); // collected as `reactRouter.useLocation`
  useNavigate(); // collected as `reactRouter.useNavigate`
  return Text(loc);
}

/// Expected `dart_usage` manifest for `client.dart` that imports this file:
/// ```json
/// {
///   "components": ["reactRouter.Link", "reactRouter.Route"],
///   "hooks": ["reactRouter.useLocation", "reactRouter.useNavigate"]
/// }
/// ```
/// `react_tool` writes this to `.dart_tool/react/browser_usage.json` (and
/// `ssr_usage.json` for the SSR entrypoint) and prefers it over JS scanning.
