name: react_server
resolution: workspace
environment:
  sdk: ">=3.12.0 <4.0.0"
dependencies:
  react:
    path: ../react
  react_actions:
    path: ../react_actions
  react_js:
    path: ../react_js
dev_dependencies:
  server_testing: 0.4.0
  test: ^1.31.2
