name: react_server
resolution: workspace
environment:
  sdk: ">=3.12.0 <4.0.0"
dependencies:
  react:
    path: ../react
  react_actions:
    path: ../react_actions
  react_js:
    path: ../react_js
  shelf: ^1.4.0
