name: superdesk
resolution: workspace
description: A React Dart application (client-only).
publish_to: none

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  react: {path: ../packages/react}
  react_js: {path: ../packages/react_js}
  react_dom: {path: ../packages/react_dom}
  react_web: {path: ../packages/react_web}
  react_actions: {path: ../packages/react_actions}
  react_router: {path: ../packages/react_router}

dev_dependencies:
  build_runner: ^2.15.3
  react_codegen: {path: ../packages/react_codegen}
  react_tool: {path: ../packages/react_tool}
  lints: ^6.1.0