part of '../ts_bindings.dart';

/// Generates a Dart source file with typed foreign-component helpers.
String generateBindings({
  required String specifier,
  required List<TsIrDeclaration> declarations,
  required String commandLine,
  String? prefix,
  String? entryComment,
  String typePrefix = '',
}) {
  final resolvedPrefix = prefix ?? lowerCamel(specifier);
  final registry = _TypeRegistry(typePrefix: typePrefix);

  final hasFunction = declarations.any((d) => d.kind == 'function');
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT EDIT.')
    ..writeln('// Generated by: $commandLine')
    ..writeln('// Source: $specifier')
    ..writeln(
      '// (extracted from ${entryComment ?? 'the package types entry'})',
    )
    ..writeln('// ignore_for_file: type=lint')
    ..writeln();
  if (hasFunction) {
    buffer.writeln("import 'dart:js_interop';");
    buffer.writeln("import 'dart:js_interop_unsafe';");
    buffer.writeln();
  }
  buffer.writeln("import 'package:react_core/react.dart';");
  buffer.writeln();
  if (hasFunction) {
    // Reuse the typed hook decoder helpers for function return values.
    buffer.writeln(_hookHelpers());
    buffer.writeln();
  }

  // First pass: emit helpers and register all referenced types.
  final helperText = StringBuffer();
  for (final declaration in declarations) {
    _emitDeclaration(helperText, declaration, resolvedPrefix, registry);
    helperText.writeln();
  }
  buffer.write(helperText);

  // Second pass: typedefs, enums, classes (sorted for determinism).
  for (final name in registry.sortedTypedefNames()) {
    buffer.write(_emitTypedef(registry.typedefs[name]!));
    buffer.writeln();
  }
  for (final name in registry.sortedEnumNames()) {
    buffer.write(_emitEnum(registry.enums[name]!));
    buffer.writeln();
  }
  for (final name in registry.sortedClassNames()) {
    buffer.write(
      _emitClass(
        registry.classes[name]!,
        registry,
        includeDecoder: hasFunction,
      ),
    );
    buffer.writeln();
  }
  return buffer.toString();
}

void _emitDeclaration(
  StringBuffer buffer,
  TsIrDeclaration declaration,
  String prefix,
  _TypeRegistry registry,
) {
  final foreignName = '$prefix.${declaration.name}';
  // Dart helpers keep the bare component name (lowerCamel); the prefix only
  // namespaces the JS registration key used by the shim, so generated APIs
  // read like `outlet()` / `memoryRouter(...)` instead of `xOutlet()`.
  final functionName = lowerCamel(declaration.name);
  final props = declaration.props;

  // A `children` prop becomes the node children parameter, except when it
  // is exclusively a function (a render-prop). ReactNode, `any`, unions of
  // node types, etc. all funnel into the typed children list.
  final hasChildren = props.any(
    (p) => p.name == 'children' && p.type.kind != 'function',
  );
  final propParams = props.where((p) => !(hasChildren && p.name == 'children'));

  // Register nested types before emitting so type names resolve.
  for (final prop in propParams) {
    _collectTypes(prop.type, declaration.name, [prop.name], registry);
  }

  switch (declaration.kind) {
    case 'hook':
      // Hooks live in the separate hooks file (generateHooks); nothing is
      // emitted into the component bindings.
      return;
    case 'function':
      // Plain functions (e.g. renderMatches) — emit a function wrapper with
      // @ReactRuntimeSymbol(kind: function). They are not foreign components.
      final funcParams = declaration.params;
      final funcReturns = declaration.returns;
      for (final p in funcParams) {
        _collectTypes(p.type, declaration.name, [p.name], registry);
      }
      if (funcReturns != null) {
        _collectTypes(funcReturns, declaration.name, ['return'], registry);
      }
      buffer
        ..writeln('/// Typed helper for the `$foreignName` function.')
        ..writeln('///')
        ..writeln('/// See https://reactrouter.com/api/${declaration.name}.')
        ..writeln('@ReactRuntimeSymbol(')
        ..writeln('  kind: ReactRuntimeSymbolKind.function,')
        ..writeln("  runtimeKey: '$foreignName',")
        ..writeln(
          '  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},',
        )
        ..writeln(')');
      // Generate a plain function wrapper using the shared hook codec.
      // Input encoding: dictionary/object values use toJson().jsify(), primitives use jsify().
      // Return decoding reuses the hook helpers (_decodePairs, _decodeList, fromJs).
      final rawName = '_${functionName}Raw';
      final jsTarget =
          'globalThis.__reactDartBindings.$prefix.${declaration.name}';
      buffer.writeln("@JS('$jsTarget')");
      final externalParams = funcParams
          .map((p) => 'JSAny? ${p.name}')
          .join(', ');
      buffer.writeln('external JSAny? $rawName($externalParams);');
      // Dart signature: required positional first, then optional positional in brackets
      final requiredParams = <String>[];
      final optionalParams = <String>[];
      for (var i = 0; i < funcParams.length; i++) {
        final p = funcParams[i];
        final t = _hookDartType(p.type, registry);
        final typeStr = p.required ? t : _nullableType(t, false);
        final paramStr = '$typeStr ${_safeParamName(p.name)}';
        if (p.required) {
          requiredParams.add(paramStr);
        } else {
          optionalParams.add(paramStr);
        }
      }
      String sig;
      if (requiredParams.isEmpty && optionalParams.isEmpty) {
        sig = '';
      } else if (optionalParams.isEmpty) {
        sig = requiredParams.join(', ');
      } else if (requiredParams.isEmpty) {
        sig = '[${optionalParams.join(', ')}]';
      } else {
        sig = '${requiredParams.join(', ')}, [${optionalParams.join(', ')}]';
      }
      final dartReturn = funcReturns != null
          ? _hookDartType(funcReturns, registry)
          : 'Object?';
      final publicReturn = funcReturns == null
          ? 'JSAny?'
          : (funcReturns.kind == 'void'
                ? 'void'
                : _nullableType(dartReturn, false));
      buffer.writeln('$publicReturn $functionName($sig) {');
      // Encode each argument: object/dictionary values that have toJson use it, else jsify.
      final callArgs = funcParams
          .map((p) {
            final n = _safeParamName(p.name);
            final isObject =
                p.type.kind == 'object' &&
                (p.type.members?.isNotEmpty ?? false);
            if (isObject) {
              return p.required
                  ? '$n.toJson().jsify()'
                  : '$n?.toJson().jsify()';
            }
            if (p.type.kind == 'record' || p.type.kind == 'urlSearchParams') {
              return '$n.jsify()';
            }
            return '$n.jsify()';
          })
          .join(', ');
      buffer.writeln('  final raw = $rawName($callArgs);');
      if (funcReturns == null || funcReturns.kind == 'void') {
        buffer.writeln('  return;');
      } else if (funcReturns.kind == 'string' ||
          funcReturns.kind == 'number' ||
          funcReturns.kind == 'boolean') {
        buffer.writeln('  if (raw == null) return null;');
        if (funcReturns.kind == 'string') {
          buffer.writeln('  return (raw as JSString).toDart;');
        } else if (funcReturns.kind == 'number') {
          buffer.writeln('  return (raw as JSNumber).toDartDouble;');
        } else {
          buffer.writeln('  return (raw as JSBoolean).toDart;');
        }
      } else if (funcReturns.kind == 'array') {
        final inner = funcReturns.element ?? const TsIrType(kind: 'any');
        final innerDart = _hookDartType(inner, registry);
        buffer.writeln('  if (raw == null) return null;');
        if (innerDart == 'String') {
          buffer.writeln(
            '  return (raw as JSArray).toDart.map((e) => (e as JSString).toDart).toList();',
          );
        } else if (inner.kind == 'object') {
          buffer.writeln(
            '  return _decodeList<$innerDart>(raw as JSArray, (e) => $innerDart.fromJs(e as JSObject));',
          );
        } else {
          buffer.writeln('  return (raw as JSArray).toDart.cast();');
        }
      } else if (funcReturns.kind == 'record' ||
          funcReturns.kind == 'urlSearchParams') {
        buffer
          ..writeln('  if (raw == null) return null;')
          ..writeln('  return _decodePairs(raw as JSArray);');
      } else if (funcReturns.kind == 'object') {
        buffer.writeln('  if (raw == null) return null;');
        if ((funcReturns.members ?? const <TsIrProp>[]).isEmpty) {
          buffer.writeln('  return raw;');
        } else {
          buffer.writeln('  return $dartReturn.fromJs(raw as JSObject);');
        }
      } else {
        buffer.writeln('  if (raw == null) return null;');
        if (funcReturns.kind != 'void') {
          buffer.writeln('  return raw;');
        }
      }
      buffer.writeln('}');
      return;
    case 'component':
      final childrenRequired =
          hasChildren && props.firstWhere((p) => p.name == 'children').required;
      buffer
        ..writeln('/// Typed helper for the `$foreignName` foreign component.')
        ..writeln('///')
        ..writeln('/// Props from `${declaration.name}`:')
        ..writeln('///')
        ..writeln('/// ${_propsDoc(props)}')
        ..writeln('@ReactRuntimeSymbol(')
        ..writeln('  kind: ReactRuntimeSymbolKind.component,')
        ..writeln("  runtimeKey: '$foreignName',")
        ..writeln(
          '  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},',
        )
        ..writeln(')')
        ..writeln('ReactNode $functionName({')
        ..writeln('  String? key,');
      if (hasChildren) {
        buffer.writeln(
          childrenRequired
              ? '  required ReactChildren children,'
              : '  ReactChildren children = const [],',
        );
      }
      for (final prop in propParams) {
        _emitParam(buffer, prop, declaration.name, registry);
      }
      buffer
        ..writeln('}) => foreignComponent(')
        ..writeln("  '$foreignName',")
        ..writeln('  key: key,')
        ..writeln('  props: {');
      for (final prop in propParams) {
        buffer.writeln('    ${_propsMapEntry(prop)}');
      }
      buffer.writeln('  },');
      if (hasChildren) {
        buffer.writeln('  children: children,');
      }
      buffer
        ..writeln(');')
        ..writeln();

      final builderName = '${_pascalIdentifier(functionName)}PropsBuilder';
      buffer.writeln('/// Mutable typed builder for `$foreignName`.');
      buffer.writeln('final class $builderName {');
      for (final prop in propParams) {
        final dartName = _safeParamName(prop.name);
        final type = _nullableType(
          _dartType(prop.type, registry),
          prop.required,
        );
        buffer.writeln('  ${prop.required ? 'late ' : ''}$type $dartName;');
      }
      buffer
        ..writeln('  String? key;')
        ..writeln(
          hasChildren
              ? '  ${childrenRequired ? 'late ' : ''}ReactChildren children;'
              : '',
        )
        ..writeln()
        ..writeln(
          hasChildren
              ? '  ReactNode call([ReactChildren? childValues]) {'
              : '  ReactNode call() {',
        )
        ..writeln('    return $functionName(');
      for (final prop in propParams) {
        final dartName = _safeParamName(prop.name);
        buffer.writeln('      $dartName: $dartName,');
      }
      buffer
        ..writeln('      key: key,')
        ..writeln(hasChildren ? '      children: childValues ?? children,' : '')
        ..writeln('    );')
        ..writeln('  }')
        ..writeln('}')
        ..writeln();
      buffer.writeln(
        '$builderName ${_lowerCamel(functionName)}Props() => $builderName();',
      );
    case 'interface':
      // Registers the class; the second pass emits all classes once.
      registry.declarationClass(declaration.name, declaration.props);
    case 'alias':
      if (props.length == 1 && props.single.name == 'value') {
        // `type X = string` style alias → plain Dart typedef.
        final typedefName = registry.declarationTypedef(
          declaration.name,
          props.single,
        );
        // Register types referenced by the alias target (e.g. arrays).
        _collectTypes(props.single.type, declaration.name, const [
          'value',
        ], registry);
        buffer
          ..writeln('/// Typed alias for `${declaration.name}`.')
          ..writeln('///')
          ..writeln('/// ${_tsTypeDoc(props.single.type)}')
          ..writeln(
            'typedef $typedefName = ${_typedefTargetType(props.single.type, registry)};',
          );
      } else {
        registry.declarationClass(declaration.name, declaration.props);
      }
  }
}

String _pascalIdentifier(String value) =>
    value.isEmpty ? 'Component' : value[0].toUpperCase() + value.substring(1);

String _lowerCamel(String value) =>
    value.isEmpty ? value : value[0].toLowerCase() + value.substring(1);

/// Walks a type tree registering classes, enums, and callback typedefs.
void _collectTypes(
  TsIrType type,
  String declName,
  List<String> path,
  _TypeRegistry registry,
) {
  switch (type.kind) {
    case 'object':
      // Call-signature / opaque interfaces have no members; they behave as
      // opaque values (e.g. LazyRouteFunction) rather than props classes.
      if ((type.members ?? const <TsIrProp>[]).isEmpty) break;
      registry.objectName(type, declName, path);
      for (final member in type.members ?? const <TsIrProp>[]) {
        _collectTypes(member.type, declName, [...path, member.name], registry);
      }
    case 'function':
      registry.typedefName(type, declName, path);
      for (final parameter in type.params ?? const <TsIrProp>[]) {
        _collectTypes(parameter.type, declName, [
          ...path,
          parameter.name,
        ], registry);
      }
      if (type.returns case final returns?) {
        _collectTypes(returns, declName, [...path, 'return'], registry);
      }
    case 'array':
      _collectTypes(
        type.element ?? const TsIrType(kind: 'any'),
        declName,
        path,
        registry,
      );
    case 'literal':
      if (_isBoolUnion(_uniqueLiterals(type.literals ?? const []))) break;
      if ((type.literals ?? const []).length >= 2) {
        registry.enumName(type, declName, path);
      }
    default:
      break;
  }
}

void _emitParam(
  StringBuffer buffer,
  TsIrProp prop,
  String declName,
  _TypeRegistry registry,
) {
  final dartName = _safeParamName(prop.name);
  final type = _nullableType(_dartType(prop.type, registry), prop.required);
  final requiredPrefix = prop.required ? 'required ' : '';
  if (prop.type.kind == 'function') {
    buffer
      ..writeln('    /// TS: ${_functionDoc(prop.type)}')
      ..writeln('    $requiredPrefix$type $dartName,');
  } else {
    buffer.writeln('    $requiredPrefix$type $dartName,');
  }
}

String _propsMapEntry(TsIrProp prop) {
  final name = _safeParamName(prop.name);
  final value = _jsonExpr(name, prop.type);
  return prop.required
      ? "'${prop.name}': $value,"
      : "if ($name != null) '${prop.name}': $value,";
}

/// The expression that encodes [source] (a Dart variable or member) into a
/// JSON-safe value for the props map / toJson.
String _jsonExpr(String source, TsIrType type) {
  switch (type.kind) {
    case 'object':
      if ((type.members ?? const <TsIrProp>[]).isEmpty) return source;
      return '$source.toJson()';
    case 'array':
      final element = type.element;
      if (element == null) return source;
      if (element.kind == 'object') {
        return '$source.map((e) => e.toJson()).toList()';
      }
      if (element.kind == 'literal' &&
          _isBoolUnion(_uniqueLiterals(element.literals ?? const []))) {
        return source;
      }
      if (element.kind == 'literal' &&
          (element.literals ?? const []).length >= 2) {
        return '$source.map((e) => e.value).toList()';
      }
      return source;
    case 'literal':
      {
        final literals = _uniqueLiterals(type.literals ?? const []);
        if (_isBoolUnion(literals)) return source;
        if (literals.length >= 2) return '$source.value';
        return source;
      }
    default:
      return source;
  }
}

/// Like [_jsonExpr] but promotes the receiver for method calls, for use on
/// non-promotable public fields inside `if (x != null)` collection entries.
String _jsonExprPromoted(String source, TsIrType type) {
  switch (type.kind) {
    case 'object':
      if ((type.members ?? const <TsIrProp>[]).isEmpty) return source;
      return '$source!.toJson()';
    case 'array':
      final element = type.element;
      if (element == null) return source;
      if (element.kind == 'object') {
        return '$source!.map((e) => e.toJson()).toList()';
      }
      if (element.kind == 'literal' &&
          _isBoolUnion(_uniqueLiterals(element.literals ?? const []))) {
        return source;
      }
      if (element.kind == 'literal' &&
          (element.literals ?? const []).length >= 2) {
        return '$source!.map((e) => e.value).toList()';
      }
      return source;
    case 'literal':
      {
        final literals = _uniqueLiterals(type.literals ?? const []);
        if (_isBoolUnion(literals)) return source;
        if (literals.length >= 2) return '$source!.value';
        return source;
      }
    default:
      return source;
  }
}

String _safeParamName(String name) {
  if (name.startsWith('_')) {
    final publicPart = name.replaceFirst(RegExp(r'^_+'), '');
    return publicPart.isEmpty
        ? 'privateValue'
        : 'private${upperCamel(publicPart)}';
  }
  if (_kReservedWords.contains(name)) return '${name}_';
  if (name == 'key') return 'elementKey';
  return name;
}

String _propsDoc(List<TsIrProp> props) {
  if (props.isEmpty) return 'No props.';
  final parts = props.map((p) {
    final tsType = _tsTypeDoc(p.type);
    return '${p.name}${p.required ? '' : '?'}: $tsType';
  });
  final lines = <String>[];
  var line = '';
  for (final part in parts) {
    if (line.isNotEmpty && line.length + part.length + 2 > 76) {
      lines.add(line);
      line = part;
    } else {
      line = line.isEmpty ? part : '$line; $part';
    }
  }
  if (line.isNotEmpty) lines.add(line);
  return lines.join('\n/// ');
}

String _tsTypeDoc(TsIrType type) {
  switch (type.kind) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'reactNode':
      return 'React.ReactNode';
    case 'hostValue':
      return 'host value';
    case 'any':
      return 'any';
    case 'void':
      return 'void';
    case 'unknown':
      return 'unknown';
    case 'null':
      return 'null';
    case 'array':
      return '${_tsTypeDoc(type.element ?? const TsIrType(kind: 'any'))}[]';
    case 'object':
      final members = type.members ?? const <TsIrProp>[];
      if (members.isEmpty) return 'Record<string, unknown>';
      final parts = members
          .map(
            (p) => '${p.name}${p.required ? '' : '?'}: ${_tsTypeDoc(p.type)}',
          )
          .join('; ');
      return '{ $parts }';
    case 'function':
      return _functionDoc(type);
    case 'literal':
      return (type.literals ?? const []).join(' | ');
    case 'union':
      return 'union';
    default:
      return 'unknown';
  }
}

String _functionDoc(TsIrType type) {
  final params = (type.params ?? const <TsIrProp>[])
      .map((p) => '${p.name}: ${_tsTypeDoc(p.type)}')
      .join(', ');
  final returns = type.returns == null ? 'void' : _tsTypeDoc(type.returns!);
  return '($params) => $returns';
}

// ---------------------------------------------------------------------------
// Typedef / enum / class emission
// ---------------------------------------------------------------------------

String _emitTypedef(_TypedefDef def) {
  if (def.isPlainAlias) {
    final target = _typedefTargetType(def.type, _emptyRegistryFor(def));
    return '/// Typed alias.\n'
        'typedef ${def.name} = $target;\n';
  }
  final type = def.type;
  final params = type.params ?? const <TsIrProp>[];
  final paramSpecs = <String>[];
  final paramCasts = <String>[];
  for (var i = 0; i < params.length; i++) {
    final p = params[i];
    paramSpecs.add(_callbackSpec(p.type));
    paramCasts.add(_callbackArg(p.name, p.type, i));
  }
  final returns = type.returns;
  final resultSpec = returns == null || returns.kind == 'void'
      ? 'reactVoid'
      : 'reactAny';
  final factoryName = lowerCamel(def.name);

  final buffer = StringBuffer()
    ..writeln('/// TS: ${_functionDoc(type)}')
    ..writeln(
      'typedef ${def.name} = ${_callbackReturnType(returns)} Function('
      '${params.map((p) => '${_callbackParamType(p.type)} ${_safeParamName(p.name)}').join(', ')});',
    )
    ..writeln()
    ..writeln(
      '/// Wraps a [${def.name}] into a [ReactCallback] for prop encoding.',
    )
    ..writeln('ReactCallback $factoryName(${def.name} fn) => ReactCallback(')
    ..writeln("  debugName: '${def.name}',")
    ..writeln('  signature: const (')
    ..writeln('    positional: [${paramSpecs.join(', ')}],')
    ..writeln('    result: $resultSpec,')
    ..writeln('    asynchronous: false,')
    ..writeln('  ),')
    ..writeln('  invoke: (arguments) {');
  if (returns == null || returns.kind == 'void') {
    buffer
      ..writeln('    fn(${paramCasts.join(', ')});')
      ..writeln('    return null;');
  } else {
    buffer.writeln('    return fn(${paramCasts.join(', ')});');
  }
  buffer
    ..writeln('  },')
    ..writeln(');');
  return buffer.toString();
}

/// Registry used to resolve names in a plain-alias typedef without mutating
/// the main registry (the alias target was already collected).
_TypeRegistry _emptyRegistryFor(_TypedefDef def) => _TypeRegistry();

String _typedefTargetType(TsIrType type, _TypeRegistry registry) {
  final base = _dartType(type, registry);
  if (base == 'Object?' && type.kind != 'array') return 'Object';
  return base;
}

String _callbackParamType(TsIrType type) {
  switch (type.kind) {
    case 'string':
      return 'String';
    case 'number':
      return 'num';
    case 'boolean':
      return 'bool';
    default:
      return 'Object?';
  }
}

String _callbackReturnType(TsIrType? returns) {
  if (returns == null || returns.kind == 'void') return 'void';
  switch (returns.kind) {
    case 'string':
      return 'String';
    case 'number':
      return 'num';
    case 'boolean':
      return 'bool';
    case 'reactNode':
      return 'ReactNode';
    default:
      return 'Object?';
  }
}

String _callbackSpec(TsIrType type) {
  switch (type.kind) {
    case 'string':
      return 'reactString';
    case 'number':
    case 'boolean':
    case 'literal':
      return 'reactAny';
    default:
      return 'reactAny';
  }
}

String _callbackArg(String name, TsIrType type, int index) {
  final arg = 'arguments[$index]';
  switch (type.kind) {
    case 'string':
      return '$arg as String';
    case 'number':
      return '$arg as num';
    case 'boolean':
      return '$arg as bool';
    default:
      return arg;
  }
}

String _emitEnum(_EnumDef def) {
  final members = <String>[];
  final used = <String>{};
  for (final literal in _uniqueLiterals(def.literals)) {
    var memberName = _enumConstantName(_literalValue(literal));
    if (memberName.isEmpty || !RegExp(r'^[a-zA-Z]').hasMatch(memberName)) {
      memberName = 'v$memberName';
    }
    if (memberName.isEmpty || memberName == 'v') {
      memberName = 'v${used.length}';
    }
    var candidate = memberName;
    var i = 2;
    while (used.contains(candidate)) {
      candidate = '$memberName$i';
      i++;
    }
    used.add(candidate);
    // Decode the serialized literal ("route" → route) so `.value` carries
    // the actual value the JS side expects.
    members.add("$candidate('${_literalValue(literal)}')");
  }
  final buffer = StringBuffer()
    ..writeln('/// Literal union: ${def.literals.join(' | ')}')
    ..writeln('enum ${def.name} {')
    ..writeln('  ${members.join(',\n  ')};')
    ..writeln('  const ${def.name}(this.value);')
    ..writeln('  final String value;')
    ..writeln()
    ..writeln('  /// Decodes a JS string value into this enum.')
    ..writeln(
      '  static ${def.name} fromValue(String value) => values.firstWhere(',
    )
    ..writeln('    (e) => e.value == value,')
    ..writeln(
      "    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown ${def.name}'),",
    )
    ..writeln('  );')
    ..writeln('}');
  return buffer.toString();
}

/// Dart constant name for an enum value. All-uppercase values ("POP", "PUSH")
/// become lowercase (pop, push) instead of lowerCamel's awkward "pOP".
String _enumConstantName(Object? value) {
  final s = value.toString();
  if (s.isNotEmpty && s == s.toUpperCase() && s != s.toLowerCase()) {
    return s.toLowerCase();
  }
  return lowerCamel(s);
}

String _emitClass(
  _ClassDef def,
  _TypeRegistry registry, {
  required bool includeDecoder,
}) {
  final props = def.type.members ?? const <TsIrProp>[];
  final buffer = StringBuffer()
    ..writeln('/// Typed props for `${def.type.name ?? def.name}`.')
    ..writeln('///')
    ..writeln('/// ${_propsDoc(props)}')
    ..writeln('class ${def.name} {')
    ..writeln('  const ${def.name}({');
  for (final prop in props) {
    final name = _safeParamName(prop.name);
    final type = _nullableType(_dartType(prop.type, registry), prop.required);
    buffer.writeln('    ${prop.required ? 'required ' : ''}$type this.$name,');
  }
  if (props.isEmpty) {
    buffer.writeln('  });'.replaceFirst('({', ''));
  } else {
    buffer.writeln('  });');
  }
  for (final prop in props) {
    final name = _safeParamName(prop.name);
    final type = _nullableType(_dartType(prop.type, registry), prop.required);
    buffer
      ..writeln()
      ..writeln('  /// TS: ${_tsTypeDoc(prop.type)}')
      ..writeln('  final $type $name;');
  }
  if (includeDecoder) {
    buffer
      ..writeln()
      ..writeln('  /// Decodes this value from a JavaScript object.')
      ..writeln('  factory ${def.name}.fromJs(JSObject js) {');
    for (final prop in props) {
      final name = _safeParamName(prop.name);
      buffer.writeln(
        "    final raw${upperCamel(name)} = js.getProperty<JSAny?>('${prop.name}'.toJS);",
      );
    }
    buffer.writeln('    return ${def.name}(');
    for (final prop in props) {
      final name = _safeParamName(prop.name);
      final raw = 'raw${upperCamel(name)}';
      final decoded = _bindingDecodeExpr(prop.type, raw, registry);
      buffer.writeln(
        prop.required
            ? '      $name: $decoded,'
            : '      $name: $raw == null || $raw.isUndefined ? null : $decoded,',
      );
    }
    buffer
      ..writeln('    );')
      ..writeln('  }');
  }
  buffer
    ..writeln()
    ..writeln('  /// JSON-safe map for prop encoding through the JS bridge.')
    ..writeln('  Map<String, Object?> toJson() => {');
  for (final prop in props) {
    final name = _safeParamName(prop.name);
    // Public fields don't promote after a null check, so method calls in
    // optional entries promote the receiver with `!`.
    final value = prop.required
        ? _jsonExpr(name, prop.type)
        : _jsonExprPromoted(name, prop.type);
    buffer.writeln(
      '    ${prop.required ? "'${prop.name}': $value" : "if ($name != null) '${prop.name}': $value"},',
    );
  }
  buffer
    ..writeln('  };')
    ..writeln('}');
  return buffer.toString();
}

String _bindingDecodeExpr(TsIrType type, String expr, _TypeRegistry registry) {
  switch (type.kind) {
    case 'string':
      return '($expr as JSString).toDart';
    case 'number':
      return '($expr as JSNumber).toDartDouble';
    case 'boolean':
      return '($expr as JSBoolean).toDart';
    case 'literal':
      final literals = _uniqueLiterals(type.literals ?? const []);
      if (_isBoolUnion(literals)) return '($expr as JSBoolean).toDart';
      if (literals.length >= 2) {
        return '${_enumNameFor(type, registry)}.fromValue(($expr as JSString).toDart)';
      }
      return _literalDartType(literals) == 'String'
          ? '($expr as JSString).toDart'
          : '($expr as JSNumber).toDart';
    case 'record':
    case 'urlSearchParams':
      return '_decodePairs($expr as JSArray)';
    case 'object':
      if ((type.members ?? const <TsIrProp>[]).isEmpty) {
        return '$expr as Object';
      }
      return '${_objectNameFor(type, registry)}.fromJs($expr as JSObject)';
    case 'array':
      final element = type.element ?? const TsIrType(kind: 'any');
      final inner = _dartType(element, registry);
      return '_decodeList<$inner>($expr as JSArray, (item) => ${_bindingDecodeExpr(element, 'item', registry)})';
    case 'function':
      return _bindingFnClosure(type, '($expr as JSFunction)', registry);
    case 'reactNode':
      return 'OpaqueReactNode($expr)';
    case 'hostValue':
    case 'any':
    case 'unknown':
    case 'null':
    case 'union':
      return expr;
    case 'void':
      return 'null';
    default:
      return '$expr as Object';
  }
}

/// Decodes a JS function using the positional callback typedef emitted for
/// component bindings and nested object values.
String _bindingFnClosure(
  TsIrType type,
  String functionExpression,
  _TypeRegistry registry,
) {
  final parameters = type.params ?? const <TsIrProp>[];
  final signature = <String>[];
  final arguments = <String>[];
  for (final parameter in parameters) {
    final name = _safeParamName(parameter.name);
    signature.add('${_callbackParamType(parameter.type)} $name');
    arguments.add(_fnArg(name, parameter.type));
  }
  final invocation =
      '$functionExpression.callAsFunction(null${arguments.isEmpty ? '' : ', ${arguments.join(', ')}'})';
  final returns = type.returns;
  if (returns == null || returns.kind == 'void') {
    return '(${signature.join(', ')}) { $invocation; }';
  }
  return '(${signature.join(', ')}) => ${_bindingDecodeExpr(returns, invocation, registry)}';
}
