part of '../ts_bindings.dart';

// ---------------------------------------------------------------------------
// Hook binding generation
//
// `use*` declarations carry per-hook params + a return type. Hooks run inside
// React's render call stack, so each generated Dart hook calls a bridge
// member on `globalThis.__reactDartHooks` or `globalThis.__reactDartBindings[namespace]` (registered by the generated shim)
// and decodes the shim's primitives/arrays into typed Dart values:
//
//   - primitives → direct casts (the external's return type is already JSX)
//   - literal unions → enums with `fromValue`
//   - records / URLSearchParams → `Map<String, String>` pairs
//   - tuples → Dart records (useSearchParams → (pairs, setter))
//   - objects → generated extension types + value classes with `fromJs(JSObject)` factories
//   - functions → closures over a JSFunction captured *during render*, so
//     navigating later from an event handler never calls the hook again
// ---------------------------------------------------------------------------

/// Generates a Dart hooks file for the extracted `use*` hooks.
///
/// [reuseTypeNames] lists top-level type names that live in a sibling
/// generated file ([bindingsImport], a Dart `import` path) the hooks file
/// references instead of redeclaring (e.g. the bindings file's enums).
String generateHooks({
  required String specifier,
  required List<TsIrDeclaration> declarations,
  required String commandLine,
  String? entryComment,
  String typePrefix = '',
  String? bindingsImport,
  Set<String>? reuseTypeNames,
  String namespace = '',
}) {
  final hooks = declarations.where((d) => d.kind == 'hook').toList();
  final registry = _TypeRegistry(
    typePrefix: typePrefix,
    reusedTypeNames: reuseTypeNames,
  );
  final bridgeTarget = namespace.isNotEmpty
      ? '__reactDartBindings.$namespace'
      : '__reactDartHooks';

  // First pass: register every value type referenced by return values.
  // Param types are inputs (encoded with jsify), so only their literals are
  // registered on demand while emitting the signatures.
  for (final hook in hooks) {
    final declBase = hook.name.startsWith('use')
        ? hook.name.substring(3)
        : hook.name;
    if (hook.returns != null) {
      _collectHookTypes(hook.returns!, declBase, const ['return'], registry);
    }
  }

  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT EDIT.')
    ..writeln('// Generated by: $commandLine')
    ..writeln('// Source: $specifier')
    ..writeln(
      '// (extracted from ${entryComment ?? 'the package types entry'})',
    )
    ..writeln('// ignore_for_file: type=lint')
    ..writeln()
    ..writeln("import 'dart:js_interop';")
    ..writeln("import 'package:react/react.dart';");
  if (bindingsImport != null) {
    buffer.writeln("import '$bindingsImport';");
  }
  buffer
    ..writeln()
    ..writeln('// Hook bindings for `$specifier`. Each hook is only available')
    ..writeln('// in JavaScript targets (browser client and Node SSR worker);')
    ..writeln('// it calls into the shim bridge (`$bridgeTarget`)')
    ..writeln('// and runs inside React\'s render call stack.')
    ..writeln();

  buffer.write(_hookHelpers());

  for (final hook in hooks) {
    buffer.write(
      _emitHook(
        hook,
        registry,
        bridgeTarget: bridgeTarget,
        namespace: namespace,
        specifier: specifier,
      ),
    );
    buffer.writeln();
  }

  for (final name in registry.sortedClassNames()) {
    buffer.write(_emitHookClass(registry.classes[name]!, registry));
    buffer.writeln();
  }
  for (final name in registry.sortedEnumNames()) {
    buffer.write(_emitEnum(registry.enums[name]!));
    buffer.writeln();
  }
  return buffer.toString();
}

String _hookHelpers() {
  return '''// Shared decode helpers for hook return values.
// Primitives and literals are decoded directly by the external's
// return type; objects with known shape use generated extension
// types (see below) for direct property access instead of
// converting to/from [[key, value]] pairs. Record / URLSearchParams
// types are still encoded as `[[k, v], ...]` pairs by the shim
// (via `toPairs`) until the shim learns to pass raw JS objects.
Map<String, String> _decodePairs(JSArray raw) {
  final result = <String, String>{};
  for (var i = 0; i < raw.length; i++) {
    final entry = (raw[i] as JSArray);
    result[(entry[0] as JSString).toDart] = (entry[1] as JSString).toDart;
  }
  return result;
}

List<T> _decodeList<T>(JSArray raw, T Function(JSAny? item) decode) {
  final result = <T>[];
  for (var i = 0; i < raw.length; i++) {
    result.add(decode(raw[i]));
  }
  return result;
}
''';
}

/// Registers value types (classes/enums) referenced by hook params/returns.
/// Function types are skipped: their options objects become Dart named
/// parameters, not classes.
void _collectHookTypes(
  TsIrType type,
  String declName,
  List<String> path,
  _TypeRegistry registry,
) {
  switch (type.kind) {
    case 'object':
      if ((type.members ?? const <TsIrProp>[]).isEmpty) break;
      registry.objectName(type, declName, path);
      for (final member in type.members ?? const <TsIrProp>[]) {
        _collectHookTypes(member.type, declName, [
          ...path,
          member.name,
        ], registry);
      }
    case 'literal':
      if (_isBoolUnion(_uniqueLiterals(type.literals ?? const []))) break;
      if ((type.literals ?? const []).length >= 2) {
        registry.enumName(type, declName, path);
      }
    case 'array':
      _collectHookTypes(type.element ?? const TsIrType(kind: 'any'), declName, [
        ...path,
        'element',
      ], registry);
    case 'record':
      _collectHookTypes(type.element ?? const TsIrType(kind: 'any'), declName, [
        ...path,
        'value',
      ], registry);
    case 'tuple':
      final elements = type.elements ?? const <TsIrType>[];
      for (var i = 0; i < elements.length; i++) {
        _collectHookTypes(elements[i], declName, [...path, 'item$i'], registry);
      }
    default:
      break;
  }
}

/// The Dart type for a hook param or decode target.
String _hookDartType(TsIrType type, _TypeRegistry registry) {
  switch (type.kind) {
    case 'string':
      return 'String';
    case 'number':
      return 'num';
    case 'boolean':
      return 'bool';
    case 'any':
    case 'unknown':
    case 'void':
    case 'null':
    case 'reactNode':
    case 'hostValue':
    case 'union':
    case 'indexedAccess':
      return 'Object?';
    case 'literal':
      final literals = _uniqueLiterals(type.literals ?? const []);
      if (_isBoolUnion(literals)) return 'bool';
      if (literals.length >= 2) return _enumNameFor(type, registry);
      return _literalDartType(literals);
    case 'record':
    case 'urlSearchParams':
      if (type.kind == 'urlSearchParams') return 'Map<String, String>';
      final value = _hookDartType(
        type.element ?? const TsIrType(kind: 'any'),
        registry,
      );
      if (value == 'String' || value == 'num' || value == 'bool') {
        return 'Map<String, $value>';
      }
      return 'Map<String, Object?>';
    case 'object':
      if ((type.members ?? const <TsIrProp>[]).isEmpty) return 'Object?';
      return _objectNameFor(type, registry);
    case 'array':
      final inner = _hookDartType(
        type.element ?? const TsIrType(kind: 'any'),
        registry,
      );
      if (inner == 'Object?') return 'List<Object?>';
      return 'List<$inner>';
    case 'function':
      return _hookFnSignature(type, registry);
    case 'tuple':
      final elements = type.elements ?? const <TsIrType>[];
      return '(${elements.map((e) => _hookDartType(e, registry)).join(', ')})';
    default:
      return 'Object?';
  }
}

/// Whether the last parameter is an object (an options bag). Such a param
/// becomes named Dart parameters instead of a positional object.
int _optionsSpreadIndex(List<TsIrProp> params) {
  if (params.isEmpty) return -1;
  final last = params.last;
  if (last.type.kind == 'object' &&
      (last.type.members ?? const <TsIrProp>[]).isNotEmpty) {
    return params.length - 1;
  }
  return -1;
}

/// Dart type for a function-type parameter. [required] distinguishes the
/// nullable/optional forms (`String? action` vs `String href`).
String _fnParamType(TsIrType type, {bool required = false}) {
  final base = switch (type.kind) {
    'string' => 'String',
    'number' => 'num',
    'boolean' => 'bool',
    _ => 'Object',
  };
  if (required && base == 'Object') return 'Object?';
  return required ? base : '$base?';
}

/// Loose Dart type for a hook's positional input parameters: inputs are
/// encoded with `jsify`, so structured values stay generic (`List<Object?>`)
/// rather than forcing generated value classes on the caller.
String _paramDartType(TsIrType type) {
  switch (type.kind) {
    case 'string':
      return 'String';
    case 'number':
      return 'num';
    case 'boolean':
      return 'bool';
    case 'array':
      return 'List<Object?>';
    default:
      return 'Object?';
  }
}

/// The inline Dart signature for a function type, e.g.
/// `void Function(Object? to, {bool? replace})`.
String _hookFnSignature(TsIrType type, _TypeRegistry registry) {
  final params = type.params ?? const <TsIrProp>[];
  final spreadIdx = _optionsSpreadIndex(params);
  final parts = <String>[];
  for (var i = 0; i < params.length; i++) {
    if (i == spreadIdx) continue;
    final p = params[i];
    final n = _safeParamName(p.name);
    // Function *types* cannot carry optional positional parameters in Dart,
    // so they are emitted as required-nullable instead of `[T? x]`.
    parts.add('${_fnParamType(p.type, required: p.required)} $n');
  }
  if (spreadIdx >= 0) {
    final members = params[spreadIdx].type.members ?? const <TsIrProp>[];
    final named = members
        .map(
          (m) =>
              '${_nullableType(_hookDartType(m.type, registry), false)} ${_safeParamName(m.name)}',
        )
        .join(', ');
    if (named.isNotEmpty) parts.add('{$named}');
  }
  final ret = type.returns == null || type.returns!.kind == 'void'
      ? 'void'
      : _hookDartType(type.returns!, registry);
  return '$ret Function(${parts.join(', ')})';
}

/// JS expression encoding a Dart argument before `callAsFunction`.
String _fnArg(String name, TsIrType type) {
  switch (type.kind) {
    case 'string':
    case 'number':
    case 'boolean':
      return '$name.toJS';
    default:
      return '$name.jsify()';
  }
}

/// Value expression for an options-map entry (enum values use `.value`).
String _fnArgValue(String name, TsIrType type) {
  if (type.kind == 'literal' && (type.literals ?? const []).length >= 2) {
    return '$name.value';
  }
  return name;
}

/// Builds `{'key': value, ...}` from non-null named options.
String _optionsMapLiteral(List<TsIrProp> members) {
  final entries = <String>[];
  for (final m in members) {
    final n = _safeParamName(m.name);
    entries.add("if ($n != null) '${m.name}': ${_fnArgValue(n, m.type)}");
  }
  return '<String, Object?>{${entries.join(', ')}}';
}

/// The JS return type declared on the per-hook external.
String _hookExternalReturn(TsIrType? returns) {
  switch (returns?.kind) {
    case 'string':
    case 'literal':
      final literals = _uniqueLiterals(returns?.literals ?? const []);
      if (_isBoolUnion(literals)) return 'JSBoolean';
      return 'JSString';
    case 'number':
      return 'JSNumber';
    case 'boolean':
      return 'JSBoolean';
    case 'record':
    case 'urlSearchParams':
    case 'tuple':
    case 'array':
      return 'JSArray';
    case 'object':
      return 'JSObject';
    case 'function':
      return 'JSFunction';
    default:
      return 'JSAny?';
  }
}

/// Decodes a JSAny? expression (a raw `callAsFunction`/array element result)
/// into a typed Dart expression.
String _elemDecode(TsIrType type, String expr, _TypeRegistry registry) {
  switch (type.kind) {
    case 'string':
      return '($expr as JSString).toDart';
    case 'number':
      return '($expr as JSNumber).toDart';
    case 'boolean':
      return '($expr as JSBoolean).toDart';
    case 'literal':
      final literals = _uniqueLiterals(type.literals ?? const []);
      if (_isBoolUnion(literals)) return '($expr as JSBoolean).toDart';
      if (literals.length >= 2) {
        return '${_enumNameFor(type, registry)}.fromValue(($expr as JSString).toDart)';
      }
      return _literalDartType(literals) == 'String'
          ? '($expr as JSString).toDart'
          : '($expr as JSNumber).toDart';
    case 'record':
    case 'urlSearchParams':
      return '_decodePairs($expr as JSArray)';
    case 'object':
      if ((type.members ?? const <TsIrProp>[]).isEmpty) return expr;
      return '${_objectNameFor(type, registry)}.fromJs($expr as JSObject)';
    case 'array':
      final element = type.element ?? const TsIrType(kind: 'any');
      return '_decodeList($expr as JSArray, (e) => ${_elemDecode(element, 'e', registry)})';
    case 'function':
      return _fnClosure(type, '($expr as JSFunction)', registry);
    default:
      return expr;
  }
}

/// A closure that invokes the captured [fnExpr] later, with the function
/// type's Dart signature. Options bags spread into named parameters.
String _fnClosure(TsIrType type, String fnExpr, _TypeRegistry registry) {
  final params = type.params ?? const <TsIrProp>[];
  final returns = type.returns;
  final spreadIdx = _optionsSpreadIndex(params);
  final sig = <String>[];
  final callArgs = <String>[];
  for (var i = 0; i < params.length; i++) {
    if (i == spreadIdx) continue;
    final p = params[i];
    final n = _safeParamName(p.name);
    // Function *types* cannot carry optional positional parameters in Dart,
    // so they are emitted as required-nullable instead of `[T? x]`.
    final t = _fnParamType(p.type, required: p.required);
    sig.add('$t $n');
    callArgs.add(_fnArg(n, p.type));
  }
  if (spreadIdx >= 0) {
    final members = params[spreadIdx].type.members ?? const <TsIrProp>[];
    final named = members
        .map(
          (m) =>
              '${_nullableType(_hookDartType(m.type, registry), false)} ${_safeParamName(m.name)}',
        )
        .join(', ');
    if (named.isNotEmpty) sig.add('{$named}');
    callArgs.add('${_optionsMapLiteral(members)}.jsify()');
  }
  final invocation =
      '$fnExpr.callAsFunction(null${callArgs.isEmpty ? '' : ', ${callArgs.join(', ')}'})';
  if (returns == null || returns.kind == 'void') {
    return '(${sig.join(', ')}) { $invocation; }';
  }
  return '(${sig.join(', ')}) => ${_elemDecode(returns, invocation, registry)}';
}

/// Emits one hook: the `@JS` external + the typed public function.
String _emitHook(
  TsIrDeclaration hook,
  _TypeRegistry registry, {
  required String bridgeTarget,
  required String namespace,
  required String specifier,
}) {
  final name = hook.name;
  final rawName = '_${name}Raw';
  final params = hook.params;
  final returns = hook.returns;
  final spreadIdx = _optionsSpreadIndex(params);
  final hasOptions = spreadIdx >= 0;
  final positional = <TsIrProp>[];
  TsIrProp? options;
  for (var i = 0; i < params.length; i++) {
    if (i == spreadIdx) {
      options = params[i];
    } else {
      positional.add(params[i]);
    }
  }

  // External declaration — every arg is JSAny?, the return is typed so
  // dart2js never has to cast a raw callAsFunction result.
  final extArgs = [
    for (var i = 0; i < positional.length + (hasOptions ? 1 : 0); i++)
      'JSAny? a$i',
  ].join(', ');
  final external = StringBuffer()
    ..writeln("@JS('globalThis.$bridgeTarget.$name')")
    ..writeln('external ${_hookExternalReturn(returns)} $rawName($extArgs);')
    ..writeln();

  // Public signature — inputs use the loose [_paramDartType] (they are
  // encoded with `jsify`), options members stay typed so enums encode via
  // `.value`.
  final sig = <String>[];
  for (final p in positional) {
    final n = _safeParamName(p.name);
    if (p.required) {
      sig.add('${_paramDartType(p.type)} $n');
    } else if (hasOptions) {
      // Dart cannot mix optional positional with named parameters, so
      // optional inputs become required-nullable when options are present.
      sig.add('${_nullableType(_paramDartType(p.type), false)} $n');
    } else {
      sig.add('[${_nullableType(_paramDartType(p.type), false)} $n]');
    }
  }
  if (hasOptions) {
    final members = options!.type.members ?? const <TsIrProp>[];
    final named = members
        .map(
          (m) =>
              '${_nullableType(_hookDartType(m.type, registry), false)} ${_safeParamName(m.name)}',
        )
        .join(', ');
    if (named.isNotEmpty) sig.add('{$named}');
  }
  final returnType = returns == null
      ? 'Object?'
      : _hookDartType(returns, registry);

  final effectiveNamespace = namespace.isNotEmpty
      ? namespace
      : lowerCamel(specifier.split('/').first);
  final runtimeKey = '$effectiveNamespace.$name';
  final buffer = StringBuffer()
    ..writeln('/// ${_hookDoc(hook)}')
    ..writeln('///')
    ..writeln('/// See https://reactrouter.com/hooks/${_hookUrl(name)}.')
    ..write(external.toString())
    ..writeln('@ReactHook()')
    ..writeln('@ReactRuntimeSymbol(')
    ..writeln('  kind: ReactRuntimeSymbolKind.hook,')
    ..writeln("  runtimeKey: '$runtimeKey',")
    ..writeln(
      '  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},',
    )
    ..writeln(')')
    ..writeln('$returnType $name(${sig.join(', ')}) {');

  // Options local (shared by the hook call and closure capture).
  if (hasOptions) {
    final members = options!.type.members ?? const <TsIrProp>[];
    buffer.writeln('  final options = ${_optionsMapLiteral(members)};');
  }
  final callArgs = <String>[
    // Optional positional inputs cross the bridge as Dart `null` (dart:js
    // interop has no `undefined` literal); the generated shim drops
    // trailing nulls so JS defaults (`function f(x = ...)`) fire — some
    // libraries (`Object.keys(init)`) throw on explicit `null`.
    for (final p in positional) '${_safeParamName(p.name)}.jsify()',
    if (hasOptions) 'options.jsify()',
  ];
  final call = '$rawName(${callArgs.join(', ')})';

  if (returns != null && returns.kind == 'function') {
    buffer
      ..writeln('  final fn = $call;')
      ..writeln('  return ${_fnClosure(returns, 'fn', registry)};');
  } else if (returns != null && returns.kind == 'tuple') {
    final elements = returns.elements ?? const <TsIrType>[];
    buffer.writeln('  final raw = $call;');
    final parts = <String>[];
    for (var i = 0; i < elements.length; i++) {
      parts.add(_elemDecode(elements[i], 'raw[$i]', registry));
    }
    buffer.writeln('  return (${parts.join(', ')});');
  } else {
    buffer.writeln('  return ${_topDecode(returns, call, registry)};');
  }
  buffer.writeln('}');
  return buffer.toString();
}

/// Decode for the top-level external call (whose return is already JSX).
String _topDecode(TsIrType? returns, String call, _TypeRegistry registry) {
  switch (returns?.kind) {
    case 'string':
    case 'number':
    case 'boolean':
      return '$call.toDart';
    case 'literal':
      final literals = _uniqueLiterals(returns!.literals ?? const []);
      if (_isBoolUnion(literals)) return '$call.toDart';
      if (literals.length >= 2) {
        return '${_enumNameFor(returns, registry)}.fromValue($call.toDart)';
      }
      return '$call.toDart';
    case 'record':
    case 'urlSearchParams':
      return '_decodePairs($call)';
    case 'object':
      if ((returns!.members ?? const <TsIrProp>[]).isEmpty) return call;
      return '${_objectNameFor(returns, registry)}.fromJs($call)';
    case 'array':
      final element = returns!.element ?? const TsIrType(kind: 'any');
      return '_decodeList($call, (e) => ${_elemDecode(element, 'e', registry)})';
    default:
      return call;
  }
}

String _hookDoc(TsIrDeclaration hook) {
  final params = hook.params
      .map((p) => '${p.name}${p.required ? '' : '?'}: ${_tsTypeDoc(p.type)}')
      .join(', ');
  final returns = hook.returns == null ? 'void' : _tsTypeDoc(hook.returns!);
  return '${hook.name}($params) => $returns';
}

String _hookUrl(String name) =>
    name.replaceFirst('use', '').toLowerCase().replaceAll(' ', '-');

/// Emits an extension type for direct JS property access and a value
/// class that wraps it for hook decode. The extension type provides
/// typed getters on the raw JS object, avoiding the generic
/// [[key, value]] pairs conversion.
String _emitHookClass(_ClassDef def, _TypeRegistry registry) {
  final props = def.type.members ?? const <TsIrProp>[];
  final className = def.name;
  final extName = '_${className}Js';
  final buffer = StringBuffer()
    ..writeln(
      '/// Typed JS interop extension for `$className` hook return values.',
    )
    ..writeln('///')
    ..writeln('/// Direct property access on the raw JS object avoids the')
    ..writeln('/// generic [[key, value]] pairs conversion used by')
    ..writeln('/// `_pairsMap` (removed in this generation).')
    ..writeln('extension type $extName(JSObject _) implements JSObject {');
  for (final prop in props) {
    final n = _safeParamName(prop.name);
    final extType = _hookExtType(prop.type);
    // The getter is also the JS property name in dart:js_interop; when the
    // Dart-safe name differs (e.g. `key` → `elementKey`), bind it back to
    // the real JS property with `@JS('...')`.
    final jsBinding = n == prop.name ? '' : "@JS('${prop.name}') ";
    if (prop.type.kind == 'function') {
      buffer.writeln('  ${jsBinding}external JSFunction get $n;');
    } else {
      buffer.writeln(
        '  ${jsBinding}external ${_nullableType(extType, prop.required)} get $n;',
      );
    }
  }
  buffer.writeln('}');
  buffer.writeln();
  buffer.writeln(
    '/// Value class for `$className` (decoded from the hook shim).',
  );
  buffer.writeln('///');
  buffer.writeln('/// ${_propsDoc(props)}');
  buffer.writeln('final class $className {');
  buffer.writeln('  $className._({');
  for (final prop in props) {
    final n = _safeParamName(prop.name);
    buffer.writeln('    required this.$n,');
  }
  buffer.writeln('  });');
  buffer.writeln();
  for (final prop in props) {
    final n = _safeParamName(prop.name);
    final dartType = _hookDartType(prop.type, registry);
    final nullable = _nullableType(dartType, prop.required);
    buffer
      ..writeln('  /// TS: ${_tsTypeDoc(prop.type)}')
      ..writeln('  final $nullable $n;');
  }

  // Factory from raw JSObject (for use with extension type)
  buffer.writeln();
  buffer.writeln("  /// Decodes the shim's raw JS object.");
  buffer.writeln('  factory $className.fromJs(JSObject js) {');
  buffer.writeln('    final v = $extName(js);');
  buffer.writeln('    return $className._(');
  for (final prop in props) {
    final n = _safeParamName(prop.name);
    buffer.writeln('      $n: ${_hookExtMemberDecode(prop, 'v', registry)},');
  }
  buffer.writeln('    );');
  buffer.writeln('  }');
  buffer.writeln();

  if (def.type.name == 'Location') {
    buffer
      ..writeln('  /// The full path including the query string.')
      ..writeln("  String get fullPath => '\$pathname\$search\$hash';")
      ..writeln()
      ..writeln('  @override')
      ..writeln('  String toString() => fullPath;');
  }
  buffer.writeln('}');
  return buffer.toString();
}

/// Decode one member from the extension type (`v.$n`) into its Dart value.
/// The extension type already provides typed property access; for object
/// members we wrap the raw JSObject in the generated value class.
String _hookExtMemberDecode(
  TsIrProp prop,
  String extVar,
  _TypeRegistry registry,
) {
  final n = _safeParamName(prop.name);
  final raw = '$extVar.$n';
  if (prop.required) {
    return _hookTypedExtDecode(prop.type, raw, registry);
  }
  if (prop.type.kind == 'function') {
    return '$raw == null ? null : ${_fnClosure(prop.type, '($raw as JSFunction)', registry)}';
  }
  if (prop.type.kind == 'object' &&
      (prop.type.members ?? const <TsIrProp>[]).isNotEmpty) {
    final target = _objectNameFor(prop.type, registry);
    return '$raw == null ? null : $target.fromJs($raw as JSObject)';
  }
  final decode = _elemDecode(prop.type, raw, registry);
  return '$raw == null ? null : $decode';
}

/// Decodes a required extension-type getter whose JS type is already known.
String _hookTypedExtDecode(TsIrType type, String expr, _TypeRegistry registry) {
  switch (type.kind) {
    case 'string':
    case 'number':
    case 'boolean':
      return '$expr.toDart';
    case 'literal':
      final literals = _uniqueLiterals(type.literals ?? const []);
      if (_isBoolUnion(literals)) return '$expr.toDart';
      if (literals.length >= 2) {
        return '${_enumNameFor(type, registry)}.fromValue($expr.toDart)';
      }
      return '$expr.toDart';
    case 'record':
    case 'urlSearchParams':
      return '_decodePairs($expr)';
    case 'object':
      if ((type.members ?? const <TsIrProp>[]).isEmpty) return expr;
      return '${_objectNameFor(type, registry)}.fromJs($expr)';
    case 'array':
      final element = type.element ?? const TsIrType(kind: 'any');
      return '_decodeList($expr, (e) => ${_elemDecode(element, 'e', registry)})';
    case 'tuple':
      final elements = type.elements ?? const <TsIrType>[];
      final parts = <String>[
        for (var i = 0; i < elements.length; i++)
          _elemDecode(elements[i], '$expr[$i]', registry),
      ];
      return '(${parts.join(', ')})';
    case 'function':
      return _fnClosure(type, expr, registry);
    default:
      return expr;
  }
}

String _hookExtType(TsIrType type) {
  switch (type.kind) {
    case 'string':
      return 'JSString';
    case 'number':
      return 'JSNumber';
    case 'boolean':
      return 'JSBoolean';
    case 'any':
    case 'unknown':
    case 'hostValue':
    case 'void':
    case 'null':
    case 'reactNode':
    case 'union':
    case 'indexedAccess':
      return 'JSAny?';
    case 'literal':
      final literals = _uniqueLiterals(type.literals ?? const []);
      if (_isBoolUnion(literals)) return 'JSBoolean';
      if (literals.length >= 2) return 'JSString';
      return _literalDartType(literals) == 'String' ? 'JSString' : 'JSNumber';
    case 'record':
    case 'urlSearchParams':
      return 'JSArray';
    case 'object':
      return 'JSObject';
    case 'array':
    case 'tuple':
      return 'JSArray';
    case 'function':
      return 'JSFunction';
    default:
      return 'JSObject';
  }
}

/// Adds `?` to [type] unless it is already nullable; required props keep
/// their declared type (`Object? state` stays `Object? state`, `String key`
/// stays `String key`).
String _nullableType(String type, bool required) =>
    required || type.endsWith('?') ? type : '$type?';
