part of '../ts_bindings.dart';

/// Generates a JS shim module that registers the bound components for the
/// foreign-component bridge (`__reactDartRegisterComponent`), so
/// `foreignComponent('prefix.Name', ...)` resolves at runtime.
///
/// When [declarations] contains `use*` hooks, the module also registers the
/// hook bridge under [namespace] (`globalThis.__reactDartBindings[namespace]`)
/// that the generated hooks file calls during render. When [namespace] is
/// empty, hooks register at `globalThis.__reactDartHooks` (legacy).
///
/// The module imports only the declarations it references as named imports
/// (aliased to `__reactDart<Name>`), so bundlers can tree-shake the rest of
/// [specifier] instead of pulling the whole namespace in.
///
/// The module imports [specifier] from the managed npm environment and must be
/// wired into `react.yaml`:
///
/// ```yaml
/// foreign:
///   modules:
///     - path/to/generated_shim.mjs
/// ```
String generateShim({
  required String specifier,
  required String prefix,
  required List<TsIrDeclaration> declarations,
  String? commandLine,
  String namespace = '',
}) {
  final components = declarations.where((d) => d.kind == 'component');
  final hooks = declarations.where((d) => d.kind == 'hook').toList();
  final functions = declarations.where((d) => d.kind == 'function').toList();
  final usedNames = <String>{};
  for (final declaration in components) {
    usedNames.add(declaration.name);
  }
  for (final hook in hooks) {
    usedNames.add(hook.name);
  }
  for (final fn in functions) {
    usedNames.add(fn.name);
  }
  final localFor = <String, String>{
    for (final name in usedNames) name: _shimLocalName(name),
  };
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE — DO NOT EDIT.')
    ..writeln('// Generated by: ${commandLine ?? 'react ts bind --shim'}')
    ..writeln('//')
    ..writeln('// Registers the bound `$specifier` components under the')
    ..writeln('// `$prefix.*` names used by the generated Dart helpers.')
    ..writeln('// Wire this module into react.yaml under `foreign.modules`.')
    ..writeln();
  if (usedNames.isNotEmpty) {
    buffer.writeln(
      "import { ${usedNames.map((n) => '$n as ${localFor[n]}').join(', ')} } "
      "from '$specifier';",
    );
  }
  buffer.writeln();
  buffer.writeln('const components = {');
  for (final declaration in components) {
    buffer.writeln(
      "  '$prefix.${declaration.name}': ${localFor[declaration.name]},",
    );
  }
  buffer
    ..writeln('};')
    ..writeln()
    ..writeln('for (const [name, component] of Object.entries(components)) {')
    ..writeln('  globalThis.__reactDartRegisterComponent?.(name, component);')
    ..writeln('}');

  final allBindings = [...hooks, ...functions];
  if (allBindings.isNotEmpty) {
    buffer
      ..writeln()
      ..writeln(
        '// Hook bridge: the generated Dart hooks (`--hooks` output) call',
      )
      ..writeln('// these members during render. Results are decoded into')
      ..writeln('// primitives or `[[key, value], ...]` pairs (via `toPairs`)')
      ..writeln('// because dart2js cannot cast a raw callAsFunction result.')
      ..writeln('const toPairs = (v) => {')
      ..writeln('  if (v == null) return v;')
      ..writeln('  if (Array.isArray(v)) return v.map(toPairs);')
      ..writeln("  if (typeof v === 'object') {")
      ..writeln(
        "    if (typeof v.entries === 'function') return [...v.entries()];",
      )
      ..writeln(
        "    return Object.entries(v).map(([k, val]) => [k, toPairs(val)]);",
      )
      ..writeln('  }')
      ..writeln('  return v;')
      ..writeln('};')
      ..writeln()
      ..writeln('const hooks = {');
    for (final hook in hooks) {
      buffer.writeln('  ${hook.name}: ${_jsHookBody(hook, localFor)},');
    }
    for (final fn in functions) {
      buffer.writeln('  ${fn.name}: (a0) => ${localFor[fn.name]}(a0),');
    }
    buffer
      ..writeln('};')
      ..writeln();
    if (namespace.isNotEmpty) {
      buffer
        ..writeln('globalThis.__reactDartBindings ??= Object.create(null);')
        ..writeln('globalThis.__reactDartBindings.$namespace = hooks;')
        ..writeln();
    } else {
      buffer.writeln('globalThis.__reactDartHooks = hooks;');
    }
  }
  return buffer.toString();
}

/// Collision-free local alias for a shim import: `Greeting` →
/// `__reactDartGreeting`, `useThing` → `__reactDartUseThing`.
String _shimLocalName(String exportName) =>
    '__reactDart${exportName[0].toUpperCase()}${exportName.substring(1)}';

/// The JS body for one hook bridge member.
String _jsHookBody(TsIrDeclaration hook, Map<String, String> localFor) {
  final args = [for (var i = 0; i < hook.params.length; i++) 'a$i'];
  // Dart `null` means "absent" for optional positionals (dart:js interop
  // cannot express `undefined`), but JS default parameters only fire for
  // a real `undefined` — some libraries even throw on explicit `null`
  // (`Object.keys(init)`). Drop trailing nulls so the call matches the
  // TypeScript signature.
  final callExpr = hook.params.any((p) => !p.required)
      ? '(() => { const as = [${args.join(', ')}]; '
            'while (as.length && as[as.length - 1] == null) as.pop(); '
            'return ${localFor[hook.name]}(...as); })()'
      : '${localFor[hook.name]}(${args.join(', ')})';
  final returns = hook.returns;
  const simple = {
    'string',
    'number',
    'boolean',
    'any',
    'unknown',
    'void',
    'null',
    'reactNode',
    'hostValue',
    'literal',
    'function',
  };
  if (returns == null || simple.contains(returns.kind)) {
    return '(${args.join(', ')}) => $callExpr';
  }
  final decode = _jsDecodeExpr(returns, 'v');
  return '(${args.join(', ')}) => { const v = $callExpr; return $decode; }';
}

/// JS decode expression for a shim bridge return value.
String _jsDecodeExpr(TsIrType type, String expr) {
  switch (type.kind) {
    case 'record':
      return 'toPairs($expr ?? {})';
    case 'urlSearchParams':
      return 'toPairs($expr)';
    case 'object':
      // Known-shape objects are passed as raw JS objects; the
      // generated extension type provides typed property access.
      return expr;
    case 'array':
      final element = type.element ?? const TsIrType(kind: 'any');
      if (element.kind == 'object' &&
          (element.members ?? const <TsIrProp>[]).isNotEmpty) {
        return '($expr ?? []).map((x) => x)';
      }
      return '($expr ?? []).map((x) => toPairs(x))';
    case 'tuple':
      final elements = type.elements ?? const <TsIrType>[];
      final parts = <String>[];
      for (var i = 0; i < elements.length; i++) {
        parts.add(_jsDecodeExpr(elements[i], '$expr[$i]'));
      }
      return '[${parts.join(', ')}]';
    default:
      return expr;
  }
}
