// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom useLocation useNavigate useParams useSearchParams
// Source: react-router-dom
// (extracted from /run/media/kingwill101/disk2/code/code/dart_packages/react_workspace/.dart_tool/react/js/node_modules/react-router-dom/./dist/index.d.ts)
// ignore_for_file: type=lint

import 'package:react/react.dart';





