// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom/server StaticRouter
// Source: react-router-dom/server
// (extracted from /run/media/kingwill101/disk2/code/code/dart_packages/react_workspace/.dart_tool/react/js/node_modules/react-router-dom/server.d.ts)
// ignore_for_file: type=lint

import 'package:react/react.dart';

/// Typed helper for the `reactRouter.StaticRouter` foreign component.
///
/// Props from `StaticRouter`:
///
/// children?: React.ReactNode; basename?: string; location: any
/// future?: { v7_prependBasename?: boolean; v7_relativeSplatPath?: boolean; v7_fetcherPersist?: boolean; v7_skipActionErrorRevalidation?: boolean; v7_partialHydration?: boolean; v7_normalizeFormMethod?: boolean }
ReactNode reactRouterStaticRouter({
  String? key,
  List<ReactNode> children = const [],
    String? basename,
    required Object location,
    ServerFutureConfig? future,
}) => foreignComponent(
  'reactRouter.StaticRouter',
  key: key,
  props: {
    if (basename != null) 'basename': basename,
    'location': location,
    if (future != null) 'future': future.toJson(),
  },
  children: children,
);

/// Typed props for `FutureConfig`.
///
/// v7_prependBasename?: boolean; v7_relativeSplatPath?: boolean
/// v7_fetcherPersist?: boolean; v7_skipActionErrorRevalidation?: boolean
/// v7_partialHydration?: boolean; v7_normalizeFormMethod?: boolean
class ServerFutureConfig {
  const ServerFutureConfig({
    bool? this.v7_prependBasename,
    bool? this.v7_relativeSplatPath,
    bool? this.v7_fetcherPersist,
    bool? this.v7_skipActionErrorRevalidation,
    bool? this.v7_partialHydration,
    bool? this.v7_normalizeFormMethod,
  });

  /// TS: boolean
  final bool? v7_prependBasename;

  /// TS: boolean
  final bool? v7_relativeSplatPath;

  /// TS: boolean
  final bool? v7_fetcherPersist;

  /// TS: boolean
  final bool? v7_skipActionErrorRevalidation;

  /// TS: boolean
  final bool? v7_partialHydration;

  /// TS: boolean
  final bool? v7_normalizeFormMethod;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (v7_prependBasename != null) 'v7_prependBasename': v7_prependBasename,
    if (v7_relativeSplatPath != null) 'v7_relativeSplatPath': v7_relativeSplatPath,
    if (v7_fetcherPersist != null) 'v7_fetcherPersist': v7_fetcherPersist,
    if (v7_skipActionErrorRevalidation != null) 'v7_skipActionErrorRevalidation': v7_skipActionErrorRevalidation,
    if (v7_partialHydration != null) 'v7_partialHydration': v7_partialHydration,
    if (v7_normalizeFormMethod != null) 'v7_normalizeFormMethod': v7_normalizeFormMethod,
  };
}

