// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom/server  --shim
//
// Registers the bound `react-router-dom/server` components under the
// `reactRouter.*` names used by the generated Dart helpers.
// Wire this module into react.yaml under `foreign.modules`.

import { StaticRouter as __reactDartStaticRouter, StaticRouterProvider as __reactDartStaticRouterProvider } from 'react-router-dom/server';

const components = {
  'reactRouter.StaticRouter': __reactDartStaticRouter,
  'reactRouter.StaticRouterProvider': __reactDartStaticRouterProvider,
};

for (const [name, component] of Object.entries(components)) {
  globalThis.__reactDartRegisterComponent?.(name, component);
}
