// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom BrowserRouter MemoryRouter Routes Route Link NavLink Outlet Navigate useHref useInRouterContext useLocation useNavigate useNavigationType useOutlet useParams useSearchParams useMatches useNavigation useRevalidator useResolvedPath useRouteError useRouteLoaderData useRoutes useBlocker useFetcher useFetchers useFormAction useLinkClickHandler useLoaderData useSubmit useActionData useOutletContext useAsyncValue useAsyncError --hooks
// Source: react-router-dom
// (extracted from /run/media/kingwill101/disk2/code/code/dart_packages/react_workspace/node_modules/react-router-dom/./dist/index.d.ts)
// ignore_for_file: type=lint

import 'dart:js_interop';
import 'react_router_bindings.g.dart';

// Hook bindings for `react-router-dom`. Each hook is only available
// in JavaScript targets (browser client and Node SSR worker);
// it calls into the shim bridge (`__reactDartBindings.reactRouter`)
// and runs inside React's render call stack.

// Shared decode helpers for hook return values.
// Primitives and literals are decoded directly by the external's
// return type; objects with known shape use generated extension
// types (see below) for direct property access instead of
// converting to/from [[key, value]] pairs. Record / URLSearchParams
// types are still encoded as `[[k, v], ...]` pairs by the shim
// (via `toPairs`) until the shim learns to pass raw JS objects.
Map<String, String> _decodePairs(JSArray raw) {
  final result = <String, String>{};
  for (var i = 0; i < raw.length; i++) {
    final entry = (raw[i] as JSArray);
    result[(entry[0] as JSString).toDart] = (entry[1] as JSString).toDart;
  }
  return result;
}

List<T> _decodeList<T>(JSArray raw, T Function(JSAny? item) decode) {
  final result = <T>[];
  for (var i = 0; i < raw.length; i++) {
    result.add(decode(raw[i]));
  }
  return result;
}
/// useHref(to: any, arg?: { relative?: "route" | "path" }) => string
///
/// See https://reactrouter.com/hooks/href.
@JS('globalThis.__reactDartBindings.reactRouter.useHref')
external JSString _useHrefRaw(JSAny? a0, JSAny? a1);

String useHref(Object? to, {RelativeRoutingType? relative}) {
  final options = <String, Object?>{if (relative != null) 'relative': relative.value};
  return _useHrefRaw(to.jsify(), options.jsify()).toDart;
}

/// useInRouterContext() => boolean
///
/// See https://reactrouter.com/hooks/inroutercontext.
@JS('globalThis.__reactDartBindings.reactRouter.useInRouterContext')
external JSBoolean _useInRouterContextRaw();

bool useInRouterContext() {
  return _useInRouterContextRaw().toDart;
}

/// useLocation() => { pathname: string; search: string; hash: string; state: any; key: string }
///
/// See https://reactrouter.com/hooks/location.
@JS('globalThis.__reactDartBindings.reactRouter.useLocation')
external JSObject _useLocationRaw();

Location useLocation() {
  return Location.fromJs(_useLocationRaw());
}

/// useNavigate() => (to: any, options: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
///
/// See https://reactrouter.com/hooks/navigate.
@JS('globalThis.__reactDartBindings.reactRouter.useNavigate')
external JSFunction _useNavigateRaw();

void Function(Object? to, {bool? replace, Object? state, bool? preventScrollReset, RelativeRoutingType? relative, bool? unstable_flushSync, bool? unstable_viewTransition}) useNavigate() {
  final fn = _useNavigateRaw();
  return (Object? to, {bool? replace, Object? state, bool? preventScrollReset, RelativeRoutingType? relative, bool? unstable_flushSync, bool? unstable_viewTransition}) { fn.callAsFunction(null, to.jsify(), <String, Object?>{if (replace != null) 'replace': replace, if (state != null) 'state': state, if (preventScrollReset != null) 'preventScrollReset': preventScrollReset, if (relative != null) 'relative': relative.value, if (unstable_flushSync != null) 'unstable_flushSync': unstable_flushSync, if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition}.jsify()); };
}

/// useNavigationType() => "POP" | "PUSH" | "REPLACE"
///
/// See https://reactrouter.com/hooks/navigationtype.
@JS('globalThis.__reactDartBindings.reactRouter.useNavigationType')
external JSString _useNavigationTypeRaw();

NavigationType useNavigationType() {
  return NavigationType.fromValue(_useNavigationTypeRaw().toDart);
}

/// useOutlet(context?: unknown) => any
///
/// See https://reactrouter.com/hooks/outlet.
@JS('globalThis.__reactDartBindings.reactRouter.useOutlet')
external JSAny? _useOutletRaw(JSAny? a0);

Object? useOutlet([Object? context]) {
  return _useOutletRaw(context.jsify());
}

/// useParams() => unknown
///
/// See https://reactrouter.com/hooks/params.
@JS('globalThis.__reactDartBindings.reactRouter.useParams')
external JSArray _useParamsRaw();

Map<String, String> useParams() {
  return _decodePairs(_useParamsRaw());
}

/// useSearchParams(defaultInit?: any) => unknown
///
/// See https://reactrouter.com/hooks/searchparams.
@JS('globalThis.__reactDartBindings.reactRouter.useSearchParams')
external JSArray _useSearchParamsRaw(JSAny? a0);

(Map<String, String>, void Function(Object? nextInit, {bool? replace, Object? state, bool? preventScrollReset, RelativeRoutingType? relative, bool? unstable_flushSync, bool? unstable_viewTransition})) useSearchParams([Object? defaultInit]) {
  final raw = _useSearchParamsRaw(defaultInit.jsify());
  return (_decodePairs(raw[0] as JSArray), (Object? nextInit, {bool? replace, Object? state, bool? preventScrollReset, RelativeRoutingType? relative, bool? unstable_flushSync, bool? unstable_viewTransition}) { (raw[1] as JSFunction).callAsFunction(null, nextInit.jsify(), <String, Object?>{if (replace != null) 'replace': replace, if (state != null) 'state': state, if (preventScrollReset != null) 'preventScrollReset': preventScrollReset, if (relative != null) 'relative': relative.value, if (unstable_flushSync != null) 'unstable_flushSync': unstable_flushSync, if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition}.jsify()); });
}

/// useMatches() => { id: string; pathname: string; params: unknown; data: any; handle: any }[]
///
/// See https://reactrouter.com/hooks/matches.
@JS('globalThis.__reactDartBindings.reactRouter.useMatches')
external JSArray _useMatchesRaw();

List<UIMatch> useMatches() {
  return _decodeList(_useMatchesRaw(), (e) => UIMatch.fromJs(e as JSObject));
}

/// useNavigation() => { state: "idle" | "loading" | "submitting"; location: { pathname: string; search: string; hash: string; state: any; key: string }; formMethod: Record<string, unknown>; formAction: string; formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; formData: any; json: Record<string, unknown>; text: string }
///
/// See https://reactrouter.com/hooks/navigation.
@JS('globalThis.__reactDartBindings.reactRouter.useNavigation')
external JSObject _useNavigationRaw();

NavigationReturn useNavigation() {
  return NavigationReturn.fromJs(_useNavigationRaw());
}

/// useRevalidator() => { revalidate: () => void; state: "idle" | "loading" }
///
/// See https://reactrouter.com/hooks/revalidator.
@JS('globalThis.__reactDartBindings.reactRouter.useRevalidator')
external JSObject _useRevalidatorRaw();

RevalidatorReturn useRevalidator() {
  return RevalidatorReturn.fromJs(_useRevalidatorRaw());
}

/// useResolvedPath(to: any, arg?: { relative?: "route" | "path" }) => { pathname: string; search: string; hash: string }
///
/// See https://reactrouter.com/hooks/resolvedpath.
@JS('globalThis.__reactDartBindings.reactRouter.useResolvedPath')
external JSObject _useResolvedPathRaw(JSAny? a0, JSAny? a1);

Path useResolvedPath(Object? to, {RelativeRoutingType? relative}) {
  final options = <String, Object?>{if (relative != null) 'relative': relative.value};
  return Path.fromJs(_useResolvedPathRaw(to.jsify(), options.jsify()));
}

/// useRouteError() => unknown
///
/// See https://reactrouter.com/hooks/routeerror.
@JS('globalThis.__reactDartBindings.reactRouter.useRouteError')
external JSAny? _useRouteErrorRaw();

Object? useRouteError() {
  return _useRouteErrorRaw();
}

/// useRouteLoaderData(routeId: string) => unknown
///
/// See https://reactrouter.com/hooks/routeloaderdata.
@JS('globalThis.__reactDartBindings.reactRouter.useRouteLoaderData')
external JSAny? _useRouteLoaderDataRaw(JSAny? a0);

Object? useRouteLoaderData(String routeId) {
  return _useRouteLoaderDataRaw(routeId.jsify());
}

/// useRoutes(routes: { caseSensitive?: any; path?: any; id?: any; loader?: any; action?: any; hasErrorBoundary?: any; shouldRevalidate?: any; handle?: any; index: true | false; children?: any[]; element?: React.ReactNode; hydrateFallbackElement?: React.ReactNode; errorElement?: React.ReactNode; Component?: any; HydrateFallback?: any; ErrorBoundary?: any; lazy?: () => any }[], locationArg?: any) => any
///
/// See https://reactrouter.com/hooks/routes.
@JS('globalThis.__reactDartBindings.reactRouter.useRoutes')
external JSAny? _useRoutesRaw(JSAny? a0, JSAny? a1);

Object? useRoutes(List<Object?> routes, [Object? locationArg]) {
  return _useRoutesRaw(routes.jsify(), locationArg.jsify());
}

/// useBlocker(shouldBlock: any) => { state: "unblocked" | "blocked" | "proceeding"; reset: () => void; proceed: () => void; location: { pathname: string; search: string; hash: string; state: any; key: string } }
///
/// See https://reactrouter.com/hooks/blocker.
@JS('globalThis.__reactDartBindings.reactRouter.useBlocker')
external JSObject _useBlockerRaw(JSAny? a0);

BlockerReturn useBlocker(Object? shouldBlock) {
  return BlockerReturn.fromJs(_useBlockerRaw(shouldBlock.jsify()));
}

/// useFetcher(arg?: { key?: string }) => { state: "idle" | "loading" | "submitting"; formMethod: Record<string, unknown>; formAction: string; formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; text: string; formData: any; json: Record<string, unknown>; data: any; Form: { method?: Record<string, unknown>; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"; action?: string; relative?: "route" | "path"; preventScrollReset?: boolean; onSubmit?: any }; submit: (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean }) => void; load: (href: string, opts: { unstable_flushSync?: boolean }) => void }
///
/// See https://reactrouter.com/hooks/fetcher.
@JS('globalThis.__reactDartBindings.reactRouter.useFetcher')
external JSObject _useFetcherRaw(JSAny? a0);

FetcherReturn useFetcher({String? elementKey}) {
  final options = <String, Object?>{if (elementKey != null) 'key': elementKey};
  return FetcherReturn.fromJs(_useFetcherRaw(options.jsify()));
}

/// useFetchers() => { state: "idle" | "loading" | "submitting"; formMethod: Record<string, unknown>; formAction: string; formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; text: string; formData: any; json: Record<string, unknown>; data: any; key: string }[]
///
/// See https://reactrouter.com/hooks/fetchers.
@JS('globalThis.__reactDartBindings.reactRouter.useFetchers')
external JSArray _useFetchersRaw();

List<FetchersReturnElement> useFetchers() {
  return _decodeList(_useFetchersRaw(), (e) => FetchersReturnElement.fromJs(e as JSObject));
}

/// useFormAction(action?: string, arg?: { relative?: "route" | "path" }) => string
///
/// See https://reactrouter.com/hooks/formaction.
@JS('globalThis.__reactDartBindings.reactRouter.useFormAction')
external JSString _useFormActionRaw(JSAny? a0, JSAny? a1);

String useFormAction(String? action, {RelativeRoutingType? relative}) {
  final options = <String, Object?>{if (relative != null) 'relative': relative.value};
  return _useFormActionRaw(action.jsify(), options.jsify()).toDart;
}

/// useLinkClickHandler(to: any, arg?: { target?: any; replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_viewTransition?: boolean }) => (event: host value) => void
///
/// See https://reactrouter.com/hooks/linkclickhandler.
@JS('globalThis.__reactDartBindings.reactRouter.useLinkClickHandler')
external JSFunction _useLinkClickHandlerRaw(JSAny? a0, JSAny? a1);

void Function(Object? event) useLinkClickHandler(Object? to, {Object? target, bool? replace, Object? state, bool? preventScrollReset, RelativeRoutingType? relative, bool? unstable_viewTransition}) {
  final options = <String, Object?>{if (target != null) 'target': target, if (replace != null) 'replace': replace, if (state != null) 'state': state, if (preventScrollReset != null) 'preventScrollReset': preventScrollReset, if (relative != null) 'relative': relative.value, if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition};
  final fn = _useLinkClickHandlerRaw(to.jsify(), options.jsify());
  return (Object? event) { fn.callAsFunction(null, event.jsify()); };
}

/// useLoaderData() => unknown
///
/// See https://reactrouter.com/hooks/loaderdata.
@JS('globalThis.__reactDartBindings.reactRouter.useLoaderData')
external JSAny? _useLoaderDataRaw();

Object? useLoaderData() {
  return _useLoaderDataRaw();
}

/// useSubmit() => (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean; replace?: boolean; state?: any; fetcherKey?: string; navigate?: boolean; unstable_viewTransition?: boolean }) => void
///
/// See https://reactrouter.com/hooks/submit.
@JS('globalThis.__reactDartBindings.reactRouter.useSubmit')
external JSFunction _useSubmitRaw();

void Function(Object? target, {Object? method, String? action, FormEncType? encType, RelativeRoutingType? relative, bool? preventScrollReset, bool? unstable_flushSync, bool? replace, Object? state, String? fetcherKey, bool? navigate, bool? unstable_viewTransition}) useSubmit() {
  final fn = _useSubmitRaw();
  return (Object? target, {Object? method, String? action, FormEncType? encType, RelativeRoutingType? relative, bool? preventScrollReset, bool? unstable_flushSync, bool? replace, Object? state, String? fetcherKey, bool? navigate, bool? unstable_viewTransition}) { fn.callAsFunction(null, target.jsify(), <String, Object?>{if (method != null) 'method': method, if (action != null) 'action': action, if (encType != null) 'encType': encType.value, if (relative != null) 'relative': relative.value, if (preventScrollReset != null) 'preventScrollReset': preventScrollReset, if (unstable_flushSync != null) 'unstable_flushSync': unstable_flushSync, if (replace != null) 'replace': replace, if (state != null) 'state': state, if (fetcherKey != null) 'fetcherKey': fetcherKey, if (navigate != null) 'navigate': navigate, if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition}.jsify()); };
}

/// useActionData() => unknown
///
/// See https://reactrouter.com/hooks/actiondata.
@JS('globalThis.__reactDartBindings.reactRouter.useActionData')
external JSAny? _useActionDataRaw();

Object? useActionData() {
  return _useActionDataRaw();
}

/// useOutletContext() => any
///
/// See https://reactrouter.com/hooks/outletcontext.
@JS('globalThis.__reactDartBindings.reactRouter.useOutletContext')
external JSAny? _useOutletContextRaw();

Object? useOutletContext() {
  return _useOutletContextRaw();
}

/// useAsyncValue() => unknown
///
/// See https://reactrouter.com/hooks/asyncvalue.
@JS('globalThis.__reactDartBindings.reactRouter.useAsyncValue')
external JSAny? _useAsyncValueRaw();

Object? useAsyncValue() {
  return _useAsyncValueRaw();
}

/// useAsyncError() => unknown
///
/// See https://reactrouter.com/hooks/asyncerror.
@JS('globalThis.__reactDartBindings.reactRouter.useAsyncError')
external JSAny? _useAsyncErrorRaw();

Object? useAsyncError() {
  return _useAsyncErrorRaw();
}

/// Typed JS interop extension for `BlockerReturn` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _BlockerReturnJs(JSObject _) implements JSObject {
  external JSString get state;
  external JSFunction get reset;
  external JSFunction get proceed;
  external JSObject get location;
}

/// Value class for `BlockerReturn` (decoded from the hook shim).
///
/// state: "unblocked" | "blocked" | "proceeding"; reset: () => void
/// proceed: () => void
/// location: { pathname: string; search: string; hash: string; state: any; key: string }
final class BlockerReturn {
  BlockerReturn._(this._value, {
    required this.state,
    required this.reset,
    required this.proceed,
    required this.location,
  });

  final _BlockerReturnJs _value;

  /// TS: "unblocked" | "blocked" | "proceeding"
  final BlockerReturnState state;
  /// TS: () => void
  final void Function() reset;
  /// TS: () => void
  final void Function() proceed;
  /// TS: { pathname: string; search: string; hash: string; state: any; key: string }
  final Location location;

  /// Decodes the shim's raw JS object.
  factory BlockerReturn.fromJs(JSObject js) {
    final v = _BlockerReturnJs(js);
    return BlockerReturn._(v,
      state: BlockerReturnState.fromValue((v.state as JSString).toDart),
      reset: () { v.reset.callAsFunction(null); },
      proceed: () { v.proceed.callAsFunction(null); },
      location: Location.fromJs(v.location as JSObject),
    );
  }

}

/// Typed JS interop extension for `FetcherReturn` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _FetcherReturnJs(JSObject _) implements JSObject {
  external JSString get state;
  external JSObject get formMethod;
  external JSString get formAction;
  external JSString get formEncType;
  external JSString get text;
  external JSAny? get formData;
  external JSObject get json;
  external JSAny? get data;
  external JSObject get Form;
  external JSFunction get submit;
  external JSFunction get load;
}

/// Value class for `FetcherReturn` (decoded from the hook shim).
///
/// state: "idle" | "loading" | "submitting"
/// formMethod: Record<string, unknown>; formAction: string
/// formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
/// text: string; formData: any; json: Record<string, unknown>; data: any
/// Form: { method?: Record<string, unknown>; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"; action?: string; relative?: "route" | "path"; preventScrollReset?: boolean; onSubmit?: any }
/// submit: (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean }) => void
/// load: (href: string, opts: { unstable_flushSync?: boolean }) => void
final class FetcherReturn {
  FetcherReturn._(this._value, {
    required this.state,
    required this.formMethod,
    required this.formAction,
    required this.formEncType,
    required this.text,
    required this.formData,
    required this.json,
    required this.data,
    required this.Form,
    required this.submit,
    required this.load,
  });

  final _FetcherReturnJs _value;

  /// TS: "idle" | "loading" | "submitting"
  final NavigationReturnState state;
  /// TS: Record<string, unknown>
  final Object? formMethod;
  /// TS: string
  final String formAction;
  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
  final FormEncType formEncType;
  /// TS: string
  final String text;
  /// TS: any
  final Object? formData;
  /// TS: Record<string, unknown>
  final Object? json;
  /// TS: any
  final Object? data;
  /// TS: { method?: Record<string, unknown>; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"; action?: string; relative?: "route" | "path"; preventScrollReset?: boolean; onSubmit?: any }
  final FetcherReturnForm Form;
  /// TS: (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean }) => void
  final void Function(Object? target, {Object? method, String? action, FormEncType? encType, RelativeRoutingType? relative, bool? preventScrollReset, bool? unstable_flushSync}) submit;
  /// TS: (href: string, opts: { unstable_flushSync?: boolean }) => void
  final void Function(String href, {bool? unstable_flushSync}) load;

  /// Decodes the shim's raw JS object.
  factory FetcherReturn.fromJs(JSObject js) {
    final v = _FetcherReturnJs(js);
    return FetcherReturn._(v,
      state: NavigationReturnState.fromValue((v.state as JSString).toDart),
      formMethod: v.formMethod,
      formAction: (v.formAction as JSString).toDart,
      formEncType: FormEncType.fromValue((v.formEncType as JSString).toDart),
      text: (v.text as JSString).toDart,
      formData: v.formData,
      json: v.json,
      data: v.data,
      Form: FetcherReturnForm.fromJs(v.Form as JSObject),
      submit: (Object? target, {Object? method, String? action, FormEncType? encType, RelativeRoutingType? relative, bool? preventScrollReset, bool? unstable_flushSync}) { v.submit.callAsFunction(null, target.jsify(), <String, Object?>{if (method != null) 'method': method, if (action != null) 'action': action, if (encType != null) 'encType': encType.value, if (relative != null) 'relative': relative.value, if (preventScrollReset != null) 'preventScrollReset': preventScrollReset, if (unstable_flushSync != null) 'unstable_flushSync': unstable_flushSync}.jsify()); },
      load: (String href, {bool? unstable_flushSync}) { v.load.callAsFunction(null, href.toJS, <String, Object?>{if (unstable_flushSync != null) 'unstable_flushSync': unstable_flushSync}.jsify()); },
    );
  }

}

/// Typed JS interop extension for `FetcherReturnForm` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _FetcherReturnFormJs(JSObject _) implements JSObject {
  external JSObject? get method;
  external JSString? get encType;
  external JSString? get action;
  external JSString? get relative;
  external JSBoolean? get preventScrollReset;
  external JSAny? get onSubmit;
}

/// Value class for `FetcherReturnForm` (decoded from the hook shim).
///
/// method?: Record<string, unknown>
/// encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
/// action?: string; relative?: "route" | "path"; preventScrollReset?: boolean
/// onSubmit?: any
final class FetcherReturnForm {
  FetcherReturnForm._(this._value, {
    required this.method,
    required this.encType,
    required this.action,
    required this.relative,
    required this.preventScrollReset,
    required this.onSubmit,
  });

  final _FetcherReturnFormJs _value;

  /// TS: Record<string, unknown>
  final Object? method;
  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
  final FetcherReturnFormEncType? encType;
  /// TS: string
  final String? action;
  /// TS: "route" | "path"
  final RelativeRoutingType? relative;
  /// TS: boolean
  final bool? preventScrollReset;
  /// TS: any
  final Object? onSubmit;

  /// Decodes the shim's raw JS object.
  factory FetcherReturnForm.fromJs(JSObject js) {
    final v = _FetcherReturnFormJs(js);
    return FetcherReturnForm._(v,
      method: v.method == null ? null : v.method,
      encType: v.encType == null ? null : FetcherReturnFormEncType.fromValue((v.encType as JSString).toDart),
      action: v.action == null ? null : (v.action as JSString).toDart,
      relative: v.relative == null ? null : RelativeRoutingType.fromValue((v.relative as JSString).toDart),
      preventScrollReset: v.preventScrollReset == null ? null : (v.preventScrollReset as JSBoolean).toDart,
      onSubmit: v.onSubmit == null ? null : v.onSubmit,
    );
  }

}

/// Typed JS interop extension for `FetchersReturnElement` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _FetchersReturnElementJs(JSObject _) implements JSObject {
  external JSString get state;
  external JSObject get formMethod;
  external JSString get formAction;
  external JSString get formEncType;
  external JSString get text;
  external JSAny? get formData;
  external JSObject get json;
  external JSAny? get data;
  @JS('key') external JSString get elementKey;
}

/// Value class for `FetchersReturnElement` (decoded from the hook shim).
///
/// state: "idle" | "loading" | "submitting"
/// formMethod: Record<string, unknown>; formAction: string
/// formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
/// text: string; formData: any; json: Record<string, unknown>; data: any
/// key: string
final class FetchersReturnElement {
  FetchersReturnElement._(this._value, {
    required this.state,
    required this.formMethod,
    required this.formAction,
    required this.formEncType,
    required this.text,
    required this.formData,
    required this.json,
    required this.data,
    required this.elementKey,
  });

  final _FetchersReturnElementJs _value;

  /// TS: "idle" | "loading" | "submitting"
  final NavigationReturnState state;
  /// TS: Record<string, unknown>
  final Object? formMethod;
  /// TS: string
  final String formAction;
  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
  final FormEncType formEncType;
  /// TS: string
  final String text;
  /// TS: any
  final Object? formData;
  /// TS: Record<string, unknown>
  final Object? json;
  /// TS: any
  final Object? data;
  /// TS: string
  final String elementKey;

  /// Decodes the shim's raw JS object.
  factory FetchersReturnElement.fromJs(JSObject js) {
    final v = _FetchersReturnElementJs(js);
    return FetchersReturnElement._(v,
      state: NavigationReturnState.fromValue((v.state as JSString).toDart),
      formMethod: v.formMethod,
      formAction: (v.formAction as JSString).toDart,
      formEncType: FormEncType.fromValue((v.formEncType as JSString).toDart),
      text: (v.text as JSString).toDart,
      formData: v.formData,
      json: v.json,
      data: v.data,
      elementKey: (v.elementKey as JSString).toDart,
    );
  }

}

/// Typed JS interop extension for `Location` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _LocationJs(JSObject _) implements JSObject {
  external JSString get pathname;
  external JSString get search;
  external JSString get hash;
  external JSAny? get state;
  @JS('key') external JSString get elementKey;
}

/// Value class for `Location` (decoded from the hook shim).
///
/// pathname: string; search: string; hash: string; state: any; key: string
final class Location {
  Location._(this._value, {
    required this.pathname,
    required this.search,
    required this.hash,
    required this.state,
    required this.elementKey,
  });

  final _LocationJs _value;

  /// TS: string
  final String pathname;
  /// TS: string
  final String search;
  /// TS: string
  final String hash;
  /// TS: any
  final Object? state;
  /// TS: string
  final String elementKey;

  /// Decodes the shim's raw JS object.
  factory Location.fromJs(JSObject js) {
    final v = _LocationJs(js);
    return Location._(v,
      pathname: (v.pathname as JSString).toDart,
      search: (v.search as JSString).toDart,
      hash: (v.hash as JSString).toDart,
      state: v.state,
      elementKey: (v.elementKey as JSString).toDart,
    );
  }

  /// The full path including the query string.
  String get fullPath => '$pathname$search$hash';

  @override
  String toString() => fullPath;
}

/// Typed JS interop extension for `NavigationReturn` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _NavigationReturnJs(JSObject _) implements JSObject {
  external JSString get state;
  external JSObject get location;
  external JSObject get formMethod;
  external JSString get formAction;
  external JSString get formEncType;
  external JSAny? get formData;
  external JSObject get json;
  external JSString get text;
}

/// Value class for `NavigationReturn` (decoded from the hook shim).
///
/// state: "idle" | "loading" | "submitting"
/// location: { pathname: string; search: string; hash: string; state: any; key: string }
/// formMethod: Record<string, unknown>; formAction: string
/// formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
/// formData: any; json: Record<string, unknown>; text: string
final class NavigationReturn {
  NavigationReturn._(this._value, {
    required this.state,
    required this.location,
    required this.formMethod,
    required this.formAction,
    required this.formEncType,
    required this.formData,
    required this.json,
    required this.text,
  });

  final _NavigationReturnJs _value;

  /// TS: "idle" | "loading" | "submitting"
  final NavigationReturnState state;
  /// TS: { pathname: string; search: string; hash: string; state: any; key: string }
  final Location location;
  /// TS: Record<string, unknown>
  final Object? formMethod;
  /// TS: string
  final String formAction;
  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
  final FormEncType formEncType;
  /// TS: any
  final Object? formData;
  /// TS: Record<string, unknown>
  final Object? json;
  /// TS: string
  final String text;

  /// Decodes the shim's raw JS object.
  factory NavigationReturn.fromJs(JSObject js) {
    final v = _NavigationReturnJs(js);
    return NavigationReturn._(v,
      state: NavigationReturnState.fromValue((v.state as JSString).toDart),
      location: Location.fromJs(v.location as JSObject),
      formMethod: v.formMethod,
      formAction: (v.formAction as JSString).toDart,
      formEncType: FormEncType.fromValue((v.formEncType as JSString).toDart),
      formData: v.formData,
      json: v.json,
      text: (v.text as JSString).toDart,
    );
  }

}

/// Typed JS interop extension for `Path` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _PathJs(JSObject _) implements JSObject {
  external JSString get pathname;
  external JSString get search;
  external JSString get hash;
}

/// Value class for `Path` (decoded from the hook shim).
///
/// pathname: string; search: string; hash: string
final class Path {
  Path._(this._value, {
    required this.pathname,
    required this.search,
    required this.hash,
  });

  final _PathJs _value;

  /// TS: string
  final String pathname;
  /// TS: string
  final String search;
  /// TS: string
  final String hash;

  /// Decodes the shim's raw JS object.
  factory Path.fromJs(JSObject js) {
    final v = _PathJs(js);
    return Path._(v,
      pathname: (v.pathname as JSString).toDart,
      search: (v.search as JSString).toDart,
      hash: (v.hash as JSString).toDart,
    );
  }

}

/// Typed JS interop extension for `RevalidatorReturn` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _RevalidatorReturnJs(JSObject _) implements JSObject {
  external JSFunction get revalidate;
  external JSString get state;
}

/// Value class for `RevalidatorReturn` (decoded from the hook shim).
///
/// revalidate: () => void; state: "idle" | "loading"
final class RevalidatorReturn {
  RevalidatorReturn._(this._value, {
    required this.revalidate,
    required this.state,
  });

  final _RevalidatorReturnJs _value;

  /// TS: () => void
  final void Function() revalidate;
  /// TS: "idle" | "loading"
  final RevalidationState state;

  /// Decodes the shim's raw JS object.
  factory RevalidatorReturn.fromJs(JSObject js) {
    final v = _RevalidatorReturnJs(js);
    return RevalidatorReturn._(v,
      revalidate: () { v.revalidate.callAsFunction(null); },
      state: RevalidationState.fromValue((v.state as JSString).toDart),
    );
  }

}

/// Typed JS interop extension for `UIMatch` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _UIMatchJs(JSObject _) implements JSObject {
  external JSString get id;
  external JSString get pathname;
  external JSArray get params;
  external JSAny? get data;
  external JSAny? get handle;
}

/// Value class for `UIMatch` (decoded from the hook shim).
///
/// id: string; pathname: string; params: unknown; data: any; handle: any
final class UIMatch {
  UIMatch._(this._value, {
    required this.id,
    required this.pathname,
    required this.params,
    required this.data,
    required this.handle,
  });

  final _UIMatchJs _value;

  /// TS: string
  final String id;
  /// TS: string
  final String pathname;
  /// TS: unknown
  final Map<String, String> params;
  /// TS: any
  final Object? data;
  /// TS: any
  final Object? handle;

  /// Decodes the shim's raw JS object.
  factory UIMatch.fromJs(JSObject js) {
    final v = _UIMatchJs(js);
    return UIMatch._(v,
      id: (v.id as JSString).toDart,
      pathname: (v.pathname as JSString).toDart,
      params: _decodePairs(v.params as JSArray),
      data: v.data,
      handle: v.handle,
    );
  }

}

/// Literal union: "unblocked" | "blocked" | "proceeding"
enum BlockerReturnState {
  unblocked('unblocked'),
  blocked('blocked'),
  proceeding('proceeding');
  const BlockerReturnState(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static BlockerReturnState fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown BlockerReturnState'),
  );
}

/// Literal union: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
enum FetcherReturnFormEncType {
  applicationXWwwFormUrlencoded('application/x-www-form-urlencoded'),
  multipartFormData('multipart/form-data'),
  textPlain('text/plain');
  const FetcherReturnFormEncType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static FetcherReturnFormEncType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown FetcherReturnFormEncType'),
  );
}

/// Literal union: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
enum FormEncType {
  applicationXWwwFormUrlencoded('application/x-www-form-urlencoded'),
  multipartFormData('multipart/form-data'),
  applicationJson('application/json'),
  textPlain('text/plain');
  const FormEncType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static FormEncType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown FormEncType'),
  );
}

/// Literal union: "idle" | "loading" | "submitting"
enum NavigationReturnState {
  idle('idle'),
  loading('loading'),
  submitting('submitting');
  const NavigationReturnState(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static NavigationReturnState fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown NavigationReturnState'),
  );
}

/// Literal union: "POP" | "PUSH" | "REPLACE"
enum NavigationType {
  pop('POP'),
  push('PUSH'),
  replace('REPLACE');
  const NavigationType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static NavigationType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown NavigationType'),
  );
}

/// Literal union: "idle" | "loading"
enum RevalidationState {
  idle('idle'),
  loading('loading');
  const RevalidationState(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static RevalidationState fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown RevalidationState'),
  );
}

