// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom  --hooks
// Source: react-router-dom
// (extracted from /run/media/kingwill101/disk2/code/code/dart_packages/react_workspace/.dart_tool/react/js/node_modules/react-router-dom/./dist/index.d.ts)
// ignore_for_file: type=lint

import 'dart:js_interop';
import 'package:react/react.dart';
import 'react_router_bindings.g.dart';

// Hook bindings for `react-router-dom`. Each hook is only available
// in JavaScript targets (browser client and Node SSR worker);
// it calls into the shim bridge (`__reactDartBindings.reactRouter`)
// and runs inside React's render call stack.

// Shared decode helpers for hook return values.
// Primitives and literals are decoded directly by the external's
// return type; objects with known shape use generated extension
// types (see below) for direct property access instead of
// converting to/from [[key, value]] pairs. Record / URLSearchParams
// types are still encoded as `[[k, v], ...]` pairs by the shim
// (via `toPairs`) until the shim learns to pass raw JS objects.
Map<String, String> _decodePairs(JSArray raw) {
  final result = <String, String>{};
  for (var i = 0; i < raw.length; i++) {
    final entry = (raw[i] as JSArray);
    result[(entry[0] as JSString).toDart] = (entry[1] as JSString).toDart;
  }
  return result;
}

List<T> _decodeList<T>(JSArray raw, T Function(JSAny? item) decode) {
  final result = <T>[];
  for (var i = 0; i < raw.length; i++) {
    result.add(decode(raw[i]));
  }
  return result;
}

/// useLinkClickHandler(to: any, arg?: { target?: any; replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_viewTransition?: boolean }) => (event: host value) => void
///
/// See https://reactrouter.com/hooks/linkclickhandler.
@JS('globalThis.__reactDartBindings.reactRouter.useLinkClickHandler')
external JSFunction _useLinkClickHandlerRaw(JSAny? a0, JSAny? a1);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useLinkClickHandler',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
void Function(Object? event) useLinkClickHandler(
  Object? to, {
  Object? target,
  bool? replace,
  Object? state,
  bool? preventScrollReset,
  RelativeRoutingType? relative,
  bool? unstable_viewTransition,
}) {
  final options = <String, Object?>{
    if (target != null) 'target': target,
    if (replace != null) 'replace': replace,
    if (state != null) 'state': state,
    if (preventScrollReset != null) 'preventScrollReset': preventScrollReset,
    if (relative != null) 'relative': relative.value,
    if (unstable_viewTransition != null)
      'unstable_viewTransition': unstable_viewTransition,
  };
  final fn = _useLinkClickHandlerRaw(to.jsify(), options.jsify());
  return (Object? event) {
    fn.callAsFunction(null, event.jsify());
  };
}

/// useSearchParams(defaultInit?: any) => unknown
///
/// See https://reactrouter.com/hooks/searchparams.
@JS('globalThis.__reactDartBindings.reactRouter.useSearchParams')
external JSArray _useSearchParamsRaw(JSAny? a0);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useSearchParams',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
(
  Map<String, String>,
  void Function(
    Object? nextInit, {
    bool? replace,
    Object? state,
    bool? preventScrollReset,
    RelativeRoutingType? relative,
    bool? unstable_flushSync,
    bool? unstable_viewTransition,
  }),
)
useSearchParams([Object? defaultInit]) {
  final raw = _useSearchParamsRaw(defaultInit.jsify());
  return (
    _decodePairs(raw[0] as JSArray),
    (
      Object? nextInit, {
      bool? replace,
      Object? state,
      bool? preventScrollReset,
      RelativeRoutingType? relative,
      bool? unstable_flushSync,
      bool? unstable_viewTransition,
    }) {
      (raw[1] as JSFunction).callAsFunction(
        null,
        nextInit.jsify(),
        <String, Object?>{
          if (replace != null) 'replace': replace,
          if (state != null) 'state': state,
          if (preventScrollReset != null)
            'preventScrollReset': preventScrollReset,
          if (relative != null) 'relative': relative.value,
          if (unstable_flushSync != null)
            'unstable_flushSync': unstable_flushSync,
          if (unstable_viewTransition != null)
            'unstable_viewTransition': unstable_viewTransition,
        }.jsify(),
      );
    },
  );
}

/// useSubmit() => (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean; replace?: boolean; state?: any; fetcherKey?: string; navigate?: boolean; unstable_viewTransition?: boolean }) => void
///
/// See https://reactrouter.com/hooks/submit.
@JS('globalThis.__reactDartBindings.reactRouter.useSubmit')
external JSFunction _useSubmitRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useSubmit',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
void Function(
  Object? target, {
  Object? method,
  String? action,
  FormEncType? encType,
  RelativeRoutingType? relative,
  bool? preventScrollReset,
  bool? unstable_flushSync,
  bool? replace,
  Object? state,
  String? fetcherKey,
  bool? navigate,
  bool? unstable_viewTransition,
})
useSubmit() {
  final fn = _useSubmitRaw();
  return (
    Object? target, {
    Object? method,
    String? action,
    FormEncType? encType,
    RelativeRoutingType? relative,
    bool? preventScrollReset,
    bool? unstable_flushSync,
    bool? replace,
    Object? state,
    String? fetcherKey,
    bool? navigate,
    bool? unstable_viewTransition,
  }) {
    fn.callAsFunction(
      null,
      target.jsify(),
      <String, Object?>{
        if (method != null) 'method': method,
        if (action != null) 'action': action,
        if (encType != null) 'encType': encType.value,
        if (relative != null) 'relative': relative.value,
        if (preventScrollReset != null)
          'preventScrollReset': preventScrollReset,
        if (unstable_flushSync != null)
          'unstable_flushSync': unstable_flushSync,
        if (replace != null) 'replace': replace,
        if (state != null) 'state': state,
        if (fetcherKey != null) 'fetcherKey': fetcherKey,
        if (navigate != null) 'navigate': navigate,
        if (unstable_viewTransition != null)
          'unstable_viewTransition': unstable_viewTransition,
      }.jsify(),
    );
  };
}

/// useFormAction(action?: string, arg?: { relative?: "route" | "path" }) => string
///
/// See https://reactrouter.com/hooks/formaction.
@JS('globalThis.__reactDartBindings.reactRouter.useFormAction')
external JSString _useFormActionRaw(JSAny? a0, JSAny? a1);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useFormAction',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
String useFormAction(String? action, {RelativeRoutingType? relative}) {
  final options = <String, Object?>{
    if (relative != null) 'relative': relative.value,
  };
  return _useFormActionRaw(action.jsify(), options.jsify()).toDart;
}

/// useFetcher(arg?: { key?: string }) => { state: "idle" | "loading" | "submitting"; formMethod: Record<string, unknown>; formAction: string; formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; text: string; formData: any; json: Record<string, unknown>; data: any; Form: { method?: Record<string, unknown>; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"; action?: string; relative?: "route" | "path"; preventScrollReset?: boolean; onSubmit?: any }; submit: (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean }) => void; load: (href: string, opts: { unstable_flushSync?: boolean }) => void }
///
/// See https://reactrouter.com/hooks/fetcher.
@JS('globalThis.__reactDartBindings.reactRouter.useFetcher')
external JSObject _useFetcherRaw(JSAny? a0);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useFetcher',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
FetcherReturn useFetcher({String? elementKey}) {
  final options = <String, Object?>{if (elementKey != null) 'key': elementKey};
  return FetcherReturn.fromJs(_useFetcherRaw(options.jsify()));
}

/// useFetchers() => { state: "idle" | "loading" | "submitting"; formMethod: Record<string, unknown>; formAction: string; formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; text: string; formData: any; json: Record<string, unknown>; data: any; key: string }[]
///
/// See https://reactrouter.com/hooks/fetchers.
@JS('globalThis.__reactDartBindings.reactRouter.useFetchers')
external JSArray _useFetchersRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useFetchers',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
List<FetchersReturnElement> useFetchers() {
  return _decodeList(
    _useFetchersRaw(),
    (e) => FetchersReturnElement.fromJs(e as JSObject),
  );
}

/// useBeforeUnload(callback: (event: host value) => any, options?: { capture?: boolean }) => void
///
/// See https://reactrouter.com/hooks/beforeunload.
@JS('globalThis.__reactDartBindings.reactRouter.useBeforeUnload')
external JSAny? _useBeforeUnloadRaw(JSAny? a0, JSAny? a1);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useBeforeUnload',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Object? useBeforeUnload(Object? callback, {bool? capture}) {
  final options = <String, Object?>{if (capture != null) 'capture': capture};
  return _useBeforeUnloadRaw(callback.jsify(), options.jsify());
}

/// useHref(to: any, arg?: { relative?: "route" | "path" }) => string
///
/// See https://reactrouter.com/hooks/href.
@JS('globalThis.__reactDartBindings.reactRouter.useHref')
external JSString _useHrefRaw(JSAny? a0, JSAny? a1);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useHref',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
String useHref(Object? to, {RelativeRoutingType? relative}) {
  final options = <String, Object?>{
    if (relative != null) 'relative': relative.value,
  };
  return _useHrefRaw(to.jsify(), options.jsify()).toDart;
}

/// useInRouterContext() => boolean
///
/// See https://reactrouter.com/hooks/inroutercontext.
@JS('globalThis.__reactDartBindings.reactRouter.useInRouterContext')
external JSBoolean _useInRouterContextRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useInRouterContext',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
bool useInRouterContext() {
  return _useInRouterContextRaw().toDart;
}

/// useLocation() => { pathname: string; search: string; hash: string; state: any; key: string }
///
/// See https://reactrouter.com/hooks/location.
@JS('globalThis.__reactDartBindings.reactRouter.useLocation')
external JSObject _useLocationRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useLocation',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Location useLocation() {
  return Location.fromJs(_useLocationRaw());
}

/// useNavigationType() => "POP" | "PUSH" | "REPLACE"
///
/// See https://reactrouter.com/hooks/navigationtype.
@JS('globalThis.__reactDartBindings.reactRouter.useNavigationType')
external JSString _useNavigationTypeRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useNavigationType',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
NavigationType useNavigationType() {
  return NavigationType.fromValue(_useNavigationTypeRaw().toDart);
}

/// useMatch(pattern: { path: { pathname: string; search: string; hash: string }; caseSensitive?: boolean; end?: boolean; pathname: string; search: string; hash: string }) => { params: unknown; pathname: string; pathnameBase: string; pattern: { path: { pathname: string; search: string; hash: string }; caseSensitive?: boolean; end?: boolean } }
///
/// See https://reactrouter.com/hooks/match.
@JS('globalThis.__reactDartBindings.reactRouter.useMatch')
external JSObject _useMatchRaw(JSAny? a0);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useMatch',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
PathMatch useMatch({
  Path? path,
  bool? caseSensitive,
  bool? end,
  String? pathname,
  String? search,
  String? hash,
}) {
  final options = <String, Object?>{
    if (path != null) 'path': path,
    if (caseSensitive != null) 'caseSensitive': caseSensitive,
    if (end != null) 'end': end,
    if (pathname != null) 'pathname': pathname,
    if (search != null) 'search': search,
    if (hash != null) 'hash': hash,
  };
  return PathMatch.fromJs(_useMatchRaw(options.jsify()));
}

/// useNavigate() => (to: any, options: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
///
/// See https://reactrouter.com/hooks/navigate.
@JS('globalThis.__reactDartBindings.reactRouter.useNavigate')
external JSFunction _useNavigateRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useNavigate',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
void Function(
  Object? to, {
  bool? replace,
  Object? state,
  bool? preventScrollReset,
  RelativeRoutingType? relative,
  bool? unstable_flushSync,
  bool? unstable_viewTransition,
})
useNavigate() {
  final fn = _useNavigateRaw();
  return (
    Object? to, {
    bool? replace,
    Object? state,
    bool? preventScrollReset,
    RelativeRoutingType? relative,
    bool? unstable_flushSync,
    bool? unstable_viewTransition,
  }) {
    fn.callAsFunction(
      null,
      to.jsify(),
      <String, Object?>{
        if (replace != null) 'replace': replace,
        if (state != null) 'state': state,
        if (preventScrollReset != null)
          'preventScrollReset': preventScrollReset,
        if (relative != null) 'relative': relative.value,
        if (unstable_flushSync != null)
          'unstable_flushSync': unstable_flushSync,
        if (unstable_viewTransition != null)
          'unstable_viewTransition': unstable_viewTransition,
      }.jsify(),
    );
  };
}

/// useOutletContext() => any
///
/// See https://reactrouter.com/hooks/outletcontext.
@JS('globalThis.__reactDartBindings.reactRouter.useOutletContext')
external JSAny? _useOutletContextRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useOutletContext',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Object? useOutletContext() {
  return _useOutletContextRaw();
}

/// useOutlet(context?: unknown) => any
///
/// See https://reactrouter.com/hooks/outlet.
@JS('globalThis.__reactDartBindings.reactRouter.useOutlet')
external JSAny? _useOutletRaw(JSAny? a0);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useOutlet',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Object? useOutlet([Object? context]) {
  return _useOutletRaw(context.jsify());
}

/// useParams() => unknown
///
/// See https://reactrouter.com/hooks/params.
@JS('globalThis.__reactDartBindings.reactRouter.useParams')
external JSArray _useParamsRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useParams',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Map<String, String> useParams() {
  return _decodePairs(_useParamsRaw());
}

/// useResolvedPath(to: any, arg?: { relative?: "route" | "path" }) => { pathname: string; search: string; hash: string }
///
/// See https://reactrouter.com/hooks/resolvedpath.
@JS('globalThis.__reactDartBindings.reactRouter.useResolvedPath')
external JSObject _useResolvedPathRaw(JSAny? a0, JSAny? a1);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useResolvedPath',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Path useResolvedPath(Object? to, {RelativeRoutingType? relative}) {
  final options = <String, Object?>{
    if (relative != null) 'relative': relative.value,
  };
  return Path.fromJs(_useResolvedPathRaw(to.jsify(), options.jsify()));
}

/// useRoutes(routes: { caseSensitive?: any; path?: any; id?: any; loader?: any; action?: any; hasErrorBoundary?: any; shouldRevalidate?: any; handle?: any; index: true | false; children?: any[]; element?: React.ReactNode; hydrateFallbackElement?: React.ReactNode; errorElement?: React.ReactNode; Component?: any; HydrateFallback?: any; ErrorBoundary?: any; lazy?: () => any }[], locationArg?: any) => any
///
/// See https://reactrouter.com/hooks/routes.
@JS('globalThis.__reactDartBindings.reactRouter.useRoutes')
external JSAny? _useRoutesRaw(JSAny? a0, JSAny? a1);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useRoutes',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Object? useRoutes(List<Object?> routes, [Object? locationArg]) {
  return _useRoutesRaw(routes.jsify(), locationArg.jsify());
}

/// useNavigation() => { state: "idle" | "loading" | "submitting"; location: { pathname: string; search: string; hash: string; state: any; key: string }; formMethod: Record<string, unknown>; formAction: string; formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; formData: any; json: Record<string, unknown>; text: string }
///
/// See https://reactrouter.com/hooks/navigation.
@JS('globalThis.__reactDartBindings.reactRouter.useNavigation')
external JSObject _useNavigationRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useNavigation',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
NavigationReturn useNavigation() {
  return NavigationReturn.fromJs(_useNavigationRaw());
}

/// useRevalidator() => { revalidate: () => void; state: "idle" | "loading" }
///
/// See https://reactrouter.com/hooks/revalidator.
@JS('globalThis.__reactDartBindings.reactRouter.useRevalidator')
external JSObject _useRevalidatorRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useRevalidator',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
RevalidatorReturn useRevalidator() {
  return RevalidatorReturn.fromJs(_useRevalidatorRaw());
}

/// useMatches() => { id: string; pathname: string; params: unknown; data: any; handle: any }[]
///
/// See https://reactrouter.com/hooks/matches.
@JS('globalThis.__reactDartBindings.reactRouter.useMatches')
external JSArray _useMatchesRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useMatches',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
List<UIMatch> useMatches() {
  return _decodeList(_useMatchesRaw(), (e) => UIMatch.fromJs(e as JSObject));
}

/// useLoaderData() => unknown
///
/// See https://reactrouter.com/hooks/loaderdata.
@JS('globalThis.__reactDartBindings.reactRouter.useLoaderData')
external JSAny? _useLoaderDataRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useLoaderData',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Object? useLoaderData() {
  return _useLoaderDataRaw();
}

/// useRouteLoaderData(routeId: string) => unknown
///
/// See https://reactrouter.com/hooks/routeloaderdata.
@JS('globalThis.__reactDartBindings.reactRouter.useRouteLoaderData')
external JSAny? _useRouteLoaderDataRaw(JSAny? a0);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useRouteLoaderData',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Object? useRouteLoaderData(String routeId) {
  return _useRouteLoaderDataRaw(routeId.jsify());
}

/// useActionData() => unknown
///
/// See https://reactrouter.com/hooks/actiondata.
@JS('globalThis.__reactDartBindings.reactRouter.useActionData')
external JSAny? _useActionDataRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useActionData',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Object? useActionData() {
  return _useActionDataRaw();
}

/// useRouteError() => unknown
///
/// See https://reactrouter.com/hooks/routeerror.
@JS('globalThis.__reactDartBindings.reactRouter.useRouteError')
external JSAny? _useRouteErrorRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useRouteError',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Object? useRouteError() {
  return _useRouteErrorRaw();
}

/// useAsyncValue() => unknown
///
/// See https://reactrouter.com/hooks/asyncvalue.
@JS('globalThis.__reactDartBindings.reactRouter.useAsyncValue')
external JSAny? _useAsyncValueRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useAsyncValue',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Object? useAsyncValue() {
  return _useAsyncValueRaw();
}

/// useAsyncError() => unknown
///
/// See https://reactrouter.com/hooks/asyncerror.
@JS('globalThis.__reactDartBindings.reactRouter.useAsyncError')
external JSAny? _useAsyncErrorRaw();

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useAsyncError',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
Object? useAsyncError() {
  return _useAsyncErrorRaw();
}

/// useBlocker(shouldBlock: any) => { state: "unblocked" | "blocked" | "proceeding"; reset: () => void; proceed: () => void; location: { pathname: string; search: string; hash: string; state: any; key: string } }
///
/// See https://reactrouter.com/hooks/blocker.
@JS('globalThis.__reactDartBindings.reactRouter.useBlocker')
external JSObject _useBlockerRaw(JSAny? a0);

@ReactHook()
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.hook,
  runtimeKey: 'reactRouter.useBlocker',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
BlockerReturn useBlocker(Object? shouldBlock) {
  return BlockerReturn.fromJs(_useBlockerRaw(shouldBlock.jsify()));
}

/// Typed JS interop extension for `BlockerReturn` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _BlockerReturnJs(JSObject _) implements JSObject {
  external JSString get state;
  external JSFunction get reset;
  external JSFunction get proceed;
  external JSObject get location;
}

/// Value class for `BlockerReturn` (decoded from the hook shim).
///
/// state: "unblocked" | "blocked" | "proceeding"; reset: () => void
/// proceed: () => void
/// location: { pathname: string; search: string; hash: string; state: any; key: string }
final class BlockerReturn {
  BlockerReturn._({
    required this.state,
    required this.reset,
    required this.proceed,
    required this.location,
  });

  /// TS: "unblocked" | "blocked" | "proceeding"
  final BlockerReturnState state;

  /// TS: () => void
  final void Function() reset;

  /// TS: () => void
  final void Function() proceed;

  /// TS: { pathname: string; search: string; hash: string; state: any; key: string }
  final Location location;

  /// Decodes the shim's raw JS object.
  factory BlockerReturn.fromJs(JSObject js) {
    final v = _BlockerReturnJs(js);
    return BlockerReturn._(
      state: BlockerReturnState.fromValue(v.state.toDart),
      reset: () {
        v.reset.callAsFunction(null);
      },
      proceed: () {
        v.proceed.callAsFunction(null);
      },
      location: Location.fromJs(v.location),
    );
  }
}

/// Typed JS interop extension for `FetcherReturn` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _FetcherReturnJs(JSObject _) implements JSObject {
  external JSString get state;
  external JSObject get formMethod;
  external JSString get formAction;
  external JSString get formEncType;
  external JSString get text;
  external JSAny? get formData;
  external JSObject get json;
  external JSAny? get data;
  external JSObject get Form;
  external JSFunction get submit;
  external JSFunction get load;
}

/// Value class for `FetcherReturn` (decoded from the hook shim).
///
/// state: "idle" | "loading" | "submitting"
/// formMethod: Record<string, unknown>; formAction: string
/// formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
/// text: string; formData: any; json: Record<string, unknown>; data: any
/// Form: { method?: Record<string, unknown>; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"; action?: string; relative?: "route" | "path"; preventScrollReset?: boolean; onSubmit?: any }
/// submit: (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean }) => void
/// load: (href: string, opts: { unstable_flushSync?: boolean }) => void
final class FetcherReturn {
  FetcherReturn._({
    required this.state,
    required this.formMethod,
    required this.formAction,
    required this.formEncType,
    required this.text,
    required this.formData,
    required this.json,
    required this.data,
    required this.Form,
    required this.submit,
    required this.load,
  });

  /// TS: "idle" | "loading" | "submitting"
  final FetcherReturnState state;

  /// TS: Record<string, unknown>
  final Object? formMethod;

  /// TS: string
  final String formAction;

  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
  final FormEncType formEncType;

  /// TS: string
  final String text;

  /// TS: any
  final Object? formData;

  /// TS: Record<string, unknown>
  final Object? json;

  /// TS: any
  final Object? data;

  /// TS: { method?: Record<string, unknown>; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"; action?: string; relative?: "route" | "path"; preventScrollReset?: boolean; onSubmit?: any }
  final FetcherReturnForm Form;

  /// TS: (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean }) => void
  final void Function(
    Object? target, {
    Object? method,
    String? action,
    FormEncType? encType,
    RelativeRoutingType? relative,
    bool? preventScrollReset,
    bool? unstable_flushSync,
  })
  submit;

  /// TS: (href: string, opts: { unstable_flushSync?: boolean }) => void
  final void Function(String href, {bool? unstable_flushSync}) load;

  /// Decodes the shim's raw JS object.
  factory FetcherReturn.fromJs(JSObject js) {
    final v = _FetcherReturnJs(js);
    return FetcherReturn._(
      state: FetcherReturnState.fromValue(v.state.toDart),
      formMethod: v.formMethod,
      formAction: v.formAction.toDart,
      formEncType: FormEncType.fromValue(v.formEncType.toDart),
      text: v.text.toDart,
      formData: v.formData,
      json: v.json,
      data: v.data,
      Form: FetcherReturnForm.fromJs(v.Form),
      submit:
          (
            Object? target, {
            Object? method,
            String? action,
            FormEncType? encType,
            RelativeRoutingType? relative,
            bool? preventScrollReset,
            bool? unstable_flushSync,
          }) {
            v.submit.callAsFunction(
              null,
              target.jsify(),
              <String, Object?>{
                if (method != null) 'method': method,
                if (action != null) 'action': action,
                if (encType != null) 'encType': encType.value,
                if (relative != null) 'relative': relative.value,
                if (preventScrollReset != null)
                  'preventScrollReset': preventScrollReset,
                if (unstable_flushSync != null)
                  'unstable_flushSync': unstable_flushSync,
              }.jsify(),
            );
          },
      load: (String href, {bool? unstable_flushSync}) {
        v.load.callAsFunction(
          null,
          href.toJS,
          <String, Object?>{
            if (unstable_flushSync != null)
              'unstable_flushSync': unstable_flushSync,
          }.jsify(),
        );
      },
    );
  }
}

/// Typed JS interop extension for `FetcherReturnForm` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _FetcherReturnFormJs(JSObject _) implements JSObject {
  external JSObject? get method;
  external JSString? get encType;
  external JSString? get action;
  external JSString? get relative;
  external JSBoolean? get preventScrollReset;
  external JSAny? get onSubmit;
}

/// Value class for `FetcherReturnForm` (decoded from the hook shim).
///
/// method?: Record<string, unknown>
/// encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
/// action?: string; relative?: "route" | "path"; preventScrollReset?: boolean
/// onSubmit?: any
final class FetcherReturnForm {
  FetcherReturnForm._({
    required this.method,
    required this.encType,
    required this.action,
    required this.relative,
    required this.preventScrollReset,
    required this.onSubmit,
  });

  /// TS: Record<string, unknown>
  final Object? method;

  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
  final FetcherReturnFormEncType? encType;

  /// TS: string
  final String? action;

  /// TS: "route" | "path"
  final RelativeRoutingType? relative;

  /// TS: boolean
  final bool? preventScrollReset;

  /// TS: any
  final Object? onSubmit;

  /// Decodes the shim's raw JS object.
  factory FetcherReturnForm.fromJs(JSObject js) {
    final v = _FetcherReturnFormJs(js);
    return FetcherReturnForm._(
      method: v.method == null ? null : v.method,
      encType: v.encType == null
          ? null
          : FetcherReturnFormEncType.fromValue((v.encType as JSString).toDart),
      action: v.action == null ? null : (v.action as JSString).toDart,
      relative: v.relative == null
          ? null
          : RelativeRoutingType.fromValue((v.relative as JSString).toDart),
      preventScrollReset: v.preventScrollReset == null
          ? null
          : (v.preventScrollReset as JSBoolean).toDart,
      onSubmit: v.onSubmit == null ? null : v.onSubmit,
    );
  }
}

/// Typed JS interop extension for `FetchersReturnElement` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _FetchersReturnElementJs(JSObject _) implements JSObject {
  external JSString get state;
  external JSObject get formMethod;
  external JSString get formAction;
  external JSString get formEncType;
  external JSString get text;
  external JSAny? get formData;
  external JSObject get json;
  external JSAny? get data;
  @JS('key')
  external JSString get elementKey;
}

/// Value class for `FetchersReturnElement` (decoded from the hook shim).
///
/// state: "idle" | "loading" | "submitting"
/// formMethod: Record<string, unknown>; formAction: string
/// formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
/// text: string; formData: any; json: Record<string, unknown>; data: any
/// key: string
final class FetchersReturnElement {
  FetchersReturnElement._({
    required this.state,
    required this.formMethod,
    required this.formAction,
    required this.formEncType,
    required this.text,
    required this.formData,
    required this.json,
    required this.data,
    required this.elementKey,
  });

  /// TS: "idle" | "loading" | "submitting"
  final FetcherReturnState state;

  /// TS: Record<string, unknown>
  final Object? formMethod;

  /// TS: string
  final String formAction;

  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
  final FormEncType formEncType;

  /// TS: string
  final String text;

  /// TS: any
  final Object? formData;

  /// TS: Record<string, unknown>
  final Object? json;

  /// TS: any
  final Object? data;

  /// TS: string
  final String elementKey;

  /// Decodes the shim's raw JS object.
  factory FetchersReturnElement.fromJs(JSObject js) {
    final v = _FetchersReturnElementJs(js);
    return FetchersReturnElement._(
      state: FetcherReturnState.fromValue(v.state.toDart),
      formMethod: v.formMethod,
      formAction: v.formAction.toDart,
      formEncType: FormEncType.fromValue(v.formEncType.toDart),
      text: v.text.toDart,
      formData: v.formData,
      json: v.json,
      data: v.data,
      elementKey: v.elementKey.toDart,
    );
  }
}

/// Typed JS interop extension for `NavigationReturn` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _NavigationReturnJs(JSObject _) implements JSObject {
  external JSString get state;
  external JSObject get location;
  external JSObject get formMethod;
  external JSString get formAction;
  external JSString get formEncType;
  external JSAny? get formData;
  external JSObject get json;
  external JSString get text;
}

/// Value class for `NavigationReturn` (decoded from the hook shim).
///
/// state: "idle" | "loading" | "submitting"
/// location: { pathname: string; search: string; hash: string; state: any; key: string }
/// formMethod: Record<string, unknown>; formAction: string
/// formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
/// formData: any; json: Record<string, unknown>; text: string
final class NavigationReturn {
  NavigationReturn._({
    required this.state,
    required this.location,
    required this.formMethod,
    required this.formAction,
    required this.formEncType,
    required this.formData,
    required this.json,
    required this.text,
  });

  /// TS: "idle" | "loading" | "submitting"
  final FetcherReturnState state;

  /// TS: { pathname: string; search: string; hash: string; state: any; key: string }
  final Location location;

  /// TS: Record<string, unknown>
  final Object? formMethod;

  /// TS: string
  final String formAction;

  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
  final FormEncType formEncType;

  /// TS: any
  final Object? formData;

  /// TS: Record<string, unknown>
  final Object? json;

  /// TS: string
  final String text;

  /// Decodes the shim's raw JS object.
  factory NavigationReturn.fromJs(JSObject js) {
    final v = _NavigationReturnJs(js);
    return NavigationReturn._(
      state: FetcherReturnState.fromValue(v.state.toDart),
      location: Location.fromJs(v.location),
      formMethod: v.formMethod,
      formAction: v.formAction.toDart,
      formEncType: FormEncType.fromValue(v.formEncType.toDart),
      formData: v.formData,
      json: v.json,
      text: v.text.toDart,
    );
  }
}

/// Typed JS interop extension for `RevalidatorReturn` hook return values.
///
/// Direct property access on the raw JS object avoids the
/// generic [[key, value]] pairs conversion used by
/// `_pairsMap` (removed in this generation).
extension type _RevalidatorReturnJs(JSObject _) implements JSObject {
  external JSFunction get revalidate;
  external JSString get state;
}

/// Value class for `RevalidatorReturn` (decoded from the hook shim).
///
/// revalidate: () => void; state: "idle" | "loading"
final class RevalidatorReturn {
  RevalidatorReturn._({required this.revalidate, required this.state});

  /// TS: () => void
  final void Function() revalidate;

  /// TS: "idle" | "loading"
  final RevalidationState state;

  /// Decodes the shim's raw JS object.
  factory RevalidatorReturn.fromJs(JSObject js) {
    final v = _RevalidatorReturnJs(js);
    return RevalidatorReturn._(
      revalidate: () {
        v.revalidate.callAsFunction(null);
      },
      state: RevalidationState.fromValue(v.state.toDart),
    );
  }
}

/// Literal union: "unblocked" | "blocked" | "proceeding"
enum BlockerReturnState {
  unblocked('unblocked'),
  blocked('blocked'),
  proceeding('proceeding');

  const BlockerReturnState(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static BlockerReturnState fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () =>
        throw ArgumentError.value(value, 'value', 'Unknown BlockerReturnState'),
  );
}

/// Literal union: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
enum FetcherReturnFormEncType {
  applicationXWwwFormUrlencoded('application/x-www-form-urlencoded'),
  multipartFormData('multipart/form-data'),
  textPlain('text/plain');

  const FetcherReturnFormEncType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static FetcherReturnFormEncType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(
      value,
      'value',
      'Unknown FetcherReturnFormEncType',
    ),
  );
}

/// Literal union: "idle" | "loading" | "submitting"
enum FetcherReturnState {
  idle('idle'),
  loading('loading'),
  submitting('submitting');

  const FetcherReturnState(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static FetcherReturnState fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () =>
        throw ArgumentError.value(value, 'value', 'Unknown FetcherReturnState'),
  );
}

/// Literal union: "idle" | "loading"
enum RevalidationState {
  idle('idle'),
  loading('loading');

  const RevalidationState(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static RevalidationState fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () =>
        throw ArgumentError.value(value, 'value', 'Unknown RevalidationState'),
  );
}
