// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom
// Source: react-router-dom
// (extracted from /run/media/kingwill101/disk2/code/code/dart_packages/react_workspace/.dart_tool/react/js/node_modules/react-router-dom/./dist/index.d.ts)
// ignore_for_file: type=lint

import 'dart:js_interop';

import 'package:react/react.dart';

/// Typed helper for the `reactRouter.createBrowserRouter` function.
///
/// See https://reactrouter.com/api/createBrowserRouter.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.createBrowserRouter',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.createBrowserRouter')
external JSAny? _createBrowserRouterRaw(JSAny? routes, JSAny? opts);
Object? createBrowserRouter(List<CreateBrowserRouterRoutes> routes, [DOMRouterOpts? opts]) {
  final raw = _createBrowserRouterRaw(routes.jsify(), opts.jsify());
  if (raw == null) return null;
  return raw as Object?;
}

/// Typed helper for the `reactRouter.createHashRouter` function.
///
/// See https://reactrouter.com/api/createHashRouter.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.createHashRouter',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.createHashRouter')
external JSAny? _createHashRouterRaw(JSAny? routes, JSAny? opts);
Object? createHashRouter(List<CreateBrowserRouterRoutes> routes, [DOMRouterOpts? opts]) {
  final raw = _createHashRouterRaw(routes.jsify(), opts.jsify());
  if (raw == null) return null;
  return raw as Object?;
}

/// Typed helper for the `reactRouter.RouterProvider` foreign component.
///
/// Props from `RouterProvider`:
///
/// fallbackElement?: React.ReactNode; router: Record<string, unknown>
/// future?: { value?: any }
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.RouterProvider',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode routerProvider({
  String? key,
    ReactNode? fallbackElement,
    required Object router,
    Pick? future,
}) => foreignComponent(
  'reactRouter.RouterProvider',
  key: key,
  props: {
    if (fallbackElement != null) 'fallbackElement': fallbackElement,
    'router': router,
    if (future != null) 'future': future.toJson(),
  },
);

/// Typed helper for the `reactRouter.BrowserRouter` foreign component.
///
/// Props from `BrowserRouter`:
///
/// basename?: string; children?: React.ReactNode
/// future?: { v7_relativeSplatPath?: boolean; v7_startTransition?: boolean }
/// window?: any
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.BrowserRouter',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode browserRouter({
  String? key,
  List<ReactNode> children = const [],
    String? basename,
    FutureConfig? future,
    Object? window,
}) => foreignComponent(
  'reactRouter.BrowserRouter',
  key: key,
  props: {
    if (basename != null) 'basename': basename,
    if (future != null) 'future': future.toJson(),
    if (window != null) 'window': window,
  },
  children: children,
);

/// Typed helper for the `reactRouter.HashRouter` foreign component.
///
/// Props from `HashRouter`:
///
/// basename?: string; children?: React.ReactNode
/// future?: { v7_relativeSplatPath?: boolean; v7_startTransition?: boolean }
/// window?: any
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.HashRouter',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode hashRouter({
  String? key,
  List<ReactNode> children = const [],
    String? basename,
    FutureConfig? future,
    Object? window,
}) => foreignComponent(
  'reactRouter.HashRouter',
  key: key,
  props: {
    if (basename != null) 'basename': basename,
    if (future != null) 'future': future.toJson(),
    if (window != null) 'window': window,
  },
  children: children,
);

/// Typed helper for the `reactRouter.Link` foreign component.
///
/// Props from `Link`:
///
/// children?: React.ReactNode; className?: string
/// style?: Record<string, unknown>; id?: string; title?: string; lang?: string
/// dir?: string; hidden?: boolean; tabIndex?: number; role?: string
/// target?: string; rel?: string; download?: boolean; onClick?: host value
/// reloadDocument?: boolean; replace?: boolean; state?: any
/// preventScrollReset?: boolean; relative?: "route" | "path"; to: any
/// unstable_viewTransition?: boolean
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.Link',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode link({
  String? key,
  List<ReactNode> children = const [],
    String? className,
    Object? style,
    String? id,
    String? title,
    String? lang,
    String? dir,
    bool? hidden,
    num? tabIndex,
    String? role,
    String? target,
    String? rel,
    bool? download,
    Object? onClick,
    bool? reloadDocument,
    bool? replace,
    Object? state,
    bool? preventScrollReset,
    RelativeRoutingType? relative,
    required Object to,
    bool? unstable_viewTransition,
}) => foreignComponent(
  'reactRouter.Link',
  key: key,
  props: {
    if (className != null) 'className': className,
    if (style != null) 'style': style,
    if (id != null) 'id': id,
    if (title != null) 'title': title,
    if (lang != null) 'lang': lang,
    if (dir != null) 'dir': dir,
    if (hidden != null) 'hidden': hidden,
    if (tabIndex != null) 'tabIndex': tabIndex,
    if (role != null) 'role': role,
    if (target != null) 'target': target,
    if (rel != null) 'rel': rel,
    if (download != null) 'download': download,
    if (onClick != null) 'onClick': onClick,
    if (reloadDocument != null) 'reloadDocument': reloadDocument,
    if (replace != null) 'replace': replace,
    if (state != null) 'state': state,
    if (preventScrollReset != null) 'preventScrollReset': preventScrollReset,
    if (relative != null) 'relative': relative.value,
    'to': to,
    if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition,
  },
  children: children,
);

/// Typed helper for the `reactRouter.NavLink` foreign component.
///
/// Props from `NavLink`:
///
/// children?: React.ReactNode; className?: string
/// style?: Record<string, unknown>; id?: string; title?: string; lang?: string
/// dir?: string; hidden?: boolean; tabIndex?: number; role?: string
/// target?: string; rel?: string; download?: boolean; onClick?: host value
/// reloadDocument?: boolean; replace?: boolean; state?: any
/// preventScrollReset?: boolean; relative?: "route" | "path"; to: any
/// unstable_viewTransition?: boolean; caseSensitive?: boolean; end?: boolean
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.NavLink',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode navLink({
  String? key,
  List<ReactNode> children = const [],
    String? className,
    Object? style,
    String? id,
    String? title,
    String? lang,
    String? dir,
    bool? hidden,
    num? tabIndex,
    String? role,
    String? target,
    String? rel,
    bool? download,
    Object? onClick,
    bool? reloadDocument,
    bool? replace,
    Object? state,
    bool? preventScrollReset,
    RelativeRoutingType? relative,
    required Object to,
    bool? unstable_viewTransition,
    bool? caseSensitive,
    bool? end,
}) => foreignComponent(
  'reactRouter.NavLink',
  key: key,
  props: {
    if (className != null) 'className': className,
    if (style != null) 'style': style,
    if (id != null) 'id': id,
    if (title != null) 'title': title,
    if (lang != null) 'lang': lang,
    if (dir != null) 'dir': dir,
    if (hidden != null) 'hidden': hidden,
    if (tabIndex != null) 'tabIndex': tabIndex,
    if (role != null) 'role': role,
    if (target != null) 'target': target,
    if (rel != null) 'rel': rel,
    if (download != null) 'download': download,
    if (onClick != null) 'onClick': onClick,
    if (reloadDocument != null) 'reloadDocument': reloadDocument,
    if (replace != null) 'replace': replace,
    if (state != null) 'state': state,
    if (preventScrollReset != null) 'preventScrollReset': preventScrollReset,
    if (relative != null) 'relative': relative.value,
    'to': to,
    if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition,
    if (caseSensitive != null) 'caseSensitive': caseSensitive,
    if (end != null) 'end': end,
  },
  children: children,
);

/// Typed helper for the `reactRouter.Form` foreign component.
///
/// Props from `Form`:
///
/// method?: Record<string, unknown>
/// encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
/// action?: string; relative?: "route" | "path"; preventScrollReset?: boolean
/// onSubmit?: any; fetcherKey?: string; navigate?: boolean
/// reloadDocument?: boolean; replace?: boolean; state?: any
/// unstable_viewTransition?: boolean
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.Form',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode form({
  String? key,
    Object? method,
    FormEncType? encType,
    String? action,
    RelativeRoutingType? relative,
    bool? preventScrollReset,
    Object? onSubmit,
    String? fetcherKey,
    bool? navigate,
    bool? reloadDocument,
    bool? replace,
    Object? state,
    bool? unstable_viewTransition,
}) => foreignComponent(
  'reactRouter.Form',
  key: key,
  props: {
    if (method != null) 'method': method,
    if (encType != null) 'encType': encType.value,
    if (action != null) 'action': action,
    if (relative != null) 'relative': relative.value,
    if (preventScrollReset != null) 'preventScrollReset': preventScrollReset,
    if (onSubmit != null) 'onSubmit': onSubmit,
    if (fetcherKey != null) 'fetcherKey': fetcherKey,
    if (navigate != null) 'navigate': navigate,
    if (reloadDocument != null) 'reloadDocument': reloadDocument,
    if (replace != null) 'replace': replace,
    if (state != null) 'state': state,
    if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition,
  },
);

/// Typed helper for the `reactRouter.ScrollRestoration` foreign component.
///
/// Props from `ScrollRestoration`:
///
/// getKey?: (location: { pathname: string; search: string; hash: string; state: any; key: string }, matches: { id: string; pathname: string; params: unknown; data: any; handle: any }[]) => string
/// storageKey?: string
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.ScrollRestoration',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode scrollRestoration({
  String? key,
    /// TS: (location: { pathname: string; search: string; hash: string; state: any; key: string }, matches: { id: string; pathname: string; params: unknown; data: any; handle: any }[]) => string
    ScrollRestorationGetKeyCallback? getKey,
    String? storageKey,
}) => foreignComponent(
  'reactRouter.ScrollRestoration',
  key: key,
  props: {
    if (getKey != null) 'getKey': getKey,
    if (storageKey != null) 'storageKey': storageKey,
  },
);








/// Typed helper for the `reactRouter.createMemoryRouter` function.
///
/// See https://reactrouter.com/api/createMemoryRouter.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.createMemoryRouter',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.createMemoryRouter')
external JSAny? _createMemoryRouterRaw(JSAny? routes, JSAny? opts);
Object? createMemoryRouter(List<CreateBrowserRouterRoutes> routes, [CreateMemoryRouterOpts? opts]) {
  final raw = _createMemoryRouterRaw(routes.jsify(), opts.jsify());
  if (raw == null) return null;
  return raw as Object?;
}

/// Typed helper for the `reactRouter.createSearchParams` function.
///
/// See https://reactrouter.com/api/createSearchParams.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.createSearchParams',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.createSearchParams')
external JSAny? _createSearchParamsRaw(JSAny? init);
Object? createSearchParams([Object? init]) {
  final raw = _createSearchParamsRaw(init.jsify());
  if (raw == null) return null;
  return raw as Object?;
}

/// Typed helper for the `reactRouter.MemoryRouter` foreign component.
///
/// Props from `MemoryRouter`:
///
/// basename?: string; children?: React.ReactNode; initialEntries?: any[]
/// initialIndex?: number
/// future?: { v7_relativeSplatPath?: boolean; v7_startTransition?: boolean }
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.MemoryRouter',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode memoryRouter({
  String? key,
  List<ReactNode> children = const [],
    String? basename,
    List<Object?>? initialEntries,
    num? initialIndex,
    FutureConfig? future,
}) => foreignComponent(
  'reactRouter.MemoryRouter',
  key: key,
  props: {
    if (basename != null) 'basename': basename,
    if (initialEntries != null) 'initialEntries': initialEntries,
    if (initialIndex != null) 'initialIndex': initialIndex,
    if (future != null) 'future': future.toJson(),
  },
  children: children,
);

/// Typed helper for the `reactRouter.Navigate` foreign component.
///
/// Props from `Navigate`:
///
/// to: any; replace?: boolean; state?: any; relative?: "route" | "path"
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.Navigate',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode navigate({
  String? key,
    required Object to,
    bool? replace,
    Object? state,
    RelativeRoutingType? relative,
}) => foreignComponent(
  'reactRouter.Navigate',
  key: key,
  props: {
    'to': to,
    if (replace != null) 'replace': replace,
    if (state != null) 'state': state,
    if (relative != null) 'relative': relative.value,
  },
);

/// Typed helper for the `reactRouter.Outlet` foreign component.
///
/// Props from `Outlet`:
///
/// context?: unknown
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.Outlet',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode outlet({
  String? key,
    Object? context,
}) => foreignComponent(
  'reactRouter.Outlet',
  key: key,
  props: {
    if (context != null) 'context': context,
  },
);

/// Typed helper for the `reactRouter.Route` foreign component.
///
/// Props from `Route`:
///
/// caseSensitive?: any; path?: any; id?: any; lazy?: () => any; loader?: any
/// action?: any; hasErrorBoundary?: any; shouldRevalidate?: any; handle?: any
/// index?: false | false | true; children?: React.ReactNode
/// element?: React.ReactNode; hydrateFallbackElement?: React.ReactNode
/// errorElement?: React.ReactNode; Component?: any; HydrateFallback?: any
/// ErrorBoundary?: any
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.Route',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode route({
  String? key,
  List<ReactNode> children = const [],
    Object? caseSensitive,
    Object? path,
    Object? id,
    /// TS: () => any
    CreateBrowserRouterRoutesLazyCallback? lazy,
    Object? loader,
    Object? action,
    Object? hasErrorBoundary,
    Object? shouldRevalidate,
    Object? handle,
    bool? index,
    ReactNode? element,
    ReactNode? hydrateFallbackElement,
    ReactNode? errorElement,
    Object? Component,
    Object? HydrateFallback,
    Object? ErrorBoundary,
}) => foreignComponent(
  'reactRouter.Route',
  key: key,
  props: {
    if (caseSensitive != null) 'caseSensitive': caseSensitive,
    if (path != null) 'path': path,
    if (id != null) 'id': id,
    if (lazy != null) 'lazy': lazy,
    if (loader != null) 'loader': loader,
    if (action != null) 'action': action,
    if (hasErrorBoundary != null) 'hasErrorBoundary': hasErrorBoundary,
    if (shouldRevalidate != null) 'shouldRevalidate': shouldRevalidate,
    if (handle != null) 'handle': handle,
    if (index != null) 'index': index,
    if (element != null) 'element': element,
    if (hydrateFallbackElement != null) 'hydrateFallbackElement': hydrateFallbackElement,
    if (errorElement != null) 'errorElement': errorElement,
    if (Component != null) 'Component': Component,
    if (HydrateFallback != null) 'HydrateFallback': HydrateFallback,
    if (ErrorBoundary != null) 'ErrorBoundary': ErrorBoundary,
  },
  children: children,
);

/// Typed helper for the `reactRouter.Router` foreign component.
///
/// Props from `Router`:
///
/// basename?: string; children?: React.ReactNode; location: any
/// navigationType?: "POP" | "PUSH" | "REPLACE"
/// navigator: { createHref: (to: any) => string; encodeLocation?: (to: any) => { pathname: string; search: string; hash: string }; go: (delta: number) => void; push: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void; replace: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void }
/// static?: boolean; future?: { value?: any }
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.Router',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode router({
  String? key,
  List<ReactNode> children = const [],
    String? basename,
    required Object location,
    NavigationType? navigationType,
    required Navigator navigator,
    bool? static,
    Pick? future,
}) => foreignComponent(
  'reactRouter.Router',
  key: key,
  props: {
    if (basename != null) 'basename': basename,
    'location': location,
    if (navigationType != null) 'navigationType': navigationType.value,
    'navigator': navigator.toJson(),
    if (static != null) 'static': static,
    if (future != null) 'future': future.toJson(),
  },
  children: children,
);

/// Typed helper for the `reactRouter.Routes` foreign component.
///
/// Props from `Routes`:
///
/// children?: React.ReactNode; location?: any
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.Routes',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode routes({
  String? key,
  List<ReactNode> children = const [],
    Object? location,
}) => foreignComponent(
  'reactRouter.Routes',
  key: key,
  props: {
    if (location != null) 'location': location,
  },
  children: children,
);

/// Typed helper for the `reactRouter.Await` foreign component.
///
/// Props from `Await`:
///
/// children: any; errorElement?: React.ReactNode; resolve: any
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.component,
  runtimeKey: 'reactRouter.Await',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
ReactNode await({
  String? key,
  required List<ReactNode> children,
    ReactNode? errorElement,
    required Object resolve,
}) => foreignComponent(
  'reactRouter.Await',
  key: key,
  props: {
    if (errorElement != null) 'errorElement': errorElement,
    'resolve': resolve,
  },
  children: children,
);

/// Typed helper for the `reactRouter.createRoutesFromChildren` function.
///
/// See https://reactrouter.com/api/createRoutesFromChildren.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.createRoutesFromChildren',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.createRoutesFromChildren')
external JSAny? _createRoutesFromChildrenRaw(JSAny? children, JSAny? parentPath);
List<CreateBrowserRouterRoutes>? createRoutesFromChildren(ReactNode children, [List<num>? parentPath]) {
  final raw = _createRoutesFromChildrenRaw(children.jsify(), parentPath.jsify());
  if (raw == null) return null;
  return raw as List<CreateBrowserRouterRoutes>?;
}

/// Typed helper for the `reactRouter.renderMatches` function.
///
/// See https://reactrouter.com/api/renderMatches.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.renderMatches',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.renderMatches')
external JSAny? _renderMatchesRaw(JSAny? matches);
Object? renderMatches(List<RouteMatch> matches) {
  final raw = _renderMatchesRaw(matches.jsify());
  if (raw == null) return null;
  return raw as Object?;
}






















/// Typed helper for the `reactRouter.matchRoutes` function.
///
/// See https://reactrouter.com/api/matchRoutes.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.matchRoutes',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.matchRoutes')
external JSAny? _matchRoutesRaw(JSAny? routes, JSAny? locationArg, JSAny? basename);
List<AgnosticRouteMatch>? matchRoutes(List<Object?> routes, Object locationArg, [String? basename]) {
  final raw = _matchRoutesRaw(routes.jsify(), locationArg.jsify(), basename.jsify());
  if (raw == null) return null;
  return raw as List<AgnosticRouteMatch>?;
}

/// Typed helper for the `reactRouter.generatePath` function.
///
/// See https://reactrouter.com/api/generatePath.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.generatePath',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.generatePath')
external JSAny? _generatePathRaw(JSAny? originalPath, JSAny? params);
String? generatePath(Path originalPath, [Object? params]) {
  final raw = _generatePathRaw(originalPath.jsify(), params.jsify());
  if (raw == null) return null;
  return raw as String?;
}

/// Typed helper for the `reactRouter.matchPath` function.
///
/// See https://reactrouter.com/api/matchPath.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.matchPath',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.matchPath')
external JSAny? _matchPathRaw(JSAny? pattern, JSAny? pathname);
PathMatch? matchPath(MatchPathPattern pattern, String pathname) {
  final raw = _matchPathRaw(pattern.jsify(), pathname.jsify());
  if (raw == null) return null;
  return raw as PathMatch?;
}

/// Typed helper for the `reactRouter.resolvePath` function.
///
/// See https://reactrouter.com/api/resolvePath.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.resolvePath',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.resolvePath')
external JSAny? _resolvePathRaw(JSAny? to, JSAny? fromPathname);
Path? resolvePath(Object to, [String? fromPathname]) {
  final raw = _resolvePathRaw(to.jsify(), fromPathname.jsify());
  if (raw == null) return null;
  return raw as Path?;
}

/// Typed helper for the `reactRouter.isRouteErrorResponse` function.
///
/// See https://reactrouter.com/api/isRouteErrorResponse.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.isRouteErrorResponse',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.isRouteErrorResponse')
external JSAny? _isRouteErrorResponseRaw(JSAny? error);
Object? isRouteErrorResponse(Object error) {
  final raw = _isRouteErrorResponseRaw(error.jsify());
  if (raw == null) return null;
  return raw as Object?;
}

/// Typed helper for the `reactRouter.createPath` function.
///
/// See https://reactrouter.com/api/createPath.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.createPath',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.createPath')
external JSAny? _createPathRaw(JSAny? arg);
String? createPath(Path arg) {
  final raw = _createPathRaw(arg.jsify());
  if (raw == null) return null;
  return raw as String?;
}

/// Typed helper for the `reactRouter.parsePath` function.
///
/// See https://reactrouter.com/api/parsePath.
@ReactRuntimeSymbol(
  kind: ReactRuntimeSymbolKind.function,
  runtimeKey: 'reactRouter.parsePath',
  targets: {ReactRenderTarget.browser, ReactRenderTarget.server},
)
@JS('globalThis.__reactDartBindings.reactRouter.parsePath')
external JSAny? _parsePathRaw(JSAny? path);
Path? parsePath(String path) {
  final raw = _parsePathRaw(path.jsify());
  if (raw == null) return null;
  return raw as Path?;
}

/// TS: () => any
typedef CreateBrowserRouterRoutesLazyCallback = Object? Function();

/// Wraps a [CreateBrowserRouterRoutesLazyCallback] into a [ReactCallback] for prop encoding.
ReactCallback createBrowserRouterRoutesLazyCallback(CreateBrowserRouterRoutesLazyCallback fn) => ReactCallback(
  debugName: 'CreateBrowserRouterRoutesLazyCallback',
  signature: const (
    positional: [],
    result: reactAny,
    asynchronous: false,
  ),
  invoke: (arguments) {
    return fn();
  },
);

/// TS: (to: any) => string
typedef RouterNavigatorCreateHrefCallback = String Function(Object? to);

/// Wraps a [RouterNavigatorCreateHrefCallback] into a [ReactCallback] for prop encoding.
ReactCallback routerNavigatorCreateHrefCallback(RouterNavigatorCreateHrefCallback fn) => ReactCallback(
  debugName: 'RouterNavigatorCreateHrefCallback',
  signature: const (
    positional: [reactAny],
    result: reactAny,
    asynchronous: false,
  ),
  invoke: (arguments) {
    return fn(arguments[0]);
  },
);

/// TS: (to: any) => { pathname: string; search: string; hash: string }
typedef RouterNavigatorEncodeLocationCallback = Object? Function(Object? to);

/// Wraps a [RouterNavigatorEncodeLocationCallback] into a [ReactCallback] for prop encoding.
ReactCallback routerNavigatorEncodeLocationCallback(RouterNavigatorEncodeLocationCallback fn) => ReactCallback(
  debugName: 'RouterNavigatorEncodeLocationCallback',
  signature: const (
    positional: [reactAny],
    result: reactAny,
    asynchronous: false,
  ),
  invoke: (arguments) {
    return fn(arguments[0]);
  },
);

/// TS: (delta: number) => void
typedef RouterNavigatorGoCallback = void Function(num delta);

/// Wraps a [RouterNavigatorGoCallback] into a [ReactCallback] for prop encoding.
ReactCallback routerNavigatorGoCallback(RouterNavigatorGoCallback fn) => ReactCallback(
  debugName: 'RouterNavigatorGoCallback',
  signature: const (
    positional: [reactAny],
    result: reactVoid,
    asynchronous: false,
  ),
  invoke: (arguments) {
    fn(arguments[0] as num);
    return null;
  },
);

/// TS: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
typedef RouterNavigatorPushCallback = void Function(Object? to, Object? state, Object? opts);

/// Wraps a [RouterNavigatorPushCallback] into a [ReactCallback] for prop encoding.
ReactCallback routerNavigatorPushCallback(RouterNavigatorPushCallback fn) => ReactCallback(
  debugName: 'RouterNavigatorPushCallback',
  signature: const (
    positional: [reactAny, reactAny, reactAny],
    result: reactVoid,
    asynchronous: false,
  ),
  invoke: (arguments) {
    fn(arguments[0], arguments[1], arguments[2]);
    return null;
  },
);

/// TS: (location: { pathname: string; search: string; hash: string; state: any; key: string }, matches: { id: string; pathname: string; params: unknown; data: any; handle: any }[]) => string
typedef ScrollRestorationGetKeyCallback = String Function(Object? location, Object? matches);

/// Wraps a [ScrollRestorationGetKeyCallback] into a [ReactCallback] for prop encoding.
ReactCallback scrollRestorationGetKeyCallback(ScrollRestorationGetKeyCallback fn) => ReactCallback(
  debugName: 'ScrollRestorationGetKeyCallback',
  signature: const (
    positional: [reactAny, reactAny],
    result: reactAny,
    asynchronous: false,
  ),
  invoke: (arguments) {
    return fn(arguments[0], arguments[1]);
  },
);

/// Literal union: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
enum FormEncType {
  applicationXWwwFormUrlencoded('application/x-www-form-urlencoded'),
  multipartFormData('multipart/form-data'),
  textPlain('text/plain');
  const FormEncType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static FormEncType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown FormEncType'),
  );
}

/// Literal union: "POP" | "PUSH" | "REPLACE"
enum NavigationType {
  pop('POP'),
  push('PUSH'),
  replace('REPLACE');
  const NavigationType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static NavigationType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown NavigationType'),
  );
}

/// Literal union: "route" | "path"
enum RelativeRoutingType {
  route('route'),
  path('path');
  const RelativeRoutingType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static RelativeRoutingType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown RelativeRoutingType'),
  );
}

/// Typed props for `AgnosticRouteMatch`.
///
/// params: unknown; pathname: string; pathnameBase: string; route: any
class AgnosticRouteMatch {
  const AgnosticRouteMatch({
    required Object? this.params,
    required String this.pathname,
    required String this.pathnameBase,
    required Object this.route,
  });

  /// TS: unknown
  final Object? params;

  /// TS: string
  final String pathname;

  /// TS: string
  final String pathnameBase;

  /// TS: any
  final Object route;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    'params': params,
    'pathname': pathname,
    'pathnameBase': pathnameBase,
    'route': route,
  };
}

/// Typed props for `CreateBrowserRouterRoutes`.
///
/// caseSensitive?: any; path?: any; id?: any; loader?: any; action?: any
/// hasErrorBoundary?: any; shouldRevalidate?: any; handle?: any
/// index: true | false; children?: any[]; element?: React.ReactNode
/// hydrateFallbackElement?: React.ReactNode; errorElement?: React.ReactNode
/// Component?: any; HydrateFallback?: any; ErrorBoundary?: any
/// lazy?: () => any
class CreateBrowserRouterRoutes {
  const CreateBrowserRouterRoutes({
    Object? this.caseSensitive,
    Object? this.path,
    Object? this.id,
    Object? this.loader,
    Object? this.action,
    Object? this.hasErrorBoundary,
    Object? this.shouldRevalidate,
    Object? this.handle,
    required bool this.index,
    List<Object?>? this.children,
    ReactNode? this.element,
    ReactNode? this.hydrateFallbackElement,
    ReactNode? this.errorElement,
    Object? this.Component,
    Object? this.HydrateFallback,
    Object? this.ErrorBoundary,
    CreateBrowserRouterRoutesLazyCallback? this.lazy,
  });

  /// TS: any
  final Object? caseSensitive;

  /// TS: any
  final Object? path;

  /// TS: any
  final Object? id;

  /// TS: any
  final Object? loader;

  /// TS: any
  final Object? action;

  /// TS: any
  final Object? hasErrorBoundary;

  /// TS: any
  final Object? shouldRevalidate;

  /// TS: any
  final Object? handle;

  /// TS: true | false
  final bool index;

  /// TS: any[]
  final List<Object?>? children;

  /// TS: React.ReactNode
  final ReactNode? element;

  /// TS: React.ReactNode
  final ReactNode? hydrateFallbackElement;

  /// TS: React.ReactNode
  final ReactNode? errorElement;

  /// TS: any
  final Object? Component;

  /// TS: any
  final Object? HydrateFallback;

  /// TS: any
  final Object? ErrorBoundary;

  /// TS: () => any
  final CreateBrowserRouterRoutesLazyCallback? lazy;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (caseSensitive != null) 'caseSensitive': caseSensitive,
    if (path != null) 'path': path,
    if (id != null) 'id': id,
    if (loader != null) 'loader': loader,
    if (action != null) 'action': action,
    if (hasErrorBoundary != null) 'hasErrorBoundary': hasErrorBoundary,
    if (shouldRevalidate != null) 'shouldRevalidate': shouldRevalidate,
    if (handle != null) 'handle': handle,
    'index': index,
    if (children != null) 'children': children,
    if (element != null) 'element': element,
    if (hydrateFallbackElement != null) 'hydrateFallbackElement': hydrateFallbackElement,
    if (errorElement != null) 'errorElement': errorElement,
    if (Component != null) 'Component': Component,
    if (HydrateFallback != null) 'HydrateFallback': HydrateFallback,
    if (ErrorBoundary != null) 'ErrorBoundary': ErrorBoundary,
    if (lazy != null) 'lazy': lazy,
  };
}

/// Typed props for `CreateMemoryRouterOpts`.
///
/// basename?: string; future?: { value?: any }; hydrationData?: { value?: any }
/// initialEntries?: any[]; initialIndex?: number; unstable_dataStrategy?: any
/// unstable_patchRoutesOnNavigation?: Record<string, unknown>
class CreateMemoryRouterOpts {
  const CreateMemoryRouterOpts({
    String? this.basename,
    Omit? this.future,
    Pick? this.hydrationData,
    List<Object?>? this.initialEntries,
    num? this.initialIndex,
    Object? this.unstable_dataStrategy,
    Object? this.unstable_patchRoutesOnNavigation,
  });

  /// TS: string
  final String? basename;

  /// TS: { value?: any }
  final Omit? future;

  /// TS: { value?: any }
  final Pick? hydrationData;

  /// TS: any[]
  final List<Object?>? initialEntries;

  /// TS: number
  final num? initialIndex;

  /// TS: any
  final Object? unstable_dataStrategy;

  /// TS: Record<string, unknown>
  final Object? unstable_patchRoutesOnNavigation;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (basename != null) 'basename': basename,
    if (future != null) 'future': future!.toJson(),
    if (hydrationData != null) 'hydrationData': hydrationData!.toJson(),
    if (initialEntries != null) 'initialEntries': initialEntries,
    if (initialIndex != null) 'initialIndex': initialIndex,
    if (unstable_dataStrategy != null) 'unstable_dataStrategy': unstable_dataStrategy,
    if (unstable_patchRoutesOnNavigation != null) 'unstable_patchRoutesOnNavigation': unstable_patchRoutesOnNavigation,
  };
}

/// Typed props for `DOMRouterOpts`.
///
/// basename?: string; future?: { value?: any }; hydrationData?: { value?: any }
/// unstable_dataStrategy?: any
/// unstable_patchRoutesOnNavigation?: Record<string, unknown>; window?: any
class DOMRouterOpts {
  const DOMRouterOpts({
    String? this.basename,
    Omit? this.future,
    Pick? this.hydrationData,
    Object? this.unstable_dataStrategy,
    Object? this.unstable_patchRoutesOnNavigation,
    Object? this.window,
  });

  /// TS: string
  final String? basename;

  /// TS: { value?: any }
  final Omit? future;

  /// TS: { value?: any }
  final Pick? hydrationData;

  /// TS: any
  final Object? unstable_dataStrategy;

  /// TS: Record<string, unknown>
  final Object? unstable_patchRoutesOnNavigation;

  /// TS: any
  final Object? window;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (basename != null) 'basename': basename,
    if (future != null) 'future': future!.toJson(),
    if (hydrationData != null) 'hydrationData': hydrationData!.toJson(),
    if (unstable_dataStrategy != null) 'unstable_dataStrategy': unstable_dataStrategy,
    if (unstable_patchRoutesOnNavigation != null) 'unstable_patchRoutesOnNavigation': unstable_patchRoutesOnNavigation,
    if (window != null) 'window': window,
  };
}

/// Typed props for `FutureConfig`.
///
/// v7_relativeSplatPath?: boolean; v7_startTransition?: boolean
class FutureConfig {
  const FutureConfig({
    bool? this.v7_relativeSplatPath,
    bool? this.v7_startTransition,
  });

  /// TS: boolean
  final bool? v7_relativeSplatPath;

  /// TS: boolean
  final bool? v7_startTransition;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (v7_relativeSplatPath != null) 'v7_relativeSplatPath': v7_relativeSplatPath,
    if (v7_startTransition != null) 'v7_startTransition': v7_startTransition,
  };
}

/// Typed props for `MatchPathPattern`.
///
/// path: { pathname: string; search: string; hash: string }
/// caseSensitive?: boolean; end?: boolean; pathname: string; search: string
/// hash: string
class MatchPathPattern {
  const MatchPathPattern({
    required Path this.path,
    bool? this.caseSensitive,
    bool? this.end,
    required String this.pathname,
    required String this.search,
    required String this.hash,
  });

  /// TS: { pathname: string; search: string; hash: string }
  final Path path;

  /// TS: boolean
  final bool? caseSensitive;

  /// TS: boolean
  final bool? end;

  /// TS: string
  final String pathname;

  /// TS: string
  final String search;

  /// TS: string
  final String hash;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    'path': path.toJson(),
    if (caseSensitive != null) 'caseSensitive': caseSensitive,
    if (end != null) 'end': end,
    'pathname': pathname,
    'search': search,
    'hash': hash,
  };
}

/// Typed props for `Navigator`.
///
/// createHref: (to: any) => string
/// encodeLocation?: (to: any) => { pathname: string; search: string; hash: string }
/// go: (delta: number) => void
/// push: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
/// replace: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
class Navigator {
  const Navigator({
    required RouterNavigatorCreateHrefCallback this.createHref,
    RouterNavigatorEncodeLocationCallback? this.encodeLocation,
    required RouterNavigatorGoCallback this.go,
    required RouterNavigatorPushCallback this.push,
    required RouterNavigatorPushCallback this.replace,
  });

  /// TS: (to: any) => string
  final RouterNavigatorCreateHrefCallback createHref;

  /// TS: (to: any) => { pathname: string; search: string; hash: string }
  final RouterNavigatorEncodeLocationCallback? encodeLocation;

  /// TS: (delta: number) => void
  final RouterNavigatorGoCallback go;

  /// TS: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
  final RouterNavigatorPushCallback push;

  /// TS: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
  final RouterNavigatorPushCallback replace;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    'createHref': createHref,
    if (encodeLocation != null) 'encodeLocation': encodeLocation,
    'go': go,
    'push': push,
    'replace': replace,
  };
}

/// Typed props for `Omit`.
///
/// value?: any
class Omit {
  const Omit({
    Object? this.value,
  });

  /// TS: any
  final Object? value;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (value != null) 'value': value,
  };
}

/// Typed props for `Path`.
///
/// pathname: string; search: string; hash: string
extension type _PathJs(JSObject _) implements JSObject {
  external JSString get pathname;
  external JSString get search;
  external JSString get hash;
}

class Path {
  const Path({
    required String this.pathname,
    required String this.search,
    required String this.hash,
  });

  /// TS: string
  final String pathname;

  /// TS: string
  final String search;

  /// TS: string
  final String hash;

  /// Decodes the shim's raw JS object.
  factory Path.fromJs(JSObject js) {
    final v = _PathJs(js);
    return Path(
      pathname: v.pathname.toDart,
      search: v.search.toDart,
      hash: v.hash.toDart,
    );
  }

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    'pathname': pathname,
    'search': search,
    'hash': hash,
  };
}

extension type _PathMatchJs(JSObject _) implements JSObject {
  external JSAny? get params;
  external JSString get pathname;
  external JSString get pathnameBase;
  external JSObject get pattern;
}

/// Typed props for `PathMatch`.
///
/// params: unknown; pathname: string; pathnameBase: string
/// pattern: { path: { pathname: string; search: string; hash: string }; caseSensitive?: boolean; end?: boolean }
class PathMatch {
  const PathMatch({
    required Object? this.params,
    required String this.pathname,
    required String this.pathnameBase,
    required PathPattern this.pattern,
  });

  /// TS: unknown
  final Object? params;

  /// TS: string
  final String pathname;

  /// TS: string
  final String pathnameBase;

  /// TS: { path: { pathname: string; search: string; hash: string }; caseSensitive?: boolean; end?: boolean }
  final PathPattern pattern;

  /// Decodes the shim's raw JS object.
  factory PathMatch.fromJs(JSObject js) {
    final v = _PathMatchJs(js);
    return PathMatch(
      params: v.params,
      pathname: v.pathname.toDart,
      pathnameBase: v.pathnameBase.toDart,
      pattern: PathPattern.fromJs(v.pattern),
    );
  }

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    'params': params,
    'pathname': pathname,
    'pathnameBase': pathnameBase,
    'pattern': pattern.toJson(),
  };
}

/// Typed props for `PathPattern`.
///
/// path: { pathname: string; search: string; hash: string }
/// caseSensitive?: boolean; end?: boolean
class PathPattern {
  const PathPattern({
    required Path this.path,
    bool? this.caseSensitive,
    bool? this.end,
  });

  /// TS: { pathname: string; search: string; hash: string }
  final Path path;

  /// TS: boolean
  final bool? caseSensitive;

  /// TS: boolean
  final bool? end;

  /// Decodes the shim's raw JS object.
  factory PathPattern.fromJs(JSObject js) {
    final v = _PathPatternJs(js);
    return PathPattern(
      path: Path.fromJs(v.path),
      caseSensitive: v.caseSensitive?.toDart,
      end: v.end?.toDart,
    );
  }

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    'path': path.toJson(),
    if (caseSensitive != null) 'caseSensitive': caseSensitive,
    if (end != null) 'end': end,
  };
}

extension type _PathPatternJs(JSObject _) implements JSObject {
  external _PathJs get path;
  external JSBoolean? get caseSensitive;
  external JSBoolean? get end;
}

/// Typed props for `Pick`.
///
/// value?: any
class Pick {
  const Pick({
    Object? this.value,
  });

  /// TS: any
  final Object? value;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (value != null) 'value': value,
  };
}

/// Typed props for `RouteMatch`.
///
/// params: unknown; pathname: string; pathnameBase: string; route: any
class RouteMatch {
  const RouteMatch({
    required Object? this.params,
    required String this.pathname,
    required String this.pathnameBase,
    required Object this.route,
  });

  /// TS: unknown
  final Object? params;

  /// TS: string
  final String pathname;

  /// TS: string
  final String pathnameBase;

  /// TS: any
  final Object route;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    'params': params,
    'pathname': pathname,
    'pathnameBase': pathnameBase,
    'route': route,
  };
}
