// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom BrowserRouter MemoryRouter Routes Route Link NavLink Outlet Navigate useHref useInRouterContext useLocation useNavigate useNavigationType useOutlet useParams useSearchParams useMatches useNavigation useRevalidator useResolvedPath useRouteError useRouteLoaderData useRoutes useBlocker useFetcher useFetchers useFormAction useLinkClickHandler useLoaderData useSubmit useActionData useOutletContext useAsyncValue useAsyncError --shim
//
// Registers the bound `react-router-dom` components under the
// `reactRouter.*` names used by the generated Dart helpers.
// Wire this module into react.yaml under `foreign.modules`.

import * as ReactRouterDom from 'react-router-dom';

const components = {
  'reactRouter.BrowserRouter': ReactRouterDom.BrowserRouter,
  'reactRouter.MemoryRouter': ReactRouterDom.MemoryRouter,
  'reactRouter.Routes': ReactRouterDom.Routes,
  'reactRouter.Route': ReactRouterDom.Route,
  'reactRouter.Link': ReactRouterDom.Link,
  'reactRouter.NavLink': ReactRouterDom.NavLink,
  'reactRouter.Outlet': ReactRouterDom.Outlet,
  'reactRouter.Navigate': ReactRouterDom.Navigate,
};

for (const [name, component] of Object.entries(components)) {
  globalThis.__reactDartRegisterComponent?.(name, component);
}

globalThis.__reactDartBindings ??= Object.create(null);
globalThis.__reactDartBindings.reactRouter = {};

// Hook bridge: the generated Dart hooks (`--hooks` output) call
// these members during render. Results are decoded into
// primitives or `[[key, value], ...]` pairs (via `toPairs`)
// because dart2js cannot cast a raw callAsFunction result.
const toPairs = (v) => {
  if (v == null) return v;
  if (Array.isArray(v)) return v.map(toPairs);
  if (typeof v === 'object') {
    if (typeof v.entries === 'function') return [...v.entries()];
    return Object.entries(v).map(([k, val]) => [k, toPairs(val)]);
  }
  return v;
};

const hooks = {
  useHref: (a0, a1) => ReactRouterDom.useHref(a0, a1),
  useInRouterContext: () => ReactRouterDom.useInRouterContext(),
  useLocation: () => ReactRouterDom.useLocation(),
  useNavigate: () => ReactRouterDom.useNavigate(),
  useNavigationType: () => ReactRouterDom.useNavigationType(),
  useOutlet: (a0) => ReactRouterDom.useOutlet(a0),
  useParams: () => ReactRouterDom.useParams(),
  useSearchParams: (a0) => ReactRouterDom.useSearchParams(a0),
  useMatches: () => ReactRouterDom.useMatches(),
  useNavigation: () => ReactRouterDom.useNavigation(),
  useRevalidator: () => ReactRouterDom.useRevalidator(),
  useResolvedPath: (a0, a1) => ReactRouterDom.useResolvedPath(a0, a1),
  useRouteError: () => ReactRouterDom.useRouteError(),
  useRouteLoaderData: (a0) => ReactRouterDom.useRouteLoaderData(a0),
  useRoutes: (a0, a1) => ReactRouterDom.useRoutes(a0, a1),
  useBlocker: (a0) => ReactRouterDom.useBlocker(a0),
  useFetcher: (a0) => ReactRouterDom.useFetcher(a0),
  useFetchers: () => ReactRouterDom.useFetchers(),
  useFormAction: (a0, a1) => ReactRouterDom.useFormAction(a0, a1),
  useLinkClickHandler: (a0, a1) => ReactRouterDom.useLinkClickHandler(a0, a1),
  useLoaderData: () => ReactRouterDom.useLoaderData(),
  useSubmit: () => ReactRouterDom.useSubmit(),
  useActionData: () => ReactRouterDom.useActionData(),
  useOutletContext: () => ReactRouterDom.useOutletContext(),
  useAsyncValue: () => ReactRouterDom.useAsyncValue(),
  useAsyncError: () => ReactRouterDom.useAsyncError(),
};

globalThis.__reactDartBindings.reactRouter = hooks;
