// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom
// Source: react-router-dom
// (extracted from /run/media/kingwill101/disk2/code/code/dart_packages/react_workspace/.dart_tool/react/js/node_modules/react-router-dom/./dist/index.d.ts)
// ignore_for_file: type=lint

import 'package:react/react.dart';

/// Typed helper for the `reactRouter.RouterProvider` foreign component.
///
/// Props from `RouterProvider`:
///
/// fallbackElement?: React.ReactNode; router: Record<string, unknown>
/// future?: { value?: any }
ReactNode routerProvider({
  String? key,
    ReactNode? fallbackElement,
    required Object router,
    Pick? future,
}) => foreignComponent(
  'reactRouter.RouterProvider',
  key: key,
  props: {
    if (fallbackElement != null) 'fallbackElement': fallbackElement,
    'router': router,
    if (future != null) 'future': future.toJson(),
  },
);

/// Typed helper for the `reactRouter.BrowserRouter` foreign component.
///
/// Props from `BrowserRouter`:
///
/// basename?: string; children?: React.ReactNode
/// future?: { v7_relativeSplatPath?: boolean; v7_startTransition?: boolean }
/// window?: any
ReactNode browserRouter({
  String? key,
  List<ReactNode> children = const [],
    String? basename,
    FutureConfig? future,
    Object? window,
}) => foreignComponent(
  'reactRouter.BrowserRouter',
  key: key,
  props: {
    if (basename != null) 'basename': basename,
    if (future != null) 'future': future.toJson(),
    if (window != null) 'window': window,
  },
  children: children,
);

/// Typed helper for the `reactRouter.HashRouter` foreign component.
///
/// Props from `HashRouter`:
///
/// basename?: string; children?: React.ReactNode
/// future?: { v7_relativeSplatPath?: boolean; v7_startTransition?: boolean }
/// window?: any
ReactNode hashRouter({
  String? key,
  List<ReactNode> children = const [],
    String? basename,
    FutureConfig? future,
    Object? window,
}) => foreignComponent(
  'reactRouter.HashRouter',
  key: key,
  props: {
    if (basename != null) 'basename': basename,
    if (future != null) 'future': future.toJson(),
    if (window != null) 'window': window,
  },
  children: children,
);

/// Typed helper for the `reactRouter.Link` foreign component.
///
/// Props from `Link`:
///
/// children?: React.ReactNode; className?: string
/// style?: Record<string, unknown>; id?: string; title?: string; lang?: string
/// dir?: string; hidden?: boolean; tabIndex?: number; role?: string
/// target?: string; rel?: string; download?: boolean; onClick?: host value
/// reloadDocument?: boolean; replace?: boolean; state?: any
/// preventScrollReset?: boolean; relative?: "route" | "path"; to: any
/// unstable_viewTransition?: boolean
ReactNode link({
  String? key,
  List<ReactNode> children = const [],
    String? className,
    Object? style,
    String? id,
    String? title,
    String? lang,
    String? dir,
    bool? hidden,
    num? tabIndex,
    String? role,
    String? target,
    String? rel,
    bool? download,
    Object? onClick,
    bool? reloadDocument,
    bool? replace,
    Object? state,
    bool? preventScrollReset,
    RelativeRoutingType? relative,
    required Object to,
    bool? unstable_viewTransition,
}) => foreignComponent(
  'reactRouter.Link',
  key: key,
  props: {
    if (className != null) 'className': className,
    if (style != null) 'style': style,
    if (id != null) 'id': id,
    if (title != null) 'title': title,
    if (lang != null) 'lang': lang,
    if (dir != null) 'dir': dir,
    if (hidden != null) 'hidden': hidden,
    if (tabIndex != null) 'tabIndex': tabIndex,
    if (role != null) 'role': role,
    if (target != null) 'target': target,
    if (rel != null) 'rel': rel,
    if (download != null) 'download': download,
    if (onClick != null) 'onClick': onClick,
    if (reloadDocument != null) 'reloadDocument': reloadDocument,
    if (replace != null) 'replace': replace,
    if (state != null) 'state': state,
    if (preventScrollReset != null) 'preventScrollReset': preventScrollReset,
    if (relative != null) 'relative': relative.value,
    'to': to,
    if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition,
  },
  children: children,
);

/// Typed helper for the `reactRouter.NavLink` foreign component.
///
/// Props from `NavLink`:
///
/// children?: React.ReactNode; className?: string
/// style?: Record<string, unknown>; id?: string; title?: string; lang?: string
/// dir?: string; hidden?: boolean; tabIndex?: number; role?: string
/// target?: string; rel?: string; download?: boolean; onClick?: host value
/// reloadDocument?: boolean; replace?: boolean; state?: any
/// preventScrollReset?: boolean; relative?: "route" | "path"; to: any
/// unstable_viewTransition?: boolean; caseSensitive?: boolean; end?: boolean
ReactNode navLink({
  String? key,
  List<ReactNode> children = const [],
    String? className,
    Object? style,
    String? id,
    String? title,
    String? lang,
    String? dir,
    bool? hidden,
    num? tabIndex,
    String? role,
    String? target,
    String? rel,
    bool? download,
    Object? onClick,
    bool? reloadDocument,
    bool? replace,
    Object? state,
    bool? preventScrollReset,
    RelativeRoutingType? relative,
    required Object to,
    bool? unstable_viewTransition,
    bool? caseSensitive,
    bool? end,
}) => foreignComponent(
  'reactRouter.NavLink',
  key: key,
  props: {
    if (className != null) 'className': className,
    if (style != null) 'style': style,
    if (id != null) 'id': id,
    if (title != null) 'title': title,
    if (lang != null) 'lang': lang,
    if (dir != null) 'dir': dir,
    if (hidden != null) 'hidden': hidden,
    if (tabIndex != null) 'tabIndex': tabIndex,
    if (role != null) 'role': role,
    if (target != null) 'target': target,
    if (rel != null) 'rel': rel,
    if (download != null) 'download': download,
    if (onClick != null) 'onClick': onClick,
    if (reloadDocument != null) 'reloadDocument': reloadDocument,
    if (replace != null) 'replace': replace,
    if (state != null) 'state': state,
    if (preventScrollReset != null) 'preventScrollReset': preventScrollReset,
    if (relative != null) 'relative': relative.value,
    'to': to,
    if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition,
    if (caseSensitive != null) 'caseSensitive': caseSensitive,
    if (end != null) 'end': end,
  },
  children: children,
);

/// Typed helper for the `reactRouter.Form` foreign component.
///
/// Props from `Form`:
///
/// method?: Record<string, unknown>
/// encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
/// action?: string; relative?: "route" | "path"; preventScrollReset?: boolean
/// onSubmit?: any; fetcherKey?: string; navigate?: boolean
/// reloadDocument?: boolean; replace?: boolean; state?: any
/// unstable_viewTransition?: boolean
ReactNode form({
  String? key,
    Object? method,
    FormEncType? encType,
    String? action,
    RelativeRoutingType? relative,
    bool? preventScrollReset,
    Object? onSubmit,
    String? fetcherKey,
    bool? navigate,
    bool? reloadDocument,
    bool? replace,
    Object? state,
    bool? unstable_viewTransition,
}) => foreignComponent(
  'reactRouter.Form',
  key: key,
  props: {
    if (method != null) 'method': method,
    if (encType != null) 'encType': encType.value,
    if (action != null) 'action': action,
    if (relative != null) 'relative': relative.value,
    if (preventScrollReset != null) 'preventScrollReset': preventScrollReset,
    if (onSubmit != null) 'onSubmit': onSubmit,
    if (fetcherKey != null) 'fetcherKey': fetcherKey,
    if (navigate != null) 'navigate': navigate,
    if (reloadDocument != null) 'reloadDocument': reloadDocument,
    if (replace != null) 'replace': replace,
    if (state != null) 'state': state,
    if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition,
  },
);

/// Typed helper for the `reactRouter.ScrollRestoration` foreign component.
///
/// Props from `ScrollRestoration`:
///
/// getKey?: (location: { pathname: string; search: string; hash: string; state: any; key: string }, matches: { id: string; pathname: string; params: unknown; data: any; handle: any }[]) => string
/// storageKey?: string
ReactNode scrollRestoration({
  String? key,
    /// TS: (location: { pathname: string; search: string; hash: string; state: any; key: string }, matches: { id: string; pathname: string; params: unknown; data: any; handle: any }[]) => string
    ScrollRestorationGetKeyCallback? getKey,
    String? storageKey,
}) => foreignComponent(
  'reactRouter.ScrollRestoration',
  key: key,
  props: {
    if (getKey != null) 'getKey': getKey,
    if (storageKey != null) 'storageKey': storageKey,
  },
);








/// Typed helper for the `reactRouter.MemoryRouter` foreign component.
///
/// Props from `MemoryRouter`:
///
/// basename?: string; children?: React.ReactNode; initialEntries?: any[]
/// initialIndex?: number
/// future?: { v7_relativeSplatPath?: boolean; v7_startTransition?: boolean }
ReactNode memoryRouter({
  String? key,
  List<ReactNode> children = const [],
    String? basename,
    List<Object?>? initialEntries,
    num? initialIndex,
    FutureConfig? future,
}) => foreignComponent(
  'reactRouter.MemoryRouter',
  key: key,
  props: {
    if (basename != null) 'basename': basename,
    if (initialEntries != null) 'initialEntries': initialEntries,
    if (initialIndex != null) 'initialIndex': initialIndex,
    if (future != null) 'future': future.toJson(),
  },
  children: children,
);

/// Typed helper for the `reactRouter.Navigate` foreign component.
///
/// Props from `Navigate`:
///
/// to: any; replace?: boolean; state?: any; relative?: "route" | "path"
ReactNode navigate({
  String? key,
    required Object to,
    bool? replace,
    Object? state,
    RelativeRoutingType? relative,
}) => foreignComponent(
  'reactRouter.Navigate',
  key: key,
  props: {
    'to': to,
    if (replace != null) 'replace': replace,
    if (state != null) 'state': state,
    if (relative != null) 'relative': relative.value,
  },
);

/// Typed helper for the `reactRouter.Outlet` foreign component.
///
/// Props from `Outlet`:
///
/// context?: unknown
ReactNode outlet({
  String? key,
    Object? context,
}) => foreignComponent(
  'reactRouter.Outlet',
  key: key,
  props: {
    if (context != null) 'context': context,
  },
);

/// Typed helper for the `reactRouter.Route` foreign component.
///
/// Props from `Route`:
///
/// caseSensitive?: any; path?: any; id?: any; lazy?: () => any; loader?: any
/// action?: any; hasErrorBoundary?: any; shouldRevalidate?: any; handle?: any
/// index?: false | false | true; children?: React.ReactNode
/// element?: React.ReactNode; hydrateFallbackElement?: React.ReactNode
/// errorElement?: React.ReactNode; Component?: any; HydrateFallback?: any
/// ErrorBoundary?: any
ReactNode route({
  String? key,
  List<ReactNode> children = const [],
    Object? caseSensitive,
    Object? path,
    Object? id,
    /// TS: () => any
    RouteLazyCallback? lazy,
    Object? loader,
    Object? action,
    Object? hasErrorBoundary,
    Object? shouldRevalidate,
    Object? handle,
    bool? index,
    ReactNode? element,
    ReactNode? hydrateFallbackElement,
    ReactNode? errorElement,
    Object? Component,
    Object? HydrateFallback,
    Object? ErrorBoundary,
}) => foreignComponent(
  'reactRouter.Route',
  key: key,
  props: {
    if (caseSensitive != null) 'caseSensitive': caseSensitive,
    if (path != null) 'path': path,
    if (id != null) 'id': id,
    if (lazy != null) 'lazy': lazy,
    if (loader != null) 'loader': loader,
    if (action != null) 'action': action,
    if (hasErrorBoundary != null) 'hasErrorBoundary': hasErrorBoundary,
    if (shouldRevalidate != null) 'shouldRevalidate': shouldRevalidate,
    if (handle != null) 'handle': handle,
    if (index != null) 'index': index,
    if (element != null) 'element': element,
    if (hydrateFallbackElement != null) 'hydrateFallbackElement': hydrateFallbackElement,
    if (errorElement != null) 'errorElement': errorElement,
    if (Component != null) 'Component': Component,
    if (HydrateFallback != null) 'HydrateFallback': HydrateFallback,
    if (ErrorBoundary != null) 'ErrorBoundary': ErrorBoundary,
  },
  children: children,
);

/// Typed helper for the `reactRouter.Router` foreign component.
///
/// Props from `Router`:
///
/// basename?: string; children?: React.ReactNode; location: any
/// navigationType?: "POP" | "PUSH" | "REPLACE"
/// navigator: { createHref: (to: any) => string; encodeLocation?: (to: any) => { pathname: string; search: string; hash: string }; go: (delta: number) => void; push: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void; replace: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void }
/// static?: boolean; future?: { value?: any }
ReactNode router({
  String? key,
  List<ReactNode> children = const [],
    String? basename,
    required Object location,
    NavigationType? navigationType,
    required Navigator navigator,
    bool? static,
    Pick? future,
}) => foreignComponent(
  'reactRouter.Router',
  key: key,
  props: {
    if (basename != null) 'basename': basename,
    'location': location,
    if (navigationType != null) 'navigationType': navigationType.value,
    'navigator': navigator.toJson(),
    if (static != null) 'static': static,
    if (future != null) 'future': future.toJson(),
  },
  children: children,
);

/// Typed helper for the `reactRouter.Routes` foreign component.
///
/// Props from `Routes`:
///
/// children?: React.ReactNode; location?: any
ReactNode routes({
  String? key,
  List<ReactNode> children = const [],
    Object? location,
}) => foreignComponent(
  'reactRouter.Routes',
  key: key,
  props: {
    if (location != null) 'location': location,
  },
  children: children,
);

/// Typed helper for the `reactRouter.Await` foreign component.
///
/// Props from `Await`:
///
/// children: any; errorElement?: React.ReactNode; resolve: any
ReactNode await({
  String? key,
  required List<ReactNode> children,
    ReactNode? errorElement,
    required Object resolve,
}) => foreignComponent(
  'reactRouter.Await',
  key: key,
  props: {
    if (errorElement != null) 'errorElement': errorElement,
    'resolve': resolve,
  },
  children: children,
);

/// Typed helper for the `reactRouter.renderMatches` foreign component.
///
/// Props from `renderMatches`:
///
/// value: { params: unknown; pathname: string; pathnameBase: string; route: any }[]
ReactNode renderMatches({
  String? key,
    required List<RouteMatch> value,
}) => foreignComponent(
  'reactRouter.renderMatches',
  key: key,
  props: {
    'value': value.map((e) => e.toJson()).toList(),
  },
);






















/// TS: () => any
typedef RouteLazyCallback = Object? Function();

/// Wraps a [RouteLazyCallback] into a [ReactCallback] for prop encoding.
ReactCallback routeLazyCallback(RouteLazyCallback fn) => ReactCallback(
  debugName: 'RouteLazyCallback',
  signature: const (
    positional: [],
    result: reactAny,
    asynchronous: false,
  ),
  invoke: (arguments) {
    return fn();
  },
);

/// TS: (to: any) => string
typedef RouterNavigatorCreateHrefCallback = String Function(Object? to);

/// Wraps a [RouterNavigatorCreateHrefCallback] into a [ReactCallback] for prop encoding.
ReactCallback routerNavigatorCreateHrefCallback(RouterNavigatorCreateHrefCallback fn) => ReactCallback(
  debugName: 'RouterNavigatorCreateHrefCallback',
  signature: const (
    positional: [reactAny],
    result: reactAny,
    asynchronous: false,
  ),
  invoke: (arguments) {
    return fn(arguments[0]);
  },
);

/// TS: (to: any) => { pathname: string; search: string; hash: string }
typedef RouterNavigatorEncodeLocationCallback = Object? Function(Object? to);

/// Wraps a [RouterNavigatorEncodeLocationCallback] into a [ReactCallback] for prop encoding.
ReactCallback routerNavigatorEncodeLocationCallback(RouterNavigatorEncodeLocationCallback fn) => ReactCallback(
  debugName: 'RouterNavigatorEncodeLocationCallback',
  signature: const (
    positional: [reactAny],
    result: reactAny,
    asynchronous: false,
  ),
  invoke: (arguments) {
    return fn(arguments[0]);
  },
);

/// TS: (delta: number) => void
typedef RouterNavigatorGoCallback = void Function(num delta);

/// Wraps a [RouterNavigatorGoCallback] into a [ReactCallback] for prop encoding.
ReactCallback routerNavigatorGoCallback(RouterNavigatorGoCallback fn) => ReactCallback(
  debugName: 'RouterNavigatorGoCallback',
  signature: const (
    positional: [reactAny],
    result: reactVoid,
    asynchronous: false,
  ),
  invoke: (arguments) {
    fn(arguments[0] as num);
    return null;
  },
);

/// TS: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
typedef RouterNavigatorPushCallback = void Function(Object? to, Object? state, Object? opts);

/// Wraps a [RouterNavigatorPushCallback] into a [ReactCallback] for prop encoding.
ReactCallback routerNavigatorPushCallback(RouterNavigatorPushCallback fn) => ReactCallback(
  debugName: 'RouterNavigatorPushCallback',
  signature: const (
    positional: [reactAny, reactAny, reactAny],
    result: reactVoid,
    asynchronous: false,
  ),
  invoke: (arguments) {
    fn(arguments[0], arguments[1], arguments[2]);
    return null;
  },
);

/// TS: (location: { pathname: string; search: string; hash: string; state: any; key: string }, matches: { id: string; pathname: string; params: unknown; data: any; handle: any }[]) => string
typedef ScrollRestorationGetKeyCallback = String Function(Object? location, Object? matches);

/// Wraps a [ScrollRestorationGetKeyCallback] into a [ReactCallback] for prop encoding.
ReactCallback scrollRestorationGetKeyCallback(ScrollRestorationGetKeyCallback fn) => ReactCallback(
  debugName: 'ScrollRestorationGetKeyCallback',
  signature: const (
    positional: [reactAny, reactAny],
    result: reactAny,
    asynchronous: false,
  ),
  invoke: (arguments) {
    return fn(arguments[0], arguments[1]);
  },
);

/// Literal union: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
enum FormEncType {
  applicationXWwwFormUrlencoded('application/x-www-form-urlencoded'),
  multipartFormData('multipart/form-data'),
  textPlain('text/plain');
  const FormEncType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static FormEncType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown FormEncType'),
  );
}

/// Literal union: "POP" | "PUSH" | "REPLACE"
enum NavigationType {
  pop('POP'),
  push('PUSH'),
  replace('REPLACE');
  const NavigationType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static NavigationType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown NavigationType'),
  );
}

/// Literal union: "route" | "path"
enum RelativeRoutingType {
  route('route'),
  path('path');
  const RelativeRoutingType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static RelativeRoutingType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown RelativeRoutingType'),
  );
}

/// Typed props for `FutureConfig`.
///
/// v7_relativeSplatPath?: boolean; v7_startTransition?: boolean
class FutureConfig {
  const FutureConfig({
    bool? this.v7_relativeSplatPath,
    bool? this.v7_startTransition,
  });

  /// TS: boolean
  final bool? v7_relativeSplatPath;

  /// TS: boolean
  final bool? v7_startTransition;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (v7_relativeSplatPath != null) 'v7_relativeSplatPath': v7_relativeSplatPath,
    if (v7_startTransition != null) 'v7_startTransition': v7_startTransition,
  };
}

/// Typed props for `Navigator`.
///
/// createHref: (to: any) => string
/// encodeLocation?: (to: any) => { pathname: string; search: string; hash: string }
/// go: (delta: number) => void
/// push: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
/// replace: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
class Navigator {
  const Navigator({
    required RouterNavigatorCreateHrefCallback this.createHref,
    RouterNavigatorEncodeLocationCallback? this.encodeLocation,
    required RouterNavigatorGoCallback this.go,
    required RouterNavigatorPushCallback this.push,
    required RouterNavigatorPushCallback this.replace,
  });

  /// TS: (to: any) => string
  final RouterNavigatorCreateHrefCallback createHref;

  /// TS: (to: any) => { pathname: string; search: string; hash: string }
  final RouterNavigatorEncodeLocationCallback? encodeLocation;

  /// TS: (delta: number) => void
  final RouterNavigatorGoCallback go;

  /// TS: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
  final RouterNavigatorPushCallback push;

  /// TS: (to: any, state: any, opts: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
  final RouterNavigatorPushCallback replace;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    'createHref': createHref,
    if (encodeLocation != null) 'encodeLocation': encodeLocation,
    'go': go,
    'push': push,
    'replace': replace,
  };
}

/// Typed props for `Pick`.
///
/// value?: any
class Pick {
  const Pick({
    Object? this.value,
  });

  /// TS: any
  final Object? value;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (value != null) 'value': value,
  };
}

/// Typed props for `RouteMatch`.
///
/// params: unknown; pathname: string; pathnameBase: string; route: any
class RouteMatch {
  const RouteMatch({
    required Object? this.params,
    required String this.pathname,
    required String this.pathnameBase,
    required Object this.route,
  });

  /// TS: unknown
  final Object? params;

  /// TS: string
  final String pathname;

  /// TS: string
  final String pathnameBase;

  /// TS: any
  final Object route;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    'params': params,
    'pathname': pathname,
    'pathnameBase': pathnameBase,
    'route': route,
  };
}

