// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom BrowserRouter MemoryRouter Routes Route Link NavLink Outlet Navigate useHref useInRouterContext useLocation useNavigate useNavigationType useOutlet useParams useSearchParams useMatches useNavigation useRevalidator useResolvedPath useRouteError useRouteLoaderData useRoutes useBlocker useFetcher useFetchers useFormAction useLinkClickHandler useLoaderData useSubmit useActionData useOutletContext useAsyncValue useAsyncError --hooks
// Source: react-router-dom
// (extracted from /run/media/kingwill101/disk2/code/code/dart_packages/react_workspace/.dart_tool/react/js/node_modules/react-router-dom/./dist/index.d.ts)
// ignore_for_file: type=lint

import 'dart:js_interop';
import 'react_router_bindings.g.dart';

// Hook bindings for `react-router-dom`. Each hook is only available
// in JavaScript targets (browser client and Node SSR worker);
// it calls into the shim bridge (`globalThis.__reactDartHooks`)
// and runs inside React's render call stack.
//
// Hooks are scoped under `globalThis.__reactDartBindings.reactRouter`
// so multiple wrappers can coexist without collisions.

// Shared decode helpers: the shim returns primitives or `[[key, value],
// ...]` pairs (recursively converted by `toPairs`), and these reshape them
// into typed Dart values.
Map<String, JSAny?> _pairsMap(JSArray pairs) {
  final map = <String, JSAny?>{};
  for (var i = 0; i < pairs.length; i++) {
    final pair = pairs[i] as JSArray;
    var value = pair[1];
    if (value == null || value.isUndefined == true) value = null;
    map[(pair[0] as JSString).toDart] = value;
  }
  return map;
}

Map<String, String> _decodePairs(JSArray pairs) {
  final result = <String, String>{};
  for (var i = 0; i < pairs.length; i++) {
    final pair = pairs[i] as JSArray;
    final value = pair[1];
    result[(pair[0] as JSString).toDart] =
        value == null || value.isUndefined == true
            ? ''
            : (value as JSString).toDart;
  }
  return result;
}

List<T> _decodeList<T>(JSArray raw, T Function(JSAny? item) decode) {
  final result = <T>[];
  for (var i = 0; i < raw.length; i++) {
    result.add(decode(raw[i]));
  }
  return result;
}
/// useHref(to: any, arg?: { relative?: "route" | "path" }) => string
///
/// See https://reactrouter.com/hooks/href.
@JS('globalThis.__reactDartBindings.reactRouter.useHref')
external JSString _useHrefRaw(JSAny? a0, JSAny? a1);

String useHref(Object? to, {RelativeRoutingType? relative}) {
  final options = <String, Object?>{if (relative != null) 'relative': relative.value};
  return _useHrefRaw(to.jsify(), options.jsify()).toDart;
}

/// useInRouterContext() => boolean
///
/// See https://reactrouter.com/hooks/inroutercontext.
@JS('globalThis.__reactDartBindings.reactRouter.useInRouterContext')
external JSBoolean _useInRouterContextRaw();

bool useInRouterContext() {
  return _useInRouterContextRaw().toDart;
}

/// useLocation() => { pathname: string; search: string; hash: string; state: any; key: string }
///
/// See https://reactrouter.com/hooks/location.
@JS('globalThis.__reactDartBindings.reactRouter.useLocation')
external JSArray _useLocationRaw();

Location useLocation() {
  return Location.fromParts(_useLocationRaw());
}

/// useNavigate() => (to: any, options: { replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_flushSync?: boolean; unstable_viewTransition?: boolean }) => void
///
/// See https://reactrouter.com/hooks/navigate.
@JS('globalThis.__reactDartBindings.reactRouter.useNavigate')
external JSFunction _useNavigateRaw();

void Function(Object? to, {bool? replace, Object? state, bool? preventScrollReset, RelativeRoutingType? relative, bool? unstable_flushSync, bool? unstable_viewTransition}) useNavigate() {
  final fn = _useNavigateRaw();
  return (Object? to, {bool? replace, Object? state, bool? preventScrollReset, RelativeRoutingType? relative, bool? unstable_flushSync, bool? unstable_viewTransition}) { fn.callAsFunction(null, to.jsify(), <String, Object?>{if (replace != null) 'replace': replace, if (state != null) 'state': state, if (preventScrollReset != null) 'preventScrollReset': preventScrollReset, if (relative != null) 'relative': relative.value, if (unstable_flushSync != null) 'unstable_flushSync': unstable_flushSync, if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition}.jsify()); };
}

/// useNavigationType() => "POP" | "PUSH" | "REPLACE"
///
/// See https://reactrouter.com/hooks/navigationtype.
@JS('globalThis.__reactDartBindings.reactRouter.useNavigationType')
external JSString _useNavigationTypeRaw();

NavigationType useNavigationType() {
  return NavigationType.fromValue(_useNavigationTypeRaw().toDart);
}

/// useOutlet(context?: unknown) => any
///
/// See https://reactrouter.com/hooks/outlet.
@JS('globalThis.__reactDartBindings.reactRouter.useOutlet')
external JSAny? _useOutletRaw(JSAny? a0);

Object? useOutlet([Object? context]) {
  return _useOutletRaw(context.jsify());
}

/// useParams() => unknown
///
/// See https://reactrouter.com/hooks/params.
@JS('globalThis.__reactDartBindings.reactRouter.useParams')
external JSArray _useParamsRaw();

Map<String, String> useParams() {
  return _decodePairs(_useParamsRaw());
}

/// useSearchParams(defaultInit?: any) => unknown
///
/// See https://reactrouter.com/hooks/searchparams.
@JS('globalThis.__reactDartBindings.reactRouter.useSearchParams')
external JSArray _useSearchParamsRaw(JSAny? a0);

(Map<String, String>, void Function(Object? nextInit, {bool? replace, Object? state, bool? preventScrollReset, RelativeRoutingType? relative, bool? unstable_flushSync, bool? unstable_viewTransition})) useSearchParams([Object? defaultInit]) {
  final raw = _useSearchParamsRaw(defaultInit.jsify());
  return (_decodePairs(raw[0] as JSArray), (Object? nextInit, {bool? replace, Object? state, bool? preventScrollReset, RelativeRoutingType? relative, bool? unstable_flushSync, bool? unstable_viewTransition}) { (raw[1] as JSFunction).callAsFunction(null, nextInit.jsify(), <String, Object?>{if (replace != null) 'replace': replace, if (state != null) 'state': state, if (preventScrollReset != null) 'preventScrollReset': preventScrollReset, if (relative != null) 'relative': relative.value, if (unstable_flushSync != null) 'unstable_flushSync': unstable_flushSync, if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition}.jsify()); });
}

/// useMatches() => { id: string; pathname: string; params: unknown; data: any; handle: any }[]
///
/// See https://reactrouter.com/hooks/matches.
@JS('globalThis.__reactDartBindings.reactRouter.useMatches')
external JSArray _useMatchesRaw();

List<UIMatch> useMatches() {
  return _decodeList(_useMatchesRaw(), (e) => UIMatch.fromParts(e as JSArray));
}

/// useNavigation() => { state: "idle" | "loading" | "submitting"; location: { pathname: string; search: string; hash: string; state: any; key: string }; formMethod: Record<string, unknown>; formAction: string; formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; formData: any; json: Record<string, unknown>; text: string }
///
/// See https://reactrouter.com/hooks/navigation.
@JS('globalThis.__reactDartBindings.reactRouter.useNavigation')
external JSArray _useNavigationRaw();

NavigationReturn useNavigation() {
  return NavigationReturn.fromParts(_useNavigationRaw());
}

/// useRevalidator() => { revalidate: () => void; state: "idle" | "loading" }
///
/// See https://reactrouter.com/hooks/revalidator.
@JS('globalThis.__reactDartBindings.reactRouter.useRevalidator')
external JSArray _useRevalidatorRaw();

RevalidatorReturn useRevalidator() {
  return RevalidatorReturn.fromParts(_useRevalidatorRaw());
}

/// useResolvedPath(to: any, arg?: { relative?: "route" | "path" }) => { pathname: string; search: string; hash: string }
///
/// See https://reactrouter.com/hooks/resolvedpath.
@JS('globalThis.__reactDartBindings.reactRouter.useResolvedPath')
external JSArray _useResolvedPathRaw(JSAny? a0, JSAny? a1);

Path useResolvedPath(Object? to, {RelativeRoutingType? relative}) {
  final options = <String, Object?>{if (relative != null) 'relative': relative.value};
  return Path.fromParts(_useResolvedPathRaw(to.jsify(), options.jsify()));
}

/// useRouteError() => unknown
///
/// See https://reactrouter.com/hooks/routeerror.
@JS('globalThis.__reactDartBindings.reactRouter.useRouteError')
external JSAny? _useRouteErrorRaw();

Object? useRouteError() {
  return _useRouteErrorRaw();
}

/// useRouteLoaderData(routeId: string) => unknown
///
/// See https://reactrouter.com/hooks/routeloaderdata.
@JS('globalThis.__reactDartBindings.reactRouter.useRouteLoaderData')
external JSAny? _useRouteLoaderDataRaw(JSAny? a0);

Object? useRouteLoaderData(String routeId) {
  return _useRouteLoaderDataRaw(routeId.jsify());
}

/// useRoutes(routes: { caseSensitive?: any; path?: any; id?: any; loader?: any; action?: any; hasErrorBoundary?: any; shouldRevalidate?: any; handle?: any; index: true | false; children?: any[]; element?: React.ReactNode; hydrateFallbackElement?: React.ReactNode; errorElement?: React.ReactNode; Component?: any; HydrateFallback?: any; ErrorBoundary?: any; lazy?: () => any }[], locationArg?: any) => any
///
/// See https://reactrouter.com/hooks/routes.
@JS('globalThis.__reactDartBindings.reactRouter.useRoutes')
external JSAny? _useRoutesRaw(JSAny? a0, JSAny? a1);

Object? useRoutes(List<Object?> routes, [Object? locationArg]) {
  return _useRoutesRaw(routes.jsify(), locationArg.jsify());
}

/// useBlocker(shouldBlock: any) => { state: "unblocked" | "blocked" | "proceeding"; reset: () => void; proceed: () => void; location: { pathname: string; search: string; hash: string; state: any; key: string } }
///
/// See https://reactrouter.com/hooks/blocker.
@JS('globalThis.__reactDartBindings.reactRouter.useBlocker')
external JSArray _useBlockerRaw(JSAny? a0);

BlockerReturn useBlocker(Object? shouldBlock) {
  return BlockerReturn.fromParts(_useBlockerRaw(shouldBlock.jsify()));
}

/// useFetcher(arg?: { key?: string }) => { state: "idle" | "loading" | "submitting"; formMethod: Record<string, unknown>; formAction: string; formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; text: string; formData: any; json: Record<string, unknown>; data: any; Form: { method?: Record<string, unknown>; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"; action?: string; relative?: "route" | "path"; preventScrollReset?: boolean; onSubmit?: any }; submit: (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean }) => void; load: (href: string, opts: { unstable_flushSync?: boolean }) => void }
///
/// See https://reactrouter.com/hooks/fetcher.
@JS('globalThis.__reactDartBindings.reactRouter.useFetcher')
external JSArray _useFetcherRaw(JSAny? a0);

FetcherReturn useFetcher({String? elementKey}) {
  final options = <String, Object?>{if (elementKey != null) 'key': elementKey};
  return FetcherReturn.fromParts(_useFetcherRaw(options.jsify()));
}

/// useFetchers() => { state: "idle" | "loading" | "submitting"; formMethod: Record<string, unknown>; formAction: string; formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; text: string; formData: any; json: Record<string, unknown>; data: any; key: string }[]
///
/// See https://reactrouter.com/hooks/fetchers.
@JS('globalThis.__reactDartBindings.reactRouter.useFetchers')
external JSArray _useFetchersRaw();

List<FetchersReturnElement> useFetchers() {
  return _decodeList(_useFetchersRaw(), (e) => FetchersReturnElement.fromParts(e as JSArray));
}

/// useFormAction(action?: string, arg?: { relative?: "route" | "path" }) => string
///
/// See https://reactrouter.com/hooks/formaction.
@JS('globalThis.__reactDartBindings.reactRouter.useFormAction')
external JSString _useFormActionRaw(JSAny? a0, JSAny? a1);

String useFormAction(String? action, {RelativeRoutingType? relative}) {
  final options = <String, Object?>{if (relative != null) 'relative': relative.value};
  return _useFormActionRaw(action.jsify(), options.jsify()).toDart;
}

/// useLinkClickHandler(to: any, arg?: { target?: any; replace?: boolean; state?: any; preventScrollReset?: boolean; relative?: "route" | "path"; unstable_viewTransition?: boolean }) => (event: host value) => void
///
/// See https://reactrouter.com/hooks/linkclickhandler.
@JS('globalThis.__reactDartBindings.reactRouter.useLinkClickHandler')
external JSFunction _useLinkClickHandlerRaw(JSAny? a0, JSAny? a1);

void Function(Object? event) useLinkClickHandler(Object? to, {Object? target, bool? replace, Object? state, bool? preventScrollReset, RelativeRoutingType? relative, bool? unstable_viewTransition}) {
  final options = <String, Object?>{if (target != null) 'target': target, if (replace != null) 'replace': replace, if (state != null) 'state': state, if (preventScrollReset != null) 'preventScrollReset': preventScrollReset, if (relative != null) 'relative': relative.value, if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition};
  final fn = _useLinkClickHandlerRaw(to.jsify(), options.jsify());
  return (Object? event) { fn.callAsFunction(null, event.jsify()); };
}

/// useLoaderData() => unknown
///
/// See https://reactrouter.com/hooks/loaderdata.
@JS('globalThis.__reactDartBindings.reactRouter.useLoaderData')
external JSAny? _useLoaderDataRaw();

Object? useLoaderData() {
  return _useLoaderDataRaw();
}

/// useSubmit() => (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean; replace?: boolean; state?: any; fetcherKey?: string; navigate?: boolean; unstable_viewTransition?: boolean }) => void
///
/// See https://reactrouter.com/hooks/submit.
@JS('globalThis.__reactDartBindings.reactRouter.useSubmit')
external JSFunction _useSubmitRaw();

void Function(Object? target, {Object? method, String? action, FormEncType? encType, RelativeRoutingType? relative, bool? preventScrollReset, bool? unstable_flushSync, bool? replace, Object? state, String? fetcherKey, bool? navigate, bool? unstable_viewTransition}) useSubmit() {
  final fn = _useSubmitRaw();
  return (Object? target, {Object? method, String? action, FormEncType? encType, RelativeRoutingType? relative, bool? preventScrollReset, bool? unstable_flushSync, bool? replace, Object? state, String? fetcherKey, bool? navigate, bool? unstable_viewTransition}) { fn.callAsFunction(null, target.jsify(), <String, Object?>{if (method != null) 'method': method, if (action != null) 'action': action, if (encType != null) 'encType': encType.value, if (relative != null) 'relative': relative.value, if (preventScrollReset != null) 'preventScrollReset': preventScrollReset, if (unstable_flushSync != null) 'unstable_flushSync': unstable_flushSync, if (replace != null) 'replace': replace, if (state != null) 'state': state, if (fetcherKey != null) 'fetcherKey': fetcherKey, if (navigate != null) 'navigate': navigate, if (unstable_viewTransition != null) 'unstable_viewTransition': unstable_viewTransition}.jsify()); };
}

/// useActionData() => unknown
///
/// See https://reactrouter.com/hooks/actiondata.
@JS('globalThis.__reactDartBindings.reactRouter.useActionData')
external JSAny? _useActionDataRaw();

Object? useActionData() {
  return _useActionDataRaw();
}

/// useOutletContext() => any
///
/// See https://reactrouter.com/hooks/outletcontext.
@JS('globalThis.__reactDartBindings.reactRouter.useOutletContext')
external JSAny? _useOutletContextRaw();

Object? useOutletContext() {
  return _useOutletContextRaw();
}

/// useAsyncValue() => unknown
///
/// See https://reactrouter.com/hooks/asyncvalue.
@JS('globalThis.__reactDartBindings.reactRouter.useAsyncValue')
external JSAny? _useAsyncValueRaw();

Object? useAsyncValue() {
  return _useAsyncValueRaw();
}

/// useAsyncError() => unknown
///
/// See https://reactrouter.com/hooks/asyncerror.
@JS('globalThis.__reactDartBindings.reactRouter.useAsyncError')
external JSAny? _useAsyncErrorRaw();

Object? useAsyncError() {
  return _useAsyncErrorRaw();
}

/// Value class for `BlockerReturn` (decoded from the hook shim).
///
/// state: "unblocked" | "blocked" | "proceeding"; reset: () => void
/// proceed: () => void
/// location: { pathname: string; search: string; hash: string; state: any; key: string }
final class BlockerReturn {
  const BlockerReturn({
    required BlockerReturnState this.state,
    required void Function() this.reset,
    required void Function() this.proceed,
    required Location this.location,
  });

  /// Decodes the shim's `[[key, value], ...]` pairs.
  factory BlockerReturn.fromParts(JSArray pairs) {
    final map = _pairsMap(pairs);
    final _preset = map['reset']! as JSFunction;
    final _pproceed = map['proceed']! as JSFunction;
    return BlockerReturn(
      state: BlockerReturnState.fromValue((map['state']! as JSString).toDart),
      reset: () { _preset.callAsFunction(null); },
      proceed: () { _pproceed.callAsFunction(null); },
      location: Location.fromParts(map['location']! as JSArray),
    );
  }

  /// TS: "unblocked" | "blocked" | "proceeding"
  final BlockerReturnState state;

  /// TS: () => void
  final void Function() reset;

  /// TS: () => void
  final void Function() proceed;

  /// TS: { pathname: string; search: string; hash: string; state: any; key: string }
  final Location location;
}

/// Value class for `FetcherReturn` (decoded from the hook shim).
///
/// state: "idle" | "loading" | "submitting"
/// formMethod: Record<string, unknown>; formAction: string
/// formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
/// text: string; formData: any; json: Record<string, unknown>; data: any
/// Form: { method?: Record<string, unknown>; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"; action?: string; relative?: "route" | "path"; preventScrollReset?: boolean; onSubmit?: any }
/// submit: (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean }) => void
/// load: (href: string, opts: { unstable_flushSync?: boolean }) => void
final class FetcherReturn {
  const FetcherReturn({
    required NavigationReturnState this.state,
    required Object? this.formMethod,
    required String this.formAction,
    required FormEncType this.formEncType,
    required String this.text,
    required Object? this.formData,
    required Object? this.json,
    required Object? this.data,
    required FetcherReturnForm this.Form,
    required void Function(Object? target, {Object? method, String? action, FormEncType? encType, RelativeRoutingType? relative, bool? preventScrollReset, bool? unstable_flushSync}) this.submit,
    required void Function(String href, {bool? unstable_flushSync}) this.load,
  });

  /// Decodes the shim's `[[key, value], ...]` pairs.
  factory FetcherReturn.fromParts(JSArray pairs) {
    final map = _pairsMap(pairs);
    final _psubmit = map['submit']! as JSFunction;
    final _pload = map['load']! as JSFunction;
    return FetcherReturn(
      state: NavigationReturnState.fromValue((map['state']! as JSString).toDart),
      formMethod: map['formMethod']!,
      formAction: (map['formAction']! as JSString).toDart,
      formEncType: FormEncType.fromValue((map['formEncType']! as JSString).toDart),
      text: (map['text']! as JSString).toDart,
      formData: map['formData']!,
      json: map['json']!,
      data: map['data']!,
      Form: FetcherReturnForm.fromParts(map['Form']! as JSArray),
      submit: (Object? target, {Object? method, String? action, FormEncType? encType, RelativeRoutingType? relative, bool? preventScrollReset, bool? unstable_flushSync}) { _psubmit.callAsFunction(null, target.jsify(), <String, Object?>{if (method != null) 'method': method, if (action != null) 'action': action, if (encType != null) 'encType': encType.value, if (relative != null) 'relative': relative.value, if (preventScrollReset != null) 'preventScrollReset': preventScrollReset, if (unstable_flushSync != null) 'unstable_flushSync': unstable_flushSync}.jsify()); },
      load: (String href, {bool? unstable_flushSync}) { _pload.callAsFunction(null, href.toJS, <String, Object?>{if (unstable_flushSync != null) 'unstable_flushSync': unstable_flushSync}.jsify()); },
    );
  }

  /// TS: "idle" | "loading" | "submitting"
  final NavigationReturnState state;

  /// TS: Record<string, unknown>
  final Object? formMethod;

  /// TS: string
  final String formAction;

  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
  final FormEncType formEncType;

  /// TS: string
  final String text;

  /// TS: any
  final Object? formData;

  /// TS: Record<string, unknown>
  final Object? json;

  /// TS: any
  final Object? data;

  /// TS: { method?: Record<string, unknown>; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"; action?: string; relative?: "route" | "path"; preventScrollReset?: boolean; onSubmit?: any }
  final FetcherReturnForm Form;

  /// TS: (target: any, options: { method?: Record<string, unknown>; action?: string; encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"; relative?: "route" | "path"; preventScrollReset?: boolean; unstable_flushSync?: boolean }) => void
  final void Function(Object? target, {Object? method, String? action, FormEncType? encType, RelativeRoutingType? relative, bool? preventScrollReset, bool? unstable_flushSync}) submit;

  /// TS: (href: string, opts: { unstable_flushSync?: boolean }) => void
  final void Function(String href, {bool? unstable_flushSync}) load;
}

/// Value class for `FetcherReturnForm` (decoded from the hook shim).
///
/// method?: Record<string, unknown>
/// encType?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
/// action?: string; relative?: "route" | "path"; preventScrollReset?: boolean
/// onSubmit?: any
final class FetcherReturnForm {
  const FetcherReturnForm({
    Object? this.method,
    FetcherReturnFormEncType? this.encType,
    String? this.action,
    RelativeRoutingType? this.relative,
    bool? this.preventScrollReset,
    Object? this.onSubmit,
  });

  /// Decodes the shim's `[[key, value], ...]` pairs.
  factory FetcherReturnForm.fromParts(JSArray pairs) {
    final map = _pairsMap(pairs);
    return FetcherReturnForm(
      method: map['method'] == null ? null : map['method']!,
      encType: map['encType'] == null ? null : FetcherReturnFormEncType.fromValue((map['encType']! as JSString).toDart),
      action: map['action'] == null ? null : (map['action']! as JSString).toDart,
      relative: map['relative'] == null ? null : RelativeRoutingType.fromValue((map['relative']! as JSString).toDart),
      preventScrollReset: map['preventScrollReset'] == null ? null : (map['preventScrollReset']! as JSBoolean).toDart,
      onSubmit: map['onSubmit'] == null ? null : map['onSubmit']!,
    );
  }

  /// TS: Record<string, unknown>
  final Object? method;

  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
  final FetcherReturnFormEncType? encType;

  /// TS: string
  final String? action;

  /// TS: "route" | "path"
  final RelativeRoutingType? relative;

  /// TS: boolean
  final bool? preventScrollReset;

  /// TS: any
  final Object? onSubmit;
}

/// Value class for `FetchersReturnElement` (decoded from the hook shim).
///
/// state: "idle" | "loading" | "submitting"
/// formMethod: Record<string, unknown>; formAction: string
/// formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
/// text: string; formData: any; json: Record<string, unknown>; data: any
/// key: string
final class FetchersReturnElement {
  const FetchersReturnElement({
    required NavigationReturnState this.state,
    required Object? this.formMethod,
    required String this.formAction,
    required FormEncType this.formEncType,
    required String this.text,
    required Object? this.formData,
    required Object? this.json,
    required Object? this.data,
    required String this.elementKey,
  });

  /// Decodes the shim's `[[key, value], ...]` pairs.
  factory FetchersReturnElement.fromParts(JSArray pairs) {
    final map = _pairsMap(pairs);
    return FetchersReturnElement(
      state: NavigationReturnState.fromValue((map['state']! as JSString).toDart),
      formMethod: map['formMethod']!,
      formAction: (map['formAction']! as JSString).toDart,
      formEncType: FormEncType.fromValue((map['formEncType']! as JSString).toDart),
      text: (map['text']! as JSString).toDart,
      formData: map['formData']!,
      json: map['json']!,
      data: map['data']!,
      elementKey: (map['key']! as JSString).toDart,
    );
  }

  /// TS: "idle" | "loading" | "submitting"
  final NavigationReturnState state;

  /// TS: Record<string, unknown>
  final Object? formMethod;

  /// TS: string
  final String formAction;

  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
  final FormEncType formEncType;

  /// TS: string
  final String text;

  /// TS: any
  final Object? formData;

  /// TS: Record<string, unknown>
  final Object? json;

  /// TS: any
  final Object? data;

  /// TS: string
  final String elementKey;
}

/// Value class for `Location` (decoded from the hook shim).
///
/// pathname: string; search: string; hash: string; state: any; key: string
final class Location {
  const Location({
    required String this.pathname,
    required String this.search,
    required String this.hash,
    required Object? this.state,
    required String this.elementKey,
  });

  /// Decodes the shim's `[[key, value], ...]` pairs.
  factory Location.fromParts(JSArray pairs) {
    final map = _pairsMap(pairs);
    return Location(
      pathname: (map['pathname']! as JSString).toDart,
      search: (map['search']! as JSString).toDart,
      hash: (map['hash']! as JSString).toDart,
      state: map['state']!,
      elementKey: (map['key']! as JSString).toDart,
    );
  }

  /// TS: string
  final String pathname;

  /// TS: string
  final String search;

  /// TS: string
  final String hash;

  /// TS: any
  final Object? state;

  /// TS: string
  final String elementKey;

  /// The full path including the query string.
  String get fullPath => '$pathname$search$hash';

  @override
  String toString() => fullPath;
}

/// Value class for `NavigationReturn` (decoded from the hook shim).
///
/// state: "idle" | "loading" | "submitting"
/// location: { pathname: string; search: string; hash: string; state: any; key: string }
/// formMethod: Record<string, unknown>; formAction: string
/// formEncType: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
/// formData: any; json: Record<string, unknown>; text: string
final class NavigationReturn {
  const NavigationReturn({
    required NavigationReturnState this.state,
    required Location this.location,
    required Object? this.formMethod,
    required String this.formAction,
    required FormEncType this.formEncType,
    required Object? this.formData,
    required Object? this.json,
    required String this.text,
  });

  /// Decodes the shim's `[[key, value], ...]` pairs.
  factory NavigationReturn.fromParts(JSArray pairs) {
    final map = _pairsMap(pairs);
    return NavigationReturn(
      state: NavigationReturnState.fromValue((map['state']! as JSString).toDart),
      location: Location.fromParts(map['location']! as JSArray),
      formMethod: map['formMethod']!,
      formAction: (map['formAction']! as JSString).toDart,
      formEncType: FormEncType.fromValue((map['formEncType']! as JSString).toDart),
      formData: map['formData']!,
      json: map['json']!,
      text: (map['text']! as JSString).toDart,
    );
  }

  /// TS: "idle" | "loading" | "submitting"
  final NavigationReturnState state;

  /// TS: { pathname: string; search: string; hash: string; state: any; key: string }
  final Location location;

  /// TS: Record<string, unknown>
  final Object? formMethod;

  /// TS: string
  final String formAction;

  /// TS: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
  final FormEncType formEncType;

  /// TS: any
  final Object? formData;

  /// TS: Record<string, unknown>
  final Object? json;

  /// TS: string
  final String text;
}

/// Value class for `Path` (decoded from the hook shim).
///
/// pathname: string; search: string; hash: string
final class Path {
  const Path({
    required String this.pathname,
    required String this.search,
    required String this.hash,
  });

  /// Decodes the shim's `[[key, value], ...]` pairs.
  factory Path.fromParts(JSArray pairs) {
    final map = _pairsMap(pairs);
    return Path(
      pathname: (map['pathname']! as JSString).toDart,
      search: (map['search']! as JSString).toDart,
      hash: (map['hash']! as JSString).toDart,
    );
  }

  /// TS: string
  final String pathname;

  /// TS: string
  final String search;

  /// TS: string
  final String hash;
}

/// Value class for `RevalidatorReturn` (decoded from the hook shim).
///
/// revalidate: () => void; state: "idle" | "loading"
final class RevalidatorReturn {
  const RevalidatorReturn({
    required void Function() this.revalidate,
    required RevalidationState this.state,
  });

  /// Decodes the shim's `[[key, value], ...]` pairs.
  factory RevalidatorReturn.fromParts(JSArray pairs) {
    final map = _pairsMap(pairs);
    final _prevalidate = map['revalidate']! as JSFunction;
    return RevalidatorReturn(
      revalidate: () { _prevalidate.callAsFunction(null); },
      state: RevalidationState.fromValue((map['state']! as JSString).toDart),
    );
  }

  /// TS: () => void
  final void Function() revalidate;

  /// TS: "idle" | "loading"
  final RevalidationState state;
}

/// Value class for `UIMatch` (decoded from the hook shim).
///
/// id: string; pathname: string; params: unknown; data: any; handle: any
final class UIMatch {
  const UIMatch({
    required String this.id,
    required String this.pathname,
    required Map<String, String> this.params,
    required Object? this.data,
    required Object? this.handle,
  });

  /// Decodes the shim's `[[key, value], ...]` pairs.
  factory UIMatch.fromParts(JSArray pairs) {
    final map = _pairsMap(pairs);
    return UIMatch(
      id: (map['id']! as JSString).toDart,
      pathname: (map['pathname']! as JSString).toDart,
      params: _decodePairs(map['params']! as JSArray),
      data: map['data']!,
      handle: map['handle']!,
    );
  }

  /// TS: string
  final String id;

  /// TS: string
  final String pathname;

  /// TS: unknown
  final Map<String, String> params;

  /// TS: any
  final Object? data;

  /// TS: any
  final Object? handle;
}

/// Literal union: "unblocked" | "blocked" | "proceeding"
enum BlockerReturnState {
  unblocked('unblocked'),
  blocked('blocked'),
  proceeding('proceeding');
  const BlockerReturnState(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static BlockerReturnState fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown BlockerReturnState'),
  );
}

/// Literal union: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain"
enum FetcherReturnFormEncType {
  applicationXWwwFormUrlencoded('application/x-www-form-urlencoded'),
  multipartFormData('multipart/form-data'),
  textPlain('text/plain');
  const FetcherReturnFormEncType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static FetcherReturnFormEncType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown FetcherReturnFormEncType'),
  );
}

/// Literal union: "application/x-www-form-urlencoded" | "multipart/form-data" | "application/json" | "text/plain"
enum FormEncType {
  applicationXWwwFormUrlencoded('application/x-www-form-urlencoded'),
  multipartFormData('multipart/form-data'),
  applicationJson('application/json'),
  textPlain('text/plain');
  const FormEncType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static FormEncType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown FormEncType'),
  );
}

/// Literal union: "idle" | "loading" | "submitting"
enum NavigationReturnState {
  idle('idle'),
  loading('loading'),
  submitting('submitting');
  const NavigationReturnState(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static NavigationReturnState fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown NavigationReturnState'),
  );
}

/// Literal union: "POP" | "PUSH" | "REPLACE"
enum NavigationType {
  pop('POP'),
  push('PUSH'),
  replace('REPLACE');
  const NavigationType(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static NavigationType fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown NavigationType'),
  );
}

/// Literal union: "idle" | "loading"
enum RevalidationState {
  idle('idle'),
  loading('loading');
  const RevalidationState(this.value);
  final String value;

  /// Decodes a JS string value into this enum.
  static RevalidationState fromValue(String value) => values.firstWhere(
    (e) => e.value == value,
    orElse: () => throw ArgumentError.value(value, 'value', 'Unknown RevalidationState'),
  );
}

