// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom  --shim
//
// Registers the bound `react-router-dom` components under the
// `reactRouter.*` names used by the generated Dart helpers.
// Wire this module into react.yaml under `foreign.modules`.

import { RouterProvider as __reactDartRouterProvider, BrowserRouter as __reactDartBrowserRouter, HashRouter as __reactDartHashRouter, Link as __reactDartLink, NavLink as __reactDartNavLink, Form as __reactDartForm, ScrollRestoration as __reactDartScrollRestoration, MemoryRouter as __reactDartMemoryRouter, Navigate as __reactDartNavigate, Outlet as __reactDartOutlet, Route as __reactDartRoute, Router as __reactDartRouter, Routes as __reactDartRoutes, Await as __reactDartAwait, renderMatches as __reactDartRenderMatches, useLinkClickHandler as __reactDartUseLinkClickHandler, useSearchParams as __reactDartUseSearchParams, useSubmit as __reactDartUseSubmit, useFormAction as __reactDartUseFormAction, useFetcher as __reactDartUseFetcher, useFetchers as __reactDartUseFetchers, useBeforeUnload as __reactDartUseBeforeUnload, useHref as __reactDartUseHref, useInRouterContext as __reactDartUseInRouterContext, useLocation as __reactDartUseLocation, useNavigationType as __reactDartUseNavigationType, useMatch as __reactDartUseMatch, useNavigate as __reactDartUseNavigate, useOutletContext as __reactDartUseOutletContext, useOutlet as __reactDartUseOutlet, useParams as __reactDartUseParams, useResolvedPath as __reactDartUseResolvedPath, useRoutes as __reactDartUseRoutes, useNavigation as __reactDartUseNavigation, useRevalidator as __reactDartUseRevalidator, useMatches as __reactDartUseMatches, useLoaderData as __reactDartUseLoaderData, useRouteLoaderData as __reactDartUseRouteLoaderData, useActionData as __reactDartUseActionData, useRouteError as __reactDartUseRouteError, useAsyncValue as __reactDartUseAsyncValue, useAsyncError as __reactDartUseAsyncError, useBlocker as __reactDartUseBlocker } from 'react-router-dom';

const components = {
  'reactRouter.RouterProvider': __reactDartRouterProvider,
  'reactRouter.BrowserRouter': __reactDartBrowserRouter,
  'reactRouter.HashRouter': __reactDartHashRouter,
  'reactRouter.Link': __reactDartLink,
  'reactRouter.NavLink': __reactDartNavLink,
  'reactRouter.Form': __reactDartForm,
  'reactRouter.ScrollRestoration': __reactDartScrollRestoration,
  'reactRouter.MemoryRouter': __reactDartMemoryRouter,
  'reactRouter.Navigate': __reactDartNavigate,
  'reactRouter.Outlet': __reactDartOutlet,
  'reactRouter.Route': __reactDartRoute,
  'reactRouter.Router': __reactDartRouter,
  'reactRouter.Routes': __reactDartRoutes,
  'reactRouter.Await': __reactDartAwait,
  'reactRouter.renderMatches': __reactDartRenderMatches,
};

for (const [name, component] of Object.entries(components)) {
  globalThis.__reactDartRegisterComponent?.(name, component);
}

// Hook bridge: the generated Dart hooks (`--hooks` output) call
// these members during render. Results are decoded into
// primitives or `[[key, value], ...]` pairs (via `toPairs`)
// because dart2js cannot cast a raw callAsFunction result.
const toPairs = (v) => {
  if (v == null) return v;
  if (Array.isArray(v)) return v.map(toPairs);
  if (typeof v === 'object') {
    if (typeof v.entries === 'function') return [...v.entries()];
    return Object.entries(v).map(([k, val]) => [k, toPairs(val)]);
  }
  return v;
};

const hooks = {
  useLinkClickHandler: (a0, a1) => (() => { const as = [a0, a1]; while (as.length && as[as.length - 1] == null) as.pop(); return __reactDartUseLinkClickHandler(...as); })(),
  useSearchParams: (a0) => { const v = (() => { const as = [a0]; while (as.length && as[as.length - 1] == null) as.pop(); return __reactDartUseSearchParams(...as); })(); return [toPairs(v[0]), v[1]]; },
  useSubmit: () => __reactDartUseSubmit(),
  useFormAction: (a0, a1) => (() => { const as = [a0, a1]; while (as.length && as[as.length - 1] == null) as.pop(); return __reactDartUseFormAction(...as); })(),
  useFetcher: (a0) => { const v = (() => { const as = [a0]; while (as.length && as[as.length - 1] == null) as.pop(); return __reactDartUseFetcher(...as); })(); return v; },
  useFetchers: () => { const v = __reactDartUseFetchers(); return (v ?? []).map((x) => x); },
  useBeforeUnload: (a0, a1) => (() => { const as = [a0, a1]; while (as.length && as[as.length - 1] == null) as.pop(); return __reactDartUseBeforeUnload(...as); })(),
  useHref: (a0, a1) => (() => { const as = [a0, a1]; while (as.length && as[as.length - 1] == null) as.pop(); return __reactDartUseHref(...as); })(),
  useInRouterContext: () => __reactDartUseInRouterContext(),
  useLocation: () => { const v = __reactDartUseLocation(); return v; },
  useNavigationType: () => __reactDartUseNavigationType(),
  useMatch: (a0) => { const v = __reactDartUseMatch(a0); return v; },
  useNavigate: () => __reactDartUseNavigate(),
  useOutletContext: () => __reactDartUseOutletContext(),
  useOutlet: (a0) => (() => { const as = [a0]; while (as.length && as[as.length - 1] == null) as.pop(); return __reactDartUseOutlet(...as); })(),
  useParams: () => { const v = __reactDartUseParams(); return toPairs(v ?? {}); },
  useResolvedPath: (a0, a1) => { const v = (() => { const as = [a0, a1]; while (as.length && as[as.length - 1] == null) as.pop(); return __reactDartUseResolvedPath(...as); })(); return v; },
  useRoutes: (a0, a1) => (() => { const as = [a0, a1]; while (as.length && as[as.length - 1] == null) as.pop(); return __reactDartUseRoutes(...as); })(),
  useNavigation: () => { const v = __reactDartUseNavigation(); return v; },
  useRevalidator: () => { const v = __reactDartUseRevalidator(); return v; },
  useMatches: () => { const v = __reactDartUseMatches(); return (v ?? []).map((x) => x); },
  useLoaderData: () => __reactDartUseLoaderData(),
  useRouteLoaderData: (a0) => __reactDartUseRouteLoaderData(a0),
  useActionData: () => __reactDartUseActionData(),
  useRouteError: () => __reactDartUseRouteError(),
  useAsyncValue: () => __reactDartUseAsyncValue(),
  useAsyncError: () => __reactDartUseAsyncError(),
  useBlocker: (a0) => { const v = __reactDartUseBlocker(a0); return v; },
};

globalThis.__reactDartBindings ??= Object.create(null);
globalThis.__reactDartBindings.reactRouter = hooks;

