name: client
resolution: workspace
description: A React Dart application (client-only).
publish_to: none

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  react_core: ^0.1.0
  react_js: ^0.1.0
  react_dom: ^0.1.0
  react_web: ^0.1.0
  react_actions: ^0.1.0

dev_dependencies:
  build_runner: ^2.15.3
  react_codegen: ^0.1.0
  react_tool: ^0.2.0
  lints: ^6.1.0
  react_testing: ^0.1.0
  server_testing: ^0.4.0
  server_testing_shelf: ^0.4.0
  test: ^1.31.2
