// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom MemoryRouter Route NavigateProps
// Source: react-router-dom
// (extracted from /run/media/kingwill101/disk2/code/code/dart_packages/react_workspace/.dart_tool/react/js/node_modules/react-router-dom/./dist/index.d.ts)
// ignore_for_file: type=lint

import 'package:react/react.dart';

/// Typed helper for the `reactRouterDom.MemoryRouter` foreign component.
///
/// Props from `MemoryRouter`:
///
/// future?: { v7_startTransition?: boolean; v7_relativeSplatPath?: boolean }
/// initialEntries?: any[]; basename?: string; children?: React.ReactNode
/// initialIndex?: number
ReactNode reactRouterDomMemoryRouter(
  List<ReactNode> children,
  {
  String? key,
    FutureConfig? future,
    List<Object?>? initialEntries,
    String? basename,
    num? initialIndex,
  }
) => foreignComponent(
  'reactRouterDom.MemoryRouter',
  key: key,
  props: {
    if (future != null) 'future': future.toJson(),
    if (initialEntries != null) 'initialEntries': initialEntries,
    if (basename != null) 'basename': basename,
    if (initialIndex != null) 'initialIndex': initialIndex,
  },
  children: children,
);

/// Typed helper for the `reactRouterDom.Route` foreign component.
///
/// Props from `Route`:
///
/// caseSensitive?: any; index?: false; errorElement?: React.ReactNode
/// hydrateFallbackElement?: React.ReactNode; Component?: any
/// lazy?: Record<string, unknown>; shouldRevalidate?: any
/// element?: React.ReactNode; action?: any; hasErrorBoundary?: any
/// children?: React.ReactNode; ErrorBoundary?: any; loader?: any; path?: any
/// handle?: any; HydrateFallback?: any; id?: any
ReactNode reactRouterDomRoute(
  List<ReactNode> children,
  {
  String? key,
    Object? caseSensitive,
    bool? index,
    ReactNode? errorElement,
    ReactNode? hydrateFallbackElement,
    Object? Component,
    Object? lazy,
    Object? shouldRevalidate,
    ReactNode? element,
    Object? action,
    Object? hasErrorBoundary,
    Object? ErrorBoundary,
    Object? loader,
    Object? path,
    Object? handle,
    Object? HydrateFallback,
    Object? id,
  }
) => foreignComponent(
  'reactRouterDom.Route',
  key: key,
  props: {
    if (caseSensitive != null) 'caseSensitive': caseSensitive,
    if (index != null) 'index': index,
    if (errorElement != null) 'errorElement': errorElement,
    if (hydrateFallbackElement != null) 'hydrateFallbackElement': hydrateFallbackElement,
    if (Component != null) 'Component': Component,
    if (lazy != null) 'lazy': lazy,
    if (shouldRevalidate != null) 'shouldRevalidate': shouldRevalidate,
    if (element != null) 'element': element,
    if (action != null) 'action': action,
    if (hasErrorBoundary != null) 'hasErrorBoundary': hasErrorBoundary,
    if (ErrorBoundary != null) 'ErrorBoundary': ErrorBoundary,
    if (loader != null) 'loader': loader,
    if (path != null) 'path': path,
    if (handle != null) 'handle': handle,
    if (HydrateFallback != null) 'HydrateFallback': HydrateFallback,
    if (id != null) 'id': id,
  },
  children: children,
);


/// Literal union: "route" | "path"
enum NavigatePropsRelative {
  route('"route"'),
  path('"path"');
  const NavigatePropsRelative(this.value);
  final String value;
}

/// Typed props for `FutureConfig`.
///
/// v7_startTransition?: boolean; v7_relativeSplatPath?: boolean
class FutureConfig {
  const FutureConfig({
    bool? this.v7_startTransition,
    bool? this.v7_relativeSplatPath,
  });

  /// TS: boolean
  final bool? v7_startTransition;

  /// TS: boolean
  final bool? v7_relativeSplatPath;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (v7_startTransition != null) 'v7_startTransition': v7_startTransition,
    if (v7_relativeSplatPath != null) 'v7_relativeSplatPath': v7_relativeSplatPath,
  };
}

/// Typed props for `NavigateProps`.
///
/// state?: any; relative?: "route" | "path"; to: any; replace?: boolean
class NavigateProps {
  const NavigateProps({
    Object? this.state,
    NavigatePropsRelative? this.relative,
    required Object this.to,
    bool? this.replace,
  });

  /// TS: any
  final Object? state;

  /// TS: "route" | "path"
  final NavigatePropsRelative? relative;

  /// TS: any
  final Object to;

  /// TS: boolean
  final bool? replace;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (state != null) 'state': state,
    if (relative != null) 'relative': relative!.value,
    'to': to,
    if (replace != null) 'replace': replace,
  };
}

