// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind react-router-dom MemoryRouter Route NavigateProps
// Source: react-router-dom
// (extracted from /run/media/kingwill101/disk2/code/code/dart_packages/react_workspace/.dart_tool/react/js/node_modules/react-router-dom/./dist/index.d.ts)
// ignore_for_file: type=lint

import 'package:react/react.dart';

/// Typed helper for the `reactRouterDom.MemoryRouter` foreign component.
///
/// Props from `MemoryRouter`:
///
/// children?: React.ReactNode; initialEntries?: any[]; basename?: string
/// initialIndex?: number
/// future?: { v7_relativeSplatPath?: boolean; v7_startTransition?: boolean }
ReactNode reactRouterDomMemoryRouter({
  String? key,
  List<ReactNode> children = const [],
    List<Object?>? initialEntries,
    String? basename,
    num? initialIndex,
    FutureConfig? future,
}) => foreignComponent(
  'reactRouterDom.MemoryRouter',
  key: key,
  props: {
    if (initialEntries != null) 'initialEntries': initialEntries,
    if (basename != null) 'basename': basename,
    if (initialIndex != null) 'initialIndex': initialIndex,
    if (future != null) 'future': future.toJson(),
  },
  children: children,
);

/// Typed helper for the `reactRouterDom.Route` foreign component.
///
/// Props from `Route`:
///
/// hasErrorBoundary?: any; errorElement?: React.ReactNode; loader?: any
/// HydrateFallback?: any; Component?: any; lazy?: Record<string, unknown>
/// handle?: any; action?: any; id?: any; path?: any; children?: React.ReactNode
/// shouldRevalidate?: any; element?: React.ReactNode; index?: false
/// caseSensitive?: any; ErrorBoundary?: any
/// hydrateFallbackElement?: React.ReactNode
ReactNode reactRouterDomRoute({
  String? key,
  List<ReactNode> children = const [],
    Object? hasErrorBoundary,
    ReactNode? errorElement,
    Object? loader,
    Object? HydrateFallback,
    Object? Component,
    Object? lazy,
    Object? handle,
    Object? action,
    Object? id,
    Object? path,
    Object? shouldRevalidate,
    ReactNode? element,
    bool? index,
    Object? caseSensitive,
    Object? ErrorBoundary,
    ReactNode? hydrateFallbackElement,
}) => foreignComponent(
  'reactRouterDom.Route',
  key: key,
  props: {
    if (hasErrorBoundary != null) 'hasErrorBoundary': hasErrorBoundary,
    if (errorElement != null) 'errorElement': errorElement,
    if (loader != null) 'loader': loader,
    if (HydrateFallback != null) 'HydrateFallback': HydrateFallback,
    if (Component != null) 'Component': Component,
    if (lazy != null) 'lazy': lazy,
    if (handle != null) 'handle': handle,
    if (action != null) 'action': action,
    if (id != null) 'id': id,
    if (path != null) 'path': path,
    if (shouldRevalidate != null) 'shouldRevalidate': shouldRevalidate,
    if (element != null) 'element': element,
    if (index != null) 'index': index,
    if (caseSensitive != null) 'caseSensitive': caseSensitive,
    if (ErrorBoundary != null) 'ErrorBoundary': ErrorBoundary,
    if (hydrateFallbackElement != null) 'hydrateFallbackElement': hydrateFallbackElement,
  },
  children: children,
);


/// Literal union: "route" | "path"
enum NavigatePropsRelative {
  route('route'),
  path('path');
  const NavigatePropsRelative(this.value);
  final String value;
}

/// Typed props for `FutureConfig`.
///
/// v7_relativeSplatPath?: boolean; v7_startTransition?: boolean
class FutureConfig {
  const FutureConfig({
    bool? this.v7_relativeSplatPath,
    bool? this.v7_startTransition,
  });

  /// TS: boolean
  final bool? v7_relativeSplatPath;

  /// TS: boolean
  final bool? v7_startTransition;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (v7_relativeSplatPath != null) 'v7_relativeSplatPath': v7_relativeSplatPath,
    if (v7_startTransition != null) 'v7_startTransition': v7_startTransition,
  };
}

/// Typed props for `NavigateProps`.
///
/// relative?: "route" | "path"; to: any; replace?: boolean; state?: any
class NavigateProps {
  const NavigateProps({
    NavigatePropsRelative? this.relative,
    required Object this.to,
    bool? this.replace,
    Object? this.state,
  });

  /// TS: "route" | "path"
  final NavigatePropsRelative? relative;

  /// TS: any
  final Object to;

  /// TS: boolean
  final bool? replace;

  /// TS: any
  final Object? state;

  /// JSON-safe map for prop encoding through the JS bridge.
  Map<String, Object?> toJson() => {
    if (relative != null) 'relative': relative!.value,
    'to': to,
    if (replace != null) 'replace': replace,
    if (state != null) 'state': state,
  };
}

