import 'package:react_tool/src/bundler/shim_pruning.dart';
import 'package:test/test.dart';

/// A generated shim (from `react ts bind --shim`) with two components and a
/// namespaced hook bridge, mirroring the `generateShim` template exactly.
const _shimSource = '''
// GENERATED CODE — DO NOT EDIT.
// Generated by: react ts bind ... --shim
//
// Registers the bound `react-router-dom` components under the
// `reactRouter.*` names used by the generated Dart helpers.
// Wire this module into react.yaml under `foreign.modules`.

import { Link as __reactDartLink, Route as __reactDartRoute, useLocation as __reactDartUseLocation, useParams as __reactDartUseParams } from 'react-router-dom';

const components = {
  'reactRouter.Link': __reactDartLink,
  'reactRouter.Route': __reactDartRoute,
};

for (const [name, component] of Object.entries(components)) {
  globalThis.__reactDartRegisterComponent?.(name, component);
}

// Hook bridge: the generated Dart hooks (`--hooks` output) call
// these members during render.
const toPairs = (v) => {
  if (v == null) return v;
  return v;
};

const hooks = {
  useLocation: () => { const v = __reactDartUseLocation(); return v; },
  useParams: () => { const v = __reactDartUseParams(); return toPairs(v ?? {}); },
};

globalThis.__reactDartBindings ??= Object.create(null);
globalThis.__reactDartBindings.reactRouter = hooks;
''';

const _legacyShimSource = '''
import { useLocation as __reactDartUseLocation } from 'some-lib';

const components = {};

for (const [name, component] of Object.entries(components)) {
  globalThis.__reactDartRegisterComponent?.(name, component);
}

const hooks = {
  useLocation: () => __reactDartUseLocation(),
};

globalThis.__reactDartHooks = hooks;
''';

void main() {
  group('parseForeignShim', () {
    test('extracts specifier, aliases, component keys, hooks, namespace', () {
      final shim = parseForeignShim(_shimSource)!;
      expect(shim.specifier, 'react-router-dom');
      expect(
        shim.aliasByExport,
        {
          'Link': '__reactDartLink',
          'Route': '__reactDartRoute',
          'useLocation': '__reactDartUseLocation',
          'useParams': '__reactDartUseParams',
        },
      );
      expect(shim.componentKeys, ['reactRouter.Link', 'reactRouter.Route']);
      expect(shim.hookNames, ['useLocation', 'useParams']);
      expect(shim.namespace, 'reactRouter');
    });

    test('treats a legacy __reactDartHooks bridge as no namespace', () {
      final shim = parseForeignShim(_legacyShimSource)!;
      expect(shim.namespace, isNull);
      expect(shim.hookNames, ['useLocation']);
    });

    test('returns null for non-generated modules', () {
      expect(
        parseForeignShim(
          'export const Card = () => <div>card</div>;\n',
        ),
        isNull,
      );
    });
  });

  group('pruneShim', () {
    test('keeps only used components and hooks, pruning the import', () {
      final shim = parseForeignShim(_shimSource)!;
      final pruned = pruneShim(
        _shimSource,
        shim: shim,
        usedComponents: {'reactRouter.Route'},
        usedHooks: {'reactRouter.useLocation'},
      );
      expect(pruned, isNot(contains("'reactRouter.Link'")));
      expect(pruned, contains("'reactRouter.Route'"));
      expect(pruned, isNot(contains('__reactDartLink')));
      expect(
        pruned,
        contains(
          "import { Route as __reactDartRoute, useLocation as __reactDartUseLocation } from 'react-router-dom';",
        ),
      );
      expect(pruned, contains('useLocation: ('));
      expect(pruned, isNot(contains('useParams:')));
      expect(pruned, contains('__reactDartBindings.reactRouter = hooks;'));
      expect(pruned, contains('for (const [name, component]'));
    });

    test('drops the whole hook bridge when no hook is used', () {
      final shim = parseForeignShim(_shimSource)!;
      final pruned = pruneShim(
        _shimSource,
        shim: shim,
        usedComponents: {'reactRouter.Link', 'reactRouter.Route'},
        usedHooks: const {},
      );
      expect(pruned, isNot(contains('const toPairs')));
      expect(pruned, isNot(contains('__reactDartBindings')));
      expect(pruned, isNot(contains('useLocation')));
      expect(pruned, contains('globalThis.__reactDartRegisterComponent'));
    });

    test('keeps the hook bridge on legacy shims with bare keys', () {
      final shim = parseForeignShim(_legacyShimSource)!;
      final pruned = pruneShim(
        _legacyShimSource,
        shim: shim,
        usedComponents: const {},
        usedHooks: {'useLocation'},
      );
      expect(pruned, contains('globalThis.__reactDartHooks = hooks;'));
      expect(pruned, contains('useLocation:'));
    });

    test('drops the import entirely when nothing is used', () {
      final shim = parseForeignShim(_shimSource)!;
      final pruned = pruneShim(
        _shimSource,
        shim: shim,
        usedComponents: const {},
        usedHooks: const {},
      );
      expect(pruned, isNot(contains('import {')));
      expect(pruned, contains('const components = {\n};'));
      expect(pruned, isNot(contains('__reactDartBindings')));
    });
  });
}
