name: example
resolution: workspace
publish_to: none
environment:
  sdk: ">=3.12.0 <4.0.0"
dependencies:
  react: ^0.1.0
  react_js: ^0.1.0
  react_dom: ^0.1.0
  react_server: ^0.1.0
  react_server_shelf: ^0.1.0
  react_web: ^0.1.0
  react_actions: ^0.1.0
  react_router: ^0.0.1
  react_zustand: ^0.0.1
  react_riverpod: ^0.0.1
  react_bloc: ^0.0.1
  shelf: ^1.4.0
  shelf_static: ^1.1.3
  riverpod: any
  bloc: any
dev_dependencies:
  build_runner: ^2.15.3
  react_codegen: ^0.1.0
  lints: ^6.1.0
  react_testing: ^0.1.0
  server_testing: ^0.4.0
  server_testing_shelf: ^0.4.0
  test: ^1.31.2
