name: react_web
resolution: workspace
environment:
  sdk: ">=3.12.0 <4.0.0"
dependencies:
  http: ^1.2.0
  react:
    path: ../react
  react_actions:
    path: ../react_actions
  react_js:
    path: ../react_js
  web: ^1.1.0
